### ISSUE TITLE
Default scope is insufficient for private org membership

### ISSUE THREAD

**Issue by athornton** [jupyterhub/oauthenticator#105]
The way we determine membership in the org whitelist is to, as an authenticated user, ask for `/orgs/[org]/members`.  The issue is, even if you're authenticated, unless you have `read:org` scope, you only get the members whose membership is public.

This is, to be charitable, unclear from the GitHub API documentation and took me quite a while to figure out.

This appears to be a conscious design decision on GitHub's part, since `/user/orgs` also requires `read:org` (or `user`, though I haven't tested that) scope (and would require a second API call as well).  It may be that the best we can do is document this thoroughly and fix the base class so `scope` is a configurable.

**Comment by minrk** [comment]
Thanks for tracking this down! We should definitely make scopes a configurable, and we can also do some things like add `read:org` to scopes if org_whitelist is enabled.

**Comment by manics** [comment]
This should be working now!
