### ISSUE TITLE
hard-coded gitlab api version 'v3' will need to handle switch to 'v4'

### ISSUE THREAD

**Issue by Analect** [jupyterhub/oauthenticator#119]
Just flagging that 'v3' of the gitlab api is hard-coded [here](
https://github.com/jupyterhub/oauthenticator/blob/master/oauthenticator/gitlab.py#L29).

From [here](https://docs.gitlab.com/ce/api/v3_to_v4.html), 'v3' was deprecated earlier this year and support for it was removed since version 9.5 of Gitlab release in August 2017.  Apparently, only 'v4' will be handled from version 9.5 onwards.  Having said that, calls against the v3 api still appear to work for gitlab.com which is running version 9.5.4.

Users that are using a self-hosted gitlab instances may have both old and newer versions of gitlab, so perhaps parameterising the version using something like `GITLAB_API_VERSION` may make sense, with the default set to `4` of `v4`.

**Comment by willingc** [comment]
Thanks @Analect for the heads up re: versioning.

**Comment by Analect** [comment]
Just updating this as the latest reference to API v3 removal I've seen.  It seems from [here](https://about.gitlab.com/2017/09/22/gitlab-10-0-released/#api-v3) that that is now not scheduled until version 11 of gitlab, which is probably still at least 6 months away.  It seems too many on gitlab.com are still hitting the v3 end-points for it to be feasible for them to switch it off at this point.

**Comment by akhmerov** [comment]
It [seems](https://docs.gitlab.com/ce/api/v3_to_v4.html) that the relevant endpoints didn't change, so if I understand correctly, the corresponding fix would be to just make the api version configurable. On a related note: why is `GITLAB_HOST` read from `os.environ`, as opposed to being a traitlet? Is there a reason for this?

**Comment by jbweston** [comment]
>  why is GITLAB_HOST read from os.environ, as opposed to being a traitlet? Is there a reason for this?

Seems that it is used in other places in the module that are not directly related to the Authenticator (e.g. `GitLabMixin`, which is used by the `GitLabLoginHandler`)
