### ISSUE TITLE
Make GITHUB_HOST configurable in jupyterhub_config.py

### ISSUE THREAD

**Issue by rwmajor2** [jupyterhub/oauthenticator#122]
When trying to run jupyterhub as a service, environment variables get stripped on Ubuntu.  It would be nice where the github_host setting is an additional setting in the jupyterhub_config.py file, e.g.

c.GitHubOAuthenticator.github_host = 'githubenterprise.org.com'

**Comment by minrk** [comment]
In the meantime, you could set the environment variable in your `jupyterhub_config.py`:

```python
os.environ['GITHUB_HOST'] = 'githubenterprise.horse'
```

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
