### ISSUE TITLE
Problems with CILogon parameters

### ISSUE THREAD

**Issue by davidedelvento** [jupyterhub/oauthenticator#133]
This is partially a follow up on issue #114 (only partially, so I'm opening a new issue instead of continuing there), and involves usernames (as #114) but also skins and identity providers.

Let's start from usernames. As the comment says in this code snippet https://github.com/jupyterhub/oauthenticator/blob/2b462c547ed8832f7e832f094134762e7cab6cc0/oauthenticator/cilogon.py#L149-L152 this is not ideal. At the moment this returns something like `http://cilogon.org/servera/users/NNNN` which is far from the actual username (`NNNN` is probably a UID on some machine, but not the text username). This could be probably fixed by using  `eppn` instead of `sub` in the above snipped. However, other people might want to use something different, e.g. email, so why not leaving that end-user-configurable and getting its value from an environment variable such as `CILOGON_CLAIM`? When not set, let's use `sub` (and when not found, before `return`ing `None`, let's spit a message in the logs about what was looked for and not found).

---

Somewhat related to this, I'd like to configure the skin and identity provider which seem to be possible (or at least thought as possible) looking at https://github.com/jupyterhub/oauthenticator/blob/2b462c547ed8832f7e832f094134762e7cab6cc0/oauthenticator/cilogon.py#L58-L62

However (and this could be my ignorance) I can't figure out how to set `self.authenticator.skin` and `idp`. If that part is still missing, how again using environmental variables `CILOGON_SKIN` and `CILOGON_IDP` while preserving current behavior when not set? From a user's perspective (who is not actually calling cilogon.py, but starting the jupyterhub server with various configurations) the environmental variables seem a better solution, and people are already setting `CILOGON_CLIENT_ID` and `CILOGON_CLIENT_SECRET` anyway, so this is not something different from what they are already doing.

---
If this sounds like a good approach, I'll be happy to implement these changes and make a PR myself if necessary.

Thanks @eshook @jbasney

**Comment by minrk** [comment]
@davidedelvento to set these variables, in your `jupyterhub_config.py` add:

```python
c.CILogonOAuthenticator.skin = 'myskin'
c.CILogonOAuthenticator.idp = 'myidp'
```

In general, that's how all configuration of JupyterHub is done. Environment variables are available for certain auth-related configuration, such as secrets that one wants to avoid putting in files. But for the most part, configuration is done via the configuration file.

Picking a different key for the username does sound like the right thing to do. The email address is what used to be used with OAuth 1, and I think that's the right thing to use. That's what Google uses, etc. The oauth1 implementation avoided including `@` in the username due to some mishandled URLs, but that has since been fixed, so using emails as-is for username should be safe and the right thing to do.

**Comment by davidedelvento** [comment]
@minrk thanks for suggesting me about the `jupytherhub_config.py`. Of course I knew about that file and of course I use if for various other settings, but I did not connect the dots...

So, for the username, instead of hardcoding `sub`, can we use self.authenticator.claim (if set)? If so, would you prefer a PR, or doing the (very small) code change yourself?

Thanks also for the very prompt response.

**Comment by minrk** [comment]
A PR would be great! I've got myself setup with a CILogon test application, so I can try to test this myself if you issue a PR.

I would probably use something like `authenticator.username_key` or something else that identifies it as the source of the JupyterHub username.
