### ISSUE TITLE
stripping the domain from cilogon usernames?

### ISSUE THREAD

**Issue by davidedelvento** [jupyterhub/oauthenticator#140]
This is related to #133 @eshook @jbasney @zonca 

oauthenticator/google.py has a "hosted_domain" configuration option that strips off the domain from the username value. I think something similar would be nice to have for oauthenticator/cilogon.py when you're using a single IdP (e.g. in my case everybody has a `@xsede.org` suffix) to prevent messing up with usernames with `@` and `.` in them.

Alternatively, I could make a callback option to set up in `jupytherhub_config.py` where the user would specify which "massage" (if any) to give to the username strings.

As before, I'd be happy to provide a PR, if given some guidance on what would be best for the project and more likely to be accepted.

**Comment by minrk** [comment]
That sounds like a good idea. A similar `idp_whitelist` and `strip_idp_domain` pair of configurables along the lines of:

```python
name, idp = email.split('@')
if self.idp_whitelist and idp not in self.idp_whitelist:
    # reject login
if len(self.idp_whitelist) == 1 and self.strip_idp_domain:
    username = name
else:
    username = email
```

ought to work.

**Comment by davidedelvento** [comment]
see PR #145 I tested in my implementation and it works for me

**Comment by davidedelvento** [comment]
see PR #145 I tested in my implementation and it works for me

**Comment by davidedelvento** [comment]
@minrk I see this is merged and works fine for me. 
To properly plan my work, do you have any sense in when it might be included in an official release?
Thanks!

**Comment by willingc** [comment]
Thanks @davidedelvento for letting us know it works. I've opened https://github.com/jupyterhub/oauthenticator/issues/170 to track the next official release.
