### ISSUE TITLE
Issue behind a corporate proxy

### ISSUE THREAD

**Issue by daleshsd** [jupyterhub/oauthenticator#142]
Running Jupyterhub in a docker container ( FROM jupyterhub/jupyterhub:0.8.0 ) and am able to authenticate and launch notebooks when the oauth service runs inside the same network . 
When i point to an oauth service that requires me to cross the corporate proxy however  i get the following exception..
    **File "/opt/conda/lib/python3.5/site-packages/oauthenticator/generic.py", line 98, in authenticate
        resp = yield http_client.fetch(req)
    tornado.curl_httpclient.CurlError: HTTP 599: Couldn't resolve host ....**
I have not been able to configure the https/http proxy , based on similar reported issues i tried the following in my jupyterhub_config.py for example with no luck.
http_proxy = os.environ.get('http_proxy')
if http_proxy:
    if http_proxy[:7] == "http://":
        http_proxy = http_proxy[7:]
    defaults['proxy_host'], defaults['proxy_port'] = http_proxy.split(":")
    defaults['proxy_port'] = int(defaults['proxy_port'])
AsyncHTTPClient.configure("tornado.curl_httpclient.CurlAsyncHTTPClient", defaults=defaults)

**Comment by daleshsd** [comment]
Works fine with the latest releases.

**Comment by dtandersen** [comment]
I had to do more work.

`AsyncHTTPClient.configure("tornado.curl_httpclient.CurlAsyncHTTPClient", defaults=defaults)` didn't work from config.yaml.

```
  extraConfig: |
    import pycurl
    import certifi
    from tornado.httpclient import HTTPRequest

    def configure_proxy(curl):
        logging.error(curl.getinfo(pycurl.EFFECTIVE_URL))
        if "google" in curl.getinfo(pycurl.EFFECTIVE_URL):
            logging.error("adding proxy")
            curl.setopt(pycurl.PROXY, "proxy.example.com")
            curl.setopt(pycurl.PROXYPORT, 8080)

    # never do this
    HTTPRequest._DEFAULTS['prepare_curl_callback'] = configure_proxy
```
