### ISSUE TITLE
GitLab authenticator requires `scope` to be set in order to work

### ISSUE THREAD

**Issue by jkinkead** [jupyterhub/oauthenticator#146]
The GitLab authenticator doesn't work unless you set a scope to include `read_user`:

```python
# In jupyterhub_config.py
c.GitLabOAuthenticator.scope = ['read_user']
```

This should probably be the default for that authenticator.

**Comment by jkinkead** [comment]
Oh: I'm using GitLab CE, not public GitLab.

**Comment by fnordian** [comment]
I can confirm this issue for public GitLab.

**Comment by nickray** [comment]
Confusingly, using the `openid` scope does not work.

**Comment by consideRatio** [comment]
`read_user` is indeed required, and `api` is required at least if gitlab is to validate membership of various groups etc as part of authorization using group membership is configured.

**Comment by sanderploegsma** [comment]
@consideRatio According to [the oauthenticator docs](https://oauthenticator.readthedocs.io/en/latest/gitlab.html) the `openid` scope grants read-only permission to group memberships. Therefore, shouldn't that suffice for the authenticator when using `allowed_gitlab_groups`?

If not, perhaps it makes sense to at least document this requirement somewhere, since it's indeed very confusing.

**Comment by consideRatio** [comment]
@sanderploegsma if you know whats minimally required, any clarifications is greatly appreciated! I'm a bit lost on what is required for two key reasons:

1. The oauthenticator app may have added some scope automatically beyond what is configured - a practice I'd like to avoid and deprecate. I'm not sure if that happens for the GitLabOAuthenticator if some essential scope and primitive scope is omitted.
2. GitLab's API itself has evolved over time, providing more detailed scope requests etc.

**Comment by sanderploegsma** [comment]
Looking at the source I think I see why additional scopes are required: checking `allowed_project_ids` requires additional scopes beyond `openid`. `read_api` should be sufficient for this though, there is no need for write-access at all for an authenticator IMO.

But, group membership is exposed through the OpenID Connect provider ([docs](https://docs.gitlab.com/ee/integration/openid_connect_provider.html)), so in theory the authenticator should be able to check `allowed_gitlab_groups` by calling `/oauth/userinfo` with the `openid` scope.
