### ISSUE TITLE
There is issue with getting back the user info from Auth0

### ISSUE THREAD

**Issue by YOxan** [jupyterhub/oauthenticator#148]
It seems like resp_json["email"] is empty (in fact resp_json at all) when you are trying to log in with using Auth0. I debugged with access_token which one was returned in the code and it seems like the response from auth0 is empty (even for curl). Such an issue could happen if you don't pass 'scope' param to the Auth0 (see authorize endpoint - there should be at least 'email'). 

```python
c.Auht0OAuthenticator.scope = ['openid', 'email']
```
If add such a line it works fine.

**Comment by jlondal** [comment]
I have put c.Auht0OAuthenticator.scope = ['openid', 'email'] into jupyterhub_config.py but I am still getting the same error?

**Comment by tobiaskaestner** [comment]
Please mind the typo in YOxan answer: it should read:
`c.Auth0OAuthenticator.scope = ['openid', 'email']`

**Comment by daniel-ciocirlan** [comment]
Hey @YOxan could I ask you how you made this work in the first place? The Auth0 authenticator doesn't even seem to call the `authenticate` method. 

My config looks like this - am I missing something?

```c.JupyterHub.log_level = 10
from oauthenticator.auth0 import Auth0OAuthenticator, LocalAuth0OAuthenticator

c.Auth0OAuthenticator.client_id = '(redacted)'
c.Auth0OAuthenticator.client_secret = '(redacted)'
c.Auth0OAuthenticator.oauth_callback_url = 'http://localhost:8000/hub'
c.Auth0OAuthenticator.scope = ['openid', 'email'] # your line

c.JupyterHub.authenticator_class = LocalAuth0OAuthenticator
c.LocalAuth0OAuthenticator.create_system_users = True

c.Authenticator.whitelist = whitelist = set()
c.JupyterHub.admin_users = admin = set()```

**Comment by daniel-ciocirlan** [comment]
I found the issue - I dug this up from an older slide of Min RK's.

The callback url must be exactly `(yourdomain)/hub/oauth_callback`, so like this:

```
c.Auth0OAuthenticator.oauth_callback_url = 'http://localhost:8000/hub/oauth_callback'

**Comment by umar-sik** [comment]
Hey, 
I am using Auth0 but its always giving me the error "O-Auth state missing form cookies". Does anyone have any idea why is that? P.S I am using Kubespawner.

**Comment by EndlessTJ** [comment]
@umar-sik I have the same problem.Do you have any solutions？

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
