### ISSUE TITLE
Option to automatically create users

### ISSUE THREAD

**Issue by davidedelvento** [jupyterhub/oauthenticator#149]
As you know I'm using CILogon (restricted to XSEDE only), but I think this would apply to other oauth providers too, so it could be an OAuthenticator feature.

I've been asked to automatically create users when they successfully authenticate. I know there are pros and cons of doing so, but I think in some circumstances the pros outweight  the cons. In fact, LocalAuthenticator has [an option](http://jupyterhub.readthedocs.io/en/latest/getting-started/authenticators-users-basics.html#use-localauthenticator-to-create-system-users) to do so.

I was wondering if this would be a feature that could be added to `OAuthenticator` (or perhaps to `CILogon` if you think it's not generic enough).

@zonca @eshook

**Comment by davidedelvento** [comment]
@minrk Is there any chance that this would be worked on, or should we instead close it?

**Comment by minrk** [comment]
There's a `Local` variant of each OAuthenticator:

```python
from oauthenticator.cilogon import LocalCILogonOAuthenticator

c.JupyterHub.authenticator_class = LocalCILogonOAuthenticator
c.LocalCILogonOAuthenticator.create_system_users = True
```

**Comment by davidedelvento** [comment]
Thanks, I'll give it a try and let you know

**Comment by renambot-uic** [comment]
Is this supposed to work ? It doesn't create user with Github auth.

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
