### ISSUE TITLE
how do i save the user with gitlab?

### ISSUE THREAD

**Issue by akkibatra** [jupyterhub/oauthenticator#150]
For gitHub we use "c.LocalGitHubOAuthenticator.create_system_users = True" this code. But I can't figure it out for GitLab. I tried "c.LocalGitLabOAuthenticator.create_system_users = True", but it doesn't work.

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
