### ISSUE TITLE
Token-based authentication

### ISSUE THREAD

**Issue by daniel-ciocirlan** [jupyterhub/oauthenticator#156]
How can one implement token authentication instead of cookie-based authentication (as I see the it's currently written)?

I'm trying to authenticate on JupyterHub from a web app and it doesn't seem to work because oauthenticator throws `OAuth state missing from cookies` in my face. This happens although the web app and jupyterhub are hosted on the same domain (my local machine, with some nginx proxies) and the web app is writing the `oauthenticator-state` cookie with the `state` received by the authenticator (Auth0) in my case. Oauthenticator doesn't seem to find it.

Because most major authenticators give you authentication tokens, it would be super helpful if oauthenticator can have this implemented entirely instead of the cookie-based method.

Happy to roll my sleeves and contribute if nobody has the time, but I'd need some help.

**Comment by umar-sik** [comment]
I am also having the same problem. I am using kubernetes along with jupyterhub and even though the call back url pre registered with the authenticator (Auth0) is the same as the jupyterhub host, this error ('OAuth state missing from cookies') is consistent. 

Any help would be appreciated.

**Comment by consideRatio** [comment]
Here is [a thread in the Jupyter forum to continue a discussion about this](https://discourse.jupyter.org/t/using-jwt-as-an-authentication-for-login/5466).

My current understanding is that it is out of scope for this repo to implement JWT based authentication, but, I lack some understanding about this in general so I may very well change my mind given more information and understanding about this.
