### ISSUE TITLE
Error when using generic oauthenticator

### ISSUE THREAD

**Issue by stefanonicotri** [jupyterhub/oauthenticator#160]
Hi,
I have a problem using the generic oauthenticator.
I am authenticating against https://iam-test.indigo-datacloud.eu/, a working OAuth2/OpenID Connect IAM server, using the following configuration file:
<pre>
c.JupyterHub.port = 443
c.JupyterHub.proxy_cmd = ['configurable-http-proxy', '--redirect-port', '80']
c.JupyterHub.ssl_cert = 'PATH_TO_CERT'
c.JupyterHub.ssl_key = 'PATH_TO_KEY'
c.GenericOAuthenticator.oauth_callback_url = 'https://jupyterhub.cloud.ba.infn.it/hub/oauth_callback'
c.GenericOAuthenticator.client_id = 'CLIENT_ID'
c.GenericOAuthenticator.client_secret = 'CLIENT_SECRET'
c.GenericOAuthenticator.token_url = 'https://iam-test.indigo-datacloud.eu/token'
from oauthenticator.generic import GenericOAuthenticator
c.JupyterHub.authenticator_class = GenericOAuthenticator
</pre>
and exporting:
<pre>
OAUTH2_AUTHORIZE_URL=https://iam-test.indigo-datacloud.eu/authorize
OAUTH2_TOKEN_URL=https://iam-test.indigo-datacloud.eu/token
</pre>
after the authentication step, I get redirected to JupyterHub and I get a 500: Internal Server Error.
The log says:
<pre>
Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/tornado/web.py", line 1445, in _execute
        result = yield result
      File "/usr/local/lib/python3.4/dist-packages/oauthenticator/oauth2.py", line 182, in get
        user = yield self.login_user()
      File "/usr/local/lib/python3.4/dist-packages/jupyterhub/handlers/base.py", line 327, in login_user
        authenticated = yield self.authenticate(data)
      File "/usr/local/lib/python3.4/dist-packages/jupyterhub/auth.py", line 221, in get_authenticated_user
        authenticated = yield self.authenticate(handler, data)
      File "/usr/local/lib/python3.4/dist-packages/oauthenticator/generic.py", line 117, in authenticate
        resp = yield http_client.fetch(req)
      File "/usr/local/lib/python3.4/dist-packages/tornado/simple_httpclient.py", line 207, in __init__
        self.request.url)
    ValueError: Unsupported url scheme:
</pre>

Can you please help me with this problem?
many thanks,
ste

**Comment by mransley** [comment]
Did you fix this, I am getting the same error.

**Comment by mransley** [comment]
I got the generic provider working with Okta.  My config was as follows:

In my jupyterhub_config.py I have the following lines:

```
from oauthenticator.generic import LocalGenericOAuthenticator
c.JupyterHub.authenticator_class = LocalGenericOAuthenticator
```

And I defined the following variables:

```
export OAUTH2_AUTHORIZE_URL="https://somewhere.okta.com/oauth2/v1/authorize?scope=openid email"
export OAUTH2_TOKEN_URL=https://somewhere.okta.com/oauth2/v1/token
export OAUTH2_USERDATA_URL=https://somewhere.okta.com/oauth2/v1/userinfo
export OAUTH_CLIENT_ID="xxx"
export OAUTH_CLIENT_SECRET="xxx"
export OAUTH_CALLBACK_URL=http://192.168.1.60:8000/hub/oauth_callback
export OAUTH2_USERNAME_KEY="email"

```

I hope this helps!

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
