### ISSUE TITLE
OpenShift OAuth: A non-empty X-CSRF-Token header is required to receive basic-auth challenges

### ISSUE THREAD

**Issue by vpavlin** [jupyterhub/oauthenticator#162]
Hi, I am trying to setup OAuth with OpenShift using Service Accounts, but I got

```
A non-empty X-CSRF-Token header is required to receive basic-auth challenges
```

Error from OpenShift and not sure what to try next. Based on docs (https://docs.openshift.com/online/architecture/additional_concepts/authentication.html)

> To prevent cross-site request forgery (CSRF) attacks against browser clients, Basic authentication challenges should only be sent if a X-CSRF-Token header is present on the request. Clients that expect to receive Basic WWW-Authenticate challenges should set this header to a non-empty value.

It sounds like the OAuth lib is not setting X-CSRF-Token - have you seen this before?

**Comment by GrahamDumpleton** [comment]
This issue is likely not relevant as ``WWW-Authenticate`` challenge likely wasn't the correct approach anyway. Real problem with with why OpenShift authenticator has been working is in https://github.com/jupyterhub/oauthenticator/issues/165
