### ISSUE TITLE
Default scope setting on wrong class in OpenShift authenticator.

### ISSUE THREAD

**Issue by GrahamDumpleton** [jupyterhub/oauthenticator#165]
In the OpenShift authenticator, the code has:

```
class OpenShiftLoginHandler(OAuthLoginHandler, OpenShiftMixin):
    # This allows `Service Accounts as OAuth Clients` scenario
    # https://docs.openshift.org/latest/architecture/additional_concepts/authentication.html#service-accounts-as-oauth-clients
    scope=['user:info']
```

The authenticator doesn't actually work though with the problem being that when talking to OpenShift it is ignoring that scope and asking for ``user:full`` instead of ``user:info``, which OpenShift rejects.

After experimentation it was found it could be made to work by using:

```
from oauthenticator.openshift import OpenShiftOAuthenticator
c.JupyterHub.authenticator_class = OpenShiftOAuthenticator
OpenShiftOAuthenticator.scope = ['user:info']
```

That is, set the ``scope`` on the ``OpenShiftOAuthenticator`` class.

Am happy to create a PR, but I don't know anything about OAuth and so seeking guidance first.

Was it just wrong that ``scope`` was set on ``OpenShiftLoginHandler`` in the first place and it should have been on ``OpenShiftOAuthenticator`` or is there some requirement for it also to be on ``OpenShiftLoginHandler``?

Many of the other authenticators only set scope on the ``OAuthenticator`` class and not on ``LoginHandler`` handler class. The Google authenticator has it on both though, with that on the ``LoginHandler`` referring to that on the ``OAuthenticator`` class. What is recommended/required practice?

Also, note that OpenShift supports two endpoints for authentication, global and project specific service account. I have only tried with the project service account method. I can't see that how ``oauthenticator`` would work would be any different for each though.

For further discussion around this issue see https://github.com/jupyter-on-openshift/jupyterhub-quickstart/issues/1

**Comment by willingc** [comment]
@GrahamDumpleton FYI. I've been working through the jupyter-on-openshift quickstart. Ran into a runtime error. 

Did #171 fully resolve this issue? Thanks.

**Comment by GrahamDumpleton** [comment]
The ``oauthenticator`` patch is very specific to using OpenShift as an OAuth provider. It isn't used in normal ``jupyterhub-quickstart`` repository.

**Comment by manics** [comment]
I'm closing this as it's quite old and there's no concrete action point. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/) or open a new issue. Thanks!
