### ISSUE TITLE
OAUTH

### ISSUE THREAD

**Issue by Rachidramadan1990** [jupyterhub/oauthenticator#166]
Hello,

I am trying to set up jupyterhub on my localhost using the following video tutorial:
https://www.youtube.com/watch?v=gSVvxOchT8Y

I achieved to authenticate with PAM.
 When I want to use the GitHub authentification
like described in the video, I get to the page with the orange button (login with github).
When I push that button, I get the Error 404: This is not the web page you are looking for. 
I double checked the my Client ID and the Client Secret.
This is how my config file looks like:

# Configuration file for jupyterhub.

c.JupyterHub.ssl_key = 'Jupyterhub.key'
c.JupyterHub.ssl_cert = 'jupyterhub.crt'
c.JupyterHub.port = 8000

from oauthenticator.github import GitHubOAuthenticator
c.JupyterHub.authenticator_class = GitHubOAuthenticator
c.GitHubOAuthenticator.create_system_users = True

Any ideas?

**Comment by minrk** [comment]
I think you'll get a 404 if the client id and/or client secret is incorrect. How are you setting them? You can set them in the config file or via environment variables.

**Comment by Rachidramadan1990** [comment]
I tried both.I added them in the env file and in the config file.
To add them in the config file, I added this command:

c.MyOAuthenticator.oauth_callback_url = 'https://localhost:8000/hub/oauth_callback'
c.MyOAuthenticator.client_id = '2baef196226560dc1506'
c.MyOAuthenticator.client_secret = '**************************************'

**Comment by raghu20ram** [comment]
hi @minrk  i am trying to use oauth for jupyterhub using github credentials, but i am unsuccessful in doing it. Can you share me an reference docs related to it if available

**Comment by nmvega** [comment]
> I tried both.I added them in the env file and in the config file.
> To add them in the config file, I added this command:
> 
> c.MyOAuthenticator.oauth_callback_url = 'https://localhost:8000/hub/oauth_callback'
> c.MyOAuthenticator.client_id = '2baef196226560dc1506'
> c.MyOAuthenticator.client_secret = '**************************************'

You have to change `MyOAuthenticator` part to match the authenticator you chose. For example, if you chose `GitHub` or `GitLab`, then respectively they would be:

```
c.GitHubOAuthenticator.oauth_callback_url = 'https://localhost:8000/hub/oauth_callback'
c.GitHubOAuthenticator.client_id = '2baef196226560dc1506'
c.GitHubOAuthenticator.client_secret = '**************************************'
```
and

```
c.GitLabOAuthenticator.oauth_callback_url = 'https://localhost:8000/hub/oauth_callback'
c.GitLabOAuthenticator.client_id = '2baef196226560dc1506'
c.GitLabOAuthenticator.client_secret = '**************************************'
```

**Comment by consideRatio** [comment]
Thanks for providing help @nmvega! :heart:
