### ISSUE TITLE
Preserve case for usernames in MWOAuthenticator

### ISSUE THREAD

**Issue by chicocvenancio** [jupyterhub/oauthenticator#168]
MediaWiki allows for multiple users with different cases (except for the first letter, Chicocvenancio and chicocvenancio are the same users, but chicocVenancio is a different one).

Should we not preserve the user case from MediaWiki? Maybe we can define normalize_username without lowercasing the username?

See https://phabricator.wikimedia.org/T180336

**Comment by willingc** [comment]
@chicocvenancio Which version of JupyterHub and OAuthenticator are you using?

This had been addressed in the past for GitHub authentication: https://github.com/jupyterhub/oauthenticator/issues/52 Let's first rule out if a version is out of date.

**Comment by chicocvenancio** [comment]
We're using the 0.6 zero-to-jupyterhub-k8s ( https://github.com/yuvipanda/paws/commit/4d5eeb164e83bf3ccdc2e3ecaecab90502e1eaca ).
That works out to be 0.8.1 for jupyterhub and 0.7.2 for oauthenticator. 
I'm pretty sure since neither OAuthenticator nor MWOAuthenticator reimplement normalize_username the normalization from [auth.py#L189](https://github.com/jupyterhub/jupyterhub/blob/4b11f8f26b1fd987f4b9b08f611f8fe943d871c2/jupyterhub/auth.py#L189) will stand.
> root@hub-864dc78ff-sc8q8:/srv/jupyterhub# pip3 freeze
> jupyterhub==0.8.1
> oauthenticator==0.7.2

**Comment by willingc** [comment]
Looking at the mediawiki authenticator, I think (not certain) that mediawiki.py may need a mixin like https://github.com/jupyterhub/oauthenticator/blob/master/oauthenticator/github.py#L49 and then have the MWLoginHandler subclass from OAuthLoginHandler.

cc/ @minrk

**Comment by minrk** [comment]
Defining a custom normalize_username for MW that does something different (e.g. nothing) should work for this.
