### ISSUE TITLE
Plan for next release of oauthenticator

### ISSUE THREAD

**Issue by willingc** [jupyterhub/oauthenticator#170]
Prompted by a question in #140.

We should determine when the next release will occur.

**Comment by GrahamDumpleton** [comment]
Then I need to get a PR to you for https://github.com/jupyterhub/oauthenticator/issues/165 ASAP then. :-)

Going to have to assume change I have in mind is okay as got no feedback on what should be done.

**Comment by davidedelvento** [comment]
Thank you @willingc for tracking down this. I saw that the new release 0.7.3 has been issue 12 days ago and I thought it would have included my merged changes, which I am waiting for eagerly.
Unfortunately, it doesn't (not sure why). I hope the subsequent release is issue soon.

**Comment by willingc** [comment]
Hang tight @GrahamDumpleton. We've been slammed the past few weeks. I'll take a look at the issue later today.

**Comment by willingc** [comment]
@davidedelvento 0.7.3 was a security release. https://github.com/jupyterhub/oauthenticator/commit/9ae4136e9fc31ea5c10d35bc567cf6daef7945d4

**Comment by PrintScr** [comment]
Do you have any estimate when Azure integration will be released? As far as I see, it has already been merged to master.

**Comment by willingc** [comment]
Hi @PrintScr, I don't have a firm estimate on the next release.

@minrk, Thoughts on timing?

**Comment by willingc** [comment]
Thanks for the nudge @davidedelvento. @mirnk, I know you are traveling this week. Any thoughts on the timing for an oauthenticator release?

**Comment by davidedelvento** [comment]
To the few watching this thread: I see that [v0.8.0](https://github.com/jupyterhub/oauthenticator/releases/tag/0.8.0) is out and [it includes](https://github.com/jupyterhub/oauthenticator/blob/0.8.0/oauthenticator/cilogon.py) the changes for PR https://github.com/jupyterhub/oauthenticator/pull/145 

So I'm happy and this issue may be closed as far as I'm concerned (unless you want to use it to always track the **next** release)
