### ISSUE TITLE
Impossible to spawn a notebook instance with Azure integration

### ISSUE THREAD

**Issue by PrintScr** [jupyterhub/oauthenticator#175]
Steps to reproduce:
1. First, you need to have an Azure user with username containing a space character.
2. Use spawner which maps oauth username to local linux user.
3. Login with that account through azure

Expected result:
1. It is possible to create a user with command:
c.Authenticator.add_user_cmd =  ['adduser', '-q', '--home', '/home/USERNAME', '--gecos', '""', '--disabled-password']
and spawn and instance

Actual result:
On user creation following error is thrown and no user is created:
```
ERROR:asyncio:Future exception was never retrieved
future: <Future finished exception=RuntimeError('Failed to create system john king: adduser: To avoid problems, the username should consist only of\nletters, digits,$
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1113, in run
    yielded = self.gen.send(value)
  File "/usr/local/lib/python3.5/dist-packages/jupyterhub/auth.py", line 487, in add_user
    yield gen.maybe_future(self.add_system_user(user))
  File "/usr/local/lib/python3.5/dist-packages/jupyterhub/auth.py", line 516, in add_system_user
    raise RuntimeError("Failed to create system user %s: %s" % (name, err))
RuntimeError: Failed to create system user john king: adduser: To avoid problems, the username should consist only of
letters, digits, underscores, periods, at signs and dashes, and not start with
a dash (as defined by IEEE Std 1003.1-2001). For compatibility with Samba
machine accounts $ is also supported at the end of the username
```

**Comment by minrk** [comment]
This should be handled in the `.normalize_username` method on the Authenticator.

**Comment by PrintScr** [comment]
@minrk 
Okay, thanks, I solve the issue in the following way in jupyterhub_config.py:
`from oauthenticator.azuread import LocalAzureAdOAuthenticator
class NormalizedLocalAzureAdOAuthenticator(LocalAzureAdOAuthenticator):
    def normalize_username(self, username):
        return username.lower().replace(' ', '_').replace('.', '_')

c.JupyterHub.authenticator_class = NormalizedLocalAzureAdOAuthenticator`

Is it a proper solution to extend the class and patch it in the configuration?
