### ISSUE TITLE
Add a new CILogon authenticator with SSO verification

### ISSUE THREAD

**Issue by pmcao** [jupyterhub/oauthenticator#178]
Hello,

I am extending the CILogon authenticator to support single-sign-on (SSO) verification using [SVAuth](https://github.com/cs0317/svAuth). The goal is to formally prove correctness of each SSO protocol execution, e.g., a login flow.

The code and demo is ready, and I would like to merge into oauthenticator for the community to use.

Please let me know if this is of jupyterhub/oauthenticator's interest and I will send a pull request. 

Phuong

**Comment by manics** [comment]
Hi, sorry no-one answered you before. We're now encouraging people to package their own authenticators that depend on the core oauthenticator package.
