### ISSUE TITLE
Github OAuthenticator can fail when a soft error is returned from the OAuth endpoint

### ISSUE THREAD

**Issue by davidbath** [jupyterhub/oauthenticator#179]
The github `OAuthenticator` subclass assumes that a successful (at the HTTP level) access token request always returns an `access-token`, here: https://github.com/jupyterhub/oauthenticator/blob/master/oauthenticator/github.py#L119

However, the github endpoint can return a number of explanatory errors in the body of the response, as detailed here: https://developer.github.com/apps/managing-oauth-apps/troubleshooting-oauth-app-access-token-request-errors/, causing the `access-token` assignment to except pretty ungracefully.

**Comment by davidbath** [comment]
Will give it a go!

**Comment by minrk** [comment]
Fixed by #214, I think
