### ISSUE TITLE
Google Oauthenticator excepts when trying to raise an exception

### ISSUE THREAD

**Issue by davidbath** [jupyterhub/oauthenticator#180]
If the google `OAuthenticator` subclass doesn't get a response from the token URL it attempts to clean up the state and then 500 the user, here: https://github.com/jupyterhub/oauthenticator/blob/master/oauthenticator/google.py#L73-L75

However, the `self.clear_all_cookies()` itself appears to except - I believe it might be intended to be `handler.clear_all_cookies()`.

**Comment by minrk** [comment]
@davidbath I think that's right! Probably an artifact of refactoring things from Handler methods to Authenticator methods. Would you like to make a PR?

**Comment by davidbath** [comment]
Sure - it'll be my first one, so might need some gentle correction through the process.
