### ISSUE TITLE
Google auth: Not enforcing hosted domain 

### ISSUE THREAD

**Issue by mascarom** [jupyterhub/oauthenticator#196]
Hi,
I'd like to set up a jupyterhub server that handles users form multiple organizations, but it's fine for me to require they all have a google account (even a personal gmail).
I wonder if an enhancement on the following line would be secure and possible: instead of enforcing the google account to be in the hosted domain a flag would instruct the google authenticator to allow auth to proceed for any successful google authentication.
Whitelist would then prevent random users to log in at all. 
I have prototyped this successfully and it seems to work fine, but I wonder if this is secure.

**Comment by mascarom** [comment]
Uhm, not sure. if you enable a hosted domain (that seems to me mandatory to get oauth to work int he first place, then the following code in google.py restricts you to accounts within your domain only:
        if self.hosted_domain:
            if not username.endswith('@'+self.hosted_domain) or \
                bodyjs['hd'] != self.hosted_domain:
                raise HTTPError(403,
                    "You are not signed in to your {} account.".format(
                        self.hosted_domain)
                )
            else:
                username = username.split('@')[0]

Am I missing something?

My proposal was to add an option to disable this piece of code and allow a generic google account to work. So for example I may host jupyterhub under mydomain.org, and somebody named joe@gmail.com could still be whitelisted and log in.

**Comment by nscozzaro** [comment]
I arrived at this page because I get an error in JupyterHub "Google account domain @gmail.com not authorized" when using my hosted domain. I would suggest updating adding a note about this in the documentation. 

![image](https://user-images.githubusercontent.com/15185105/63227065-7c942800-c1b0-11e9-9777-e9ff95907de7.png)

**Comment by manics** [comment]
I'm closing this as it's quite old. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/) or open a new issue. Thanks!

**Comment by rvernaeshv** [comment]
@nscozzaro hey... How did you solved the "Google account domain @gmail.com not authorized" issue?
