### ISSUE TITLE
Potential problem in Generic OAuth implementation.

### ISSUE THREAD

**Issue by GrahamDumpleton** [jupyterhub/oauthenticator#197]
The generic OAuth implementation has the code:

```
        req = HTTPRequest(url,
                          method=self.userdata_method,
                          headers=headers,
                          validate_cert=self.tls_verify,
                          body=urllib.parse.urlencode({'access_token': access_token})
                          )
        resp = yield http_client.fetch(req)
        resp_json = json.loads(resp.body.decode('utf8', 'replace'))
```

The ``userdata_method`` is set as:

```
    userdata_method = Unicode(
        os.environ.get('OAUTH2_USERDATA_METHOD', 'GET'),
        config=True,
        help="Userdata method to get user data login information"
    )
```

The problem is that Tornado implements sanity checks and will error if you try and use ``GET`` method where you supply a body for the request. The result is an exception of:

```
ValueError: Body must be None for method GET (unless allow_nonstandard_methods is true)
```

The workaround was to set in the configuration ``userdata_method`` to ``POST`` as the target URL for getting user info must allow both ``GET`` and ``POST``. 

* http://openid.net/specs/openid-connect-core-1_0.html#UserInfo

So this should perhaps default to using ``POST`` for ``userdata_method`` since is accepted anyway. Alternatively, need to pass ``allow_nonstandard_methods=True`` to ``HTTPRequest`` class when initialised.

**Comment by minrk** [comment]
#198 sets the default to POST, which I think is ~always the case

**Comment by minrk** [comment]
I misunderstood which step this was. Since it's the userdata method, it's ~always GET so just deleting the body should do it. That's what #198 does now.

**Comment by consideRatio** [comment]
@minrk #198 left a remnant configuration option of `OAUTH2_USERDATA_METHOD` being unusable. As I found it in the source code and examples of accessing the this endpoint on the web utilizing POST, I tried to mimic them and ended up with:

```
ValueError: Body must not be None for method POST (unless allow_nonstandard_methods is true)
```

### Suggested action:
- Remove this configuration option

**Comment by consideRatio** [comment]
Hmmm, figured I'd go ahead and get it done, but stumbled. There is not only an environment variable but also the traitlet configuration and became very uncertain on how to proceed.

https://github.com/jupyterhub/oauthenticator/blob/650174e9801d1c5b046bbc5d7f70fd3120271527/oauthenticator/generic.py#L65-L69

https://github.com/jupyterhub/oauthenticator/blob/650174e9801d1c5b046bbc5d7f70fd3120271527/oauthenticator/generic.py#L136-L140

**Comment by minrk** [comment]
Yes, the userdata option should probably be removed and hardcoded to GET. I'm not aware of an example where userdata should be fetched by any other method.

**Comment by manics** [comment]
Is this still an issue?

**Comment by consideRatio** [comment]
@manics I submitted a PR about the deprecation of the userdata_method, and think we should close this issue no matter what at this point as @minrk fixed the key issue of sending data in a request.
