### ISSUE TITLE
Google oauthenticator does not allow oauth token to be used in notebook

### ISSUE THREAD

**Issue by patwoowong** [jupyterhub/oauthenticator#200]
One would expect a granted token to allow access to the requested scopes in google cloud but the token is not available for use in a user's notebook server.

**Comment by betatim** [comment]
Authentication information is not passed on to the user notebooks by default. You can arrange for it to happen though. Take a look at http://jupyterhub.readthedocs.io/en/latest/reference/authenticators.html#authentication-state for an example how to do that.

**Comment by betatim** [comment]
Yes you can add this as part of the extra config, or if it grows too big make your own hub image.

I'll close this issue now, feel free to re-open if there are more questions or create a new one for a new topic.
