### ISSUE TITLE
Get access token from Jupyter notebook console after authenticating with Keycloak

### ISSUE THREAD

**Issue by michec81** [jupyterhub/oauthenticator#203]
Hi,
I am doing some test with JupyterHub connecting with a Keycloak OAuth2 endpoint, I am using the oauthenticator plugin that I previously installed.

https://github.com/jupyterhub/oauthenticator

actually I can succesfully authenticate to JupyterHub on my VM, but I would like also to print the Keycloak OAuth2 access token on the notebook console. I need it because I have to pass this to a different service to validate. How can I print it? I need some function as i.e. get_token() or something like that. Tried with many libraries (oauth2client, requests, urllib, ...) but cannot figure out what to do.

Thanks in advance,
M

**Comment by consideRatio** [comment]
If you want to access the token on the user, you could perhaps have the spawner set an environment variable in the pre_spawn_start method, I think you can do it like this by having a custom authenticator on top of the one you are using, or by customizing the one your are using. GTG Good luck!

```python
      from z2jh import get_config, get_secret, set_config_if_not_none

      # If we want to do some custom logic when we know whom have logged in...
      from oauthenticator.generic import GenericOAuthenticator
      class MyAuthenticator(GenericOAuthenticator):  
          from tornado import gen

          @gen.coroutine
          def pre_spawn_start(self, user, spawner):
              auth_state = yield user.get_auth_state()
              if not auth_state:
                  return
              # do stuff here... like...
              spawner.environment.update({'CAT_NAME': "missan"})
```

**Comment by consideRatio** [comment]
Perhaps if you all that auth_state stuff? It isn't important to you anyhow as far as I know. May require you to have auth.state.enabled = true in your config.yaml or something, my understand regarding these details are fuzzy.

I would recommend to try setting a static 'LOOK_FOR_ME': 'DOH' environment variable first btw, debugging things this deep down has been quite hard as logs may not reach you so taking small steps could be useful.

**Comment by michec81** [comment]
Solved, thanks a lot for your help!

**Comment by michec81** [comment]
Sorry for asking again, but I find a small problem after doing some test on my application.
I realized that the pre_spawn_start method configures correctly the token bearer in the spawner environment, but the token after a while expires as we expect. Since I pass the token to a remote application service the authentication fails. So I suppose the token should be refreshed someway but I don't know how this could be done. Moreover, for what I know, I can pass the token to the spanwer only using the pre_spawn_start(self, user, spawner) method (/usr/local/lib/python3.6/dist-packages/oauthenticator/generic.py).
Could you give me any help on this?

Thank you again,

Cheers,
Michele

**Comment by michec81** [comment]
I link the new issue:
https://github.com/jupyterhub/oauthenticator/issues/211
