### ISSUE TITLE
[Auth0] Support for using custom domains

### ISSUE THREAD

**Issue by isaurssaurav** [jupyterhub/oauthenticator#207]
I have recently bought a custom domain for Auth0 login's Url.(a.example.com)
But there is no way to pass my new domain Url in jupyterhub's Auth0.
I have tired in with :
`AUTH0_SUBDOMAIN = a.example.com`
But, It adds .auth0.com at last . For e.g a.example.com.auth0.com

Thanks.

**Comment by isaurssaurav** [comment]
i have solved it by, overriding **Auth0LoginHandler** class.
But it would be nice if we have something like `AUTH0_DOMAIN = a.example.com`

**Comment by antoinekrajnc** [comment]
Hi @isaurssaurav, 


Thanks a lot for your answer. I ran into the same issue. Could you provide a little more detail? Did you override the *Auth0LoginHandler* class inside the `.yaml` config file? 

Thanks a lot for your help!

**Comment by isaurssaurav** [comment]
@antoinekrajnc, 
I override the function from jupyerhub_config.py.

So. [This](https://github.com/jupyterhub/oauthenticator/blob/44121eab53ec1a6f6c957b64f438f3cd65377845/oauthenticator/auth0.py) is the class you will be overriding

It's been long, so I don't really remember the details  but here is my jupterhub_config file:

```
from oauthenticator.auth0 import Auth0OAuthenticator
from oauthenticator.auth0 import Auth0LoginHandler

c.JupyterHub.authenticator_class = CustomAuthenticator //this is where you override the function

#Custom Authenticator
class CustomAuth0LoginHandler(Auth0LoginHandler):
    AUTH0_SUBDOMAIN = os.environ['AUTH0_SUBDOMAIN']
    _OAUTH_AUTHORIZE_URL = "https://%s/authorize" % AUTH0_SUBDOMAIN
    _OAUTH_ACCESS_TOKEN_URL = "https://%s/oauth/token" % AUTH0_SUBDOMAIN


class CustomAuthenticator(Auth0OAuthenticator):
    login_handler = CustomAuth0LoginHandler

    @gen.coroutine
    def authenticate(self, handler, data=None):
        AUTH0_SUBDOMAIN = os.environ['AUTH0_SUBDOMAIN']
        code = handler.get_argument("code")
        http_client = AsyncHTTPClient()
        params = {
            'grant_type': 'authorization_code',
            'client_id': self.client_id,
            'client_secret': self.client_secret,
            'code': code,
            'redirect_uri': self.get_callback_url(handler)
        }
        url = "https://%s/oauth/token" % AUTH0_SUBDOMAIN

        req = HTTPRequest(url,
                          method="POST",
                          headers={"Content-Type": "application/json"},
                          body=json.dumps(params)
                          )

        resp = yield http_client.fetch(req)
        resp_json = json.loads(resp.body.decode('utf8', 'replace'))

        access_token = resp_json['access_token']

        # Determine who the logged in user is
        headers = {"Accept": "application/json",
                   "User-Agent": "JupyterHub",
                   "Authorization": "Bearer {}".format(access_token)
                   }

        req = HTTPRequest("https://%s/userinfo" % AUTH0_SUBDOMAIN,
                          method="GET",
                          headers=headers
                          )
        resp = yield http_client.fetch(req)
        resp_json = json.loads(resp.body.decode('utf8', 'replace'))
        return {
            'name': resp_json["email"],
            'auth_state': {
                'access_token': access_token,
                'auth0_user': resp_json,
            }
        }
```
P.S: `AUTH0_SUBDOMAIN is env variable I defined in Dockerfile

I am still not sure this is the right way but hope it helps

**Comment by drhagen** [comment]
I am interested in implementing this because I need it also. This is what I propose:

- Add an attribute `auth0_domain`. The value for `auth0_domain` can be supplied with the following precedence:
  1. `auth0_domain` in `jupyterhub_config.py`
  2. `auth0_subdomain` in `jupyterhub_config.py` (now deprecated)
  2. `AUTH0_DOMAIN` environment variable
  3. `AUTH0_SUBDOMAIN` environment variable (now deprecated)
- The value of `self.auth0_domain` will be used everywhere `{self.auth0_subdomain}.auth0.com` is currently used
- Change the error for not specifying `auth0_subdomain` to instead say that `auth0_domain` is not specified

This should ensure backwards compatibility with current use.

Side question: should I to maintain the `%` string formatting or are f-strings preferred now?

**Comment by drhagen** [comment]
I still need custom Auth0 domains and am willing to do the work. Would a PR implementing the solution described above be considered?
