### ISSUE TITLE
Normalization of user names due to 404 error on worker (GoogleAuth)

### ISSUE THREAD

**Issue by h4gen** [jupyterhub/oauthenticator#210]
I ran into an error which caused the hub to show an 404 page after the spawner tried to redirect to the notebook instance on the worker. I used google authentication but I guess it can happen for every kind of authentication. I do not know what exactly caused the error on the hub side but I figured out that the problem was caused by special characters in the user name. In this case the user names had the format xxx.xxx@company.com leading to user names xxx.xxx  on the hub. This seems to be a problem if oauthenticator is used but not if in development mode with no authentication. I ended up using the `c.Authenticator.username_map()` to normalize the user names. This works pretty well. Maybe this should be documented somewhere.

**Comment by minrk** [comment]
What Spawner were you using? Some username normalization may be required for certain Spawners, and there are a few mechanisms for that.

**Comment by h4gen** [comment]
I use our own custom [AWS spawner](https://github.com/idalab-de/jupyterhub-aws-spawner). But as mentioned it works pretty well with normalization. My post was more for the sake of documentation :)
