### ISSUE TITLE
refresh token on OAuth2 module in Jupyter

### ISSUE THREAD

**Issue by michec81** [jupyterhub/oauthenticator#211]
referring to this old issue:

https://github.com/jupyterhub/oauthenticator/issues/203#issuecomment-417228318

 I find a small problem after doing some test on my application.
I realized that the pre_spawn_start method configures correctly the token bearer in the spawner environment, but the token after a while expires as we expect. Since I pass the token to a remote application service the authentication fails. So I suppose the token should be refreshed someway but I don't know how this could be done. Moreover, for what I know, I can pass the token to the spanwer only using the pre_spawn_start(self, user, spawner) method (/usr/local/lib/python3.6/dist-packages/oauthenticator/generic.py).
Could you give me any help on this?

Thank you again,

Cheers,
Michele

**Comment by michec81** [comment]
I think the problem arises as the pre_spanwer method is executed only once and the spawner_environment variable is not refreshed anymore.

  #added by CINECA
    @gen.coroutine
    def pre_spawn_start(self, user, spawner):
        auth_state = yield user.get_auth_state()
        if not auth_state:
             return 
        spawner.environment['OAUTH2_AUTHORIZE_TOKEN'] = auth_state['access_token']
        self.log.info("Passing access token variable to user spawn process %s", auth_state['access_token'])

**Comment by gweis** [comment]
The Access token is usually meant to be a short lived token. In general it has a validity time of a couple of minutes. 

Usually can use a refresh token to renew an access token, or you might be able to configure the access token validity time.

Also the environment variable inside your notebook container can't be refreshed by an outside process. Your only chance is to pass along a refresh token and have some sort of  process in your notebook server to regularly update the access token.

**Comment by michec81** [comment]
I know, but the point is that if I logout and login again, the pre_spawn_start is not called again and old token is still present in the environment variable.

Is it possible to access user.get_auth_state() directly from the notebook so I can be sure to use the current token, rather then previously set and stored in the environment?

is the same problem like this:
https://stackoverflow.com/questions/51287958/how-to-access-current-user-auth-state-from-notebook

Thank you again!

**Comment by michec81** [comment]
maybe a solution could be here:

https://github.com/jupyterhub/jupyterhub/issues/337 

but I still not understand what to do

**Comment by PaulMazzuca** [comment]
I agree with this issue. At the very least, storing the access token does not really make sense as it will most likely expire by the time it is used after persistence.  The better item to store would be the refresh token.   The question therefore becomes where should the logic of refreshing actually occur?  Of course, we could put the onus on the actual notebook user, but I feel like there could be a more elegant solution.  Maybe in the base authenticator class there could be a refresh function that is called if the refresh token is in the environment or the spawner?

**Comment by michec81** [comment]
we can find some hints in the globus.py module implementation:

**Comment by PaulMazzuca** [comment]
It looks like the globus authenticator does grab all the tokens, then uses the pre_spawn_start to put them all in a single environment variable.  Thinking about this more, given that OAuth tokens usually live around 30 minutes, even after refreshed, the actual refresh logic will probably have to be handled inside the spawned container itself.  This means that in order for a refresh to occur, either a script is strategically mounted and executed periodically inside the container, or the onus is placed on the user or package that the user might be using.

**Comment by PaulMazzuca** [comment]
After doing some research, in order to get the refresh token (at least for Google OAuth), in the oauth2.py, one would need to change line 89 to 
```python
extra_params={'state': state, 'access_type' : 'offline'}
```
If the access_type is offline using Google OAuth, a refresh token will be returned on the first login. This refresh token can then be passed to the environment using pre_spawn_start. 

Is there any issue with modifying the oauth2.py? or would it be better to make it similar to how to scope is passed through by doing self.authenticator.extra_params?

**Comment by gweis** [comment]
The ```GenericOAuthenticator``` has a configurable ```extra_params`` field https://github.com/jupyterhub/oauthenticator/blob/master/oauthenticator/generic.py#L52 . 
I guess adding a configurable trait extra_params to the base ```OAuthLoginHandler``` would solve this.

**Comment by betatim** [comment]
The way I solved this problem for https://notebooks.openhumans.org/hub/login is https://github.com/wildtreetech/ohjh/tree/master/images/refresher. Together with a small notebook server extension that is also in that repository.

You could probably build on this for your particular use case.

What it does is provide a small service that users talk to to obtain a valid token. The service itself fetches the token from JupyterHub's database and if the token has expired refreshes it before giving it to the user.

**Comment by PaulMazzuca** [comment]
@betatim I like your solution because, generally speaking, you would not want the refresh token to be available to the user given the sensitivity of the token.  Ideally that refresh token would stay on the hub.

**Comment by SolarisYan** [comment]
Hi @michec81, have you solved this?

**Comment by michec81** [comment]
no, unfortunately not. Thanks for your question :(

**Comment by kimsk** [comment]
Has anyone tried the solution provided by this https://github.com/jupyterhub/jupyterhub/issues/2676 and this PR, https://github.com/jupyterhub/oauthenticator/pull/287?

I tried to set `c.Auth0HubEnvAuthenticator.refresh_pre_spawn = True`, but I got the warning that Config option `refresh_pre_spawn` not recognized by `Auth0Authenticator`.

**Comment by SolarisYan** [comment]
@kimsk The solution need jupyterhub version 1.0.0

**Comment by lplancke** [comment]
Hi all,

Any update on this ?
Another solution would be to change the SelfAPIHandler so as to allow users to retreive their own access token (without being an admin, which gives you the right to see anyone's token):

class SelfAPIHandler(APIHandler):
	"""Return the authenticated user's model

	Based on the authentication info. Acts as a 'whoami' for auth tokens.
	"""

	async def get(self):
		user = self.get_current_user()
		
		if user is None:
			# whoami can be accessed via oauth token
			user = self.get_current_user_oauth_token()
		if user is None:
			raise web.HTTPError(403)
			
		model=self.user_model(user)
		model['auth_state'] = await user.get_auth_state()

		self.write(json.dumps(model))

This way, you can request the user API from your notebook and retrieve the last oauth token, independently from spawns:

    import requests 
    import os

    r=requests.get("http://127.0.0.1:8081/hub/api/user",
        headers={
           'Authorization': 'token %s' % os.environ["JPY_API_TOKEN"]
        })

    r.json()

Any thoughts ?

**Comment by michec81** [comment]
Thanks I will check as soon as possible!

**Comment by michec81** [comment]
it works, thanks a lot!!

**Comment by hardik42** [comment]
For some reason, I receive None for auth_state. Do I have to enable it somewhere?

**Comment by hardik42** [comment]
It worked! One needs to have auth_state enabled. 
https://github.com/jupyterhub/jupyterhub/blob/master/docs/source/reference/authenticators.md

**Comment by manics** [comment]
It sounds like this is solved!

**Comment by aparna2198** [comment]
@michec81 what was the solution. i am facing issue with my refresh token unable to get a new access token post expirty.

**Comment by hevara247** [comment]
@aparna2198 did you ever find a way around this?
