### ISSUE TITLE
Generic authentication responds with HTTP/500 on authorisation

### ISSUE THREAD

**Issue by xenatisch** [jupyterhub/oauthenticator#212]
## Problem 
Generic authentication fails following oAuth2 authorisation, and produces an uncontextualised and unhandled HTTP/500 error.

## Context
The hub and the authentication servers are run on separate Docker containers. They are both served through Nginx, which itself is housed on a a container that is independent of the two servers. 

The hub runs on a subdomain, and all proxies are handled by Nginx. 

The authorisation is handled through the [Django OAuth Toolkit](https://django-oauth-toolkit.readthedocs.io/en/latest/index.html).

The authentication server has been tested separately and is fully operational.

### Tools:
The following tools have been used:

- Python 3.6.6
- Jupyterhub 0.9.1
- oAuthenticator 0.8.0

- Docker 18.06.1-ce
- Docker machine 0.14.0
- Docker compose 1.21.2
- Docker compose yml file version 3.5

- Nginx 1.15.1

- Jupyerhub OS: Debian 9 

- OAuth2 server: Django OAuth Toolkit 1.2.0

## Details and logs

When attempting to authenticate using the Generic Authentication protocol, the authorisation is requested through a `GET` request from the hub server is sent to the authentication server as follows:
```
http://localhost/oauth2/authorize/?redirect_uri=http%3A%2F%2Flab.localhost%2Fhub%2Foauth_callback&client_id=[secret]&response_type=code&state=[secret]
```
Once the *Authorise* button is pressed, a `POST` request (from and to the authentication server) is sent, yielding an HTTP/302 response:

```
http://localhost/oauth2/authorize/?redirect_uri=http%3A%2F%2Flab.localhost%2Fhub%2Foauth_callback&client_id=[secret]&response_type=code&state=[secret]
```
This immediately triggers a redirection, sending a `GET` request to the hub server, as follows:

**Request:**
```
http://lab.localhost/hub/oauth_callback?code=[secret]&state=[secret]
```
**Request Header:**
```
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en-US;q=0.9,en;q=0.8
Cache-Control: max-age=0
Connection: keep-alive
Cookie: oauthenticator-state="[secret]:oauthenticator-state|120:[secret]|[secret]"
Host: lab.localhost
Referer: http://localhost/oauth2/authorize/?redirect_uri=http%3A%2F%2Flab.localhost%2Fhub%2Foauth_callback&client_id=[secret]&response_type=code&state=[secret]
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36 OPR/55.0.2994.37
```

**Response Headers:**
```
access-control-allow-headers: accept, content-type, authorization
Connection: keep-alive
Content-Length: 4473
content-security-policy: frame-ancestors 'self'; report-uri /hub/security/csp-report
Content-Type: text/html; charset=utf-8
Date: Thu, 30 Aug 2018 13:31:55 GMT
Server: nginx/1.15.1
set-cookie: oauthenticator-state=""; expires=Wed, 30 Aug 2017 13:31:55 GMT; Path=/
x-jupyterhub-version: 0.9.1
```

**Query parameters**:
```
code: [secret]
state: [secret]
```

which is responded to by an HTTP/500 (Internal Server Error). Upon additional investigation; it turns out that the actual error is:

> HTTP 599: Failed to connect to localhost port 80: Connection refused

Needless to say that, unless I am missing something, this cannot reasonably be the case given the fact that a connection was initially established to request authorisation in the first place. 

#### Hub server
```
[JupyterHub] [INFO] [302 GET /hub/oauth_login?next= -> http://localhost/oauth2/authorize/?redirect_uri=http%3A%2F%2Flab.localhost%2Fhub%2Foauth_callback&client_id=[secret]&response_type=code&state=[secret] (@XXX.XXX.XXX.XXX) 1.87ms]

[JupyterHub] [ERROR] [Uncaught exception GET /hub/oauth_callback?code=[secret]&state=[secret] (XXX.XXX.XXX.XXX)
    HTTPServerRequest(protocol='http', host='lab.localhost', method='GET', uri='/hub/oauth_callback?code=[secret]&state=[secret]', version='HTTP/1.1', remote_ip='XXX.XXX.XXX.XXX')]
    Traceback (most recent call last):
      File "[...]/tornado/web.py", line 1543, in _execute
        result = yield result
      File "[...]/oauthenticator/oauth2.py", line 182, in get
        user = yield self.login_user()
      File "[...]/jupyterhub/handlers/base.py", line 473, in login_user
        authenticated = await self.authenticate(data)
      File "[...]/jupyterhub/auth.py", line 257, in get_authenticated_user
        authenticated = await maybe_future(self.authenticate(handler, data))
      File "[...]/oauthenticator/generic.py", line 116, in authenticate
        resp = yield http_client.fetch(req)
    tornado.curl_httpclient.CurlError: HTTP 599: Failed to connect to localhost port 80: Connection refused

[JupyterHub] [DEBUG] [No template for 500]

[JupyterHub] [ERROR] [{
      "X-Forwarded-Host": "lab.localhost",
      "X-Forwarded-Proto": "http",
      "X-Forwarded-Port": "80",
      "Cookie": "oauthenticator-state=[secret]:oauthenticator-state|120:[secret]"",
      "Accept-Language": "en-GB,en-US;q=0.9,en;q=0.8",
      "Accept-Encoding": "gzip, deflate, br",
      "Referer": "http://localhost/oauth2/authorize/?redirect_uri=http%3A%2F%2Flab.localhost%2Fhub%2Foauth_callback&client_id=[secret]&response_type=code&state=[secret]",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36 OPR/55.0.2994.37",
      "Upgrade-Insecure-Requests": "1",
      "Cache-Control": "max-age=0",
      "Connection": "close",
      "X-Nginx-Proxy": "true",
      "X-Forwarded-For": "XXX.XXX.XXX.XXX,::XXXX:XXXX.XXXX.XXX.XXX",
      "X-Real-Ip": "XXX.XXX.XXX.XXX.1",
      "Host": "lab.localhost"
    }]

[JupyterHub] [ERROR] [500 GET /hub/oauth_callback?code=[secret]&state=[secret] (@XXX.XXX.XXX.XXX) 9.14ms]
```
#### Access logs

Nginx access logs for the authentication server and the hub are as follows:

##### Authentication server:
```
XXX.XXX.XXX.XXX.1 | - [30/Aug/2018:13:04:48 +0000] <GET /oauth2/authorize/?redirect_uri=http%3A%2F%2Flab.localhost%2Fhub%2Foauth_callback&client_id=[secret]&response_type=code&state=[secret] HTTP/1.1> : 200 || 953 || Referer: http://lab.localhost/hub/login | Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36 OPR/55.0.2994.37 | rt=0.041 | uct=0.000 | uht=0.044 | urt=0.044 

XXX.XXX.XXX.XXX.1 | - [30/Aug/2018:13:04:49 +0000] <POST /oauth2/authorize/?redirect_uri=http%3A%2F%2Flab.localhost%2Fhub%2Foauth_callback&client_id=[secret]&response_type=code&state=[secret] HTTP/1.1> : 302 || 0 || Referer: http://localhost/oauth2/authorize/?redirect_uri=http%3A%2F%2Flab.localhost%2Fhub%2Foauth_callback&client_id=[secret]&response_type=code&state=[secret] | Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36 OPR/55.0.2994.37 | rt=0.030 | uct=0.000 | uht=0.028 | urt=0.028 
```

##### Hub server (on a subdomain proxy):
```
XXX.XXX.XXX.XXX.1 | - [30/Aug/2018:13:04:48 +0000] <GET /hub/oauth_login?next= HTTP/1.1> : 302 || 0 || Referer: http://lab.localhost/hub/login | Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36 OPR/55.0.2994.37 | rt=0.003 | uct=0.000 | uht=0.004 | urt=0.004

XXX.XXX.XXX.XXX.1 | - [30/Aug/2018:13:04:49 +0000] <GET /hub/oauth_callback?code=[secret]&state=[secret] HTTP/1.1> : 500 || 4473 || Referer: http://localhost/oauth2/authorize/?redirect_uri=http%3A%2F%2Flab.localhost%2Fhub%2Foauth_callback&client_id=[secret]&response_type=code&state=[secret] | Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36 OPR/55.0.2994.37 | rt=0.004 | uct=0.000 | uht=0.004 | urt=0.004
```

### Jupyerhub
Settings as define in `jupyterhub_config.py`:

```
c.JupyterHub.authenticator_class = 'oauthenticator.generic.GenericOAuthenticator'

c.OAuthenticator.client_id = '[secret]'
c.OAuthenticator.client_secret = '[secret]'

c.GenericOAuthenticator.oauth_callback_url = 'http://lab.localhost/hub/oauth_callback'
c.GenericOAuthenticator.token_url = 'http://localhost/oauth2/token/'
c.GenericOAuthenticator.userdata_url = 'http://localhost/api/users/username'
c.GenericOAuthenticator.userdata_method = 'GET'
c.GenericOAuthenticator.userdata_params = {"state": "state"}
c.GenericOAuthenticator.username_key = "username"
```
and the environment variables:
```
OAUTH2_AUTHORIZE_URL=http://localhost/oauth2/authorize/
OAUTH2_TOKEN_URL=http://localhost/oauth2/token/

DOCKER_NETWORK_NAME=labhub
DOCKER_NOTEBOOK_IMAGE=jupyter/scipy-notebook:8f56e3c47fec

DOCKER_NOTEBOOK_DIR=/home/jovyan/work

DATA_VOLUME_HOST=lab-data

DATA_VOLUME_CONTAINER=/data

OAUTH2_TLS_VERIFY=False
```
Note that HTTPS protocols are handled by Nginx, and as such, they are left unset in `jupyerhub_config.py`.  

### Nginx

Settings for the hub:

```
server {

    listen 80;
    server_name lab.localhost;
    keepalive_timeout 65s;
    resolver_timeout 5s;
    
    charset utf-8;

    access_log /var/log/nginx/access-lab.log main;

    location / {

        proxy_pass http://lab/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-NginX-Proxy true;

    }

    location ~* /(user/[^/]*)/(api/kernels/[^/]+/channels|terminals/websocket)/? {

        proxy_pass http://lab;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_set_header X-NginX-Proxy true;

        # WebSocket support
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 86400;

    }

}
```

**Comment by gweis** [comment]
Are you sure, that JupyterHub can connect to your OAuth server via localhost? From a JupyterHub's container point of view, localhost is the container JupyterHub is running in.

JupyterHub needs to contact the OAuth server directly to verify the code response and fetch an access token.

**Comment by xenatisch** [comment]
@gweis Absolutely. How else would I be sending an authorisation request over to the authentication server?

Note that the auth server is on `localhost`, whilst Jupyterhub is on `lab.localhost`, both accessible via port 80. 

How it works now is that I connect to `lab.localhost` and access the hub, then press the button for **Sign in with Generic OAuth2** [request 1 / GET], which redirect me onto the authentication server to gain authorisation, once I press authorise [request 2 / POST], I am then redirected to the hub's callback URI with an authorisation code [request 3 / GET], and that's where the HTTP/500 error occurs. 

As you can see in the access logs, the request is resolved, it's just not processed correctly (hence HTTP/500).

**Comment by gweis** [comment]
That's exactly what I am talking about...

```
[JupyterHub] [ERROR] [Uncaught exception GET /hub/oauth_callback?code=[secret]&state=[secret] (XXX.XXX.XXX.XXX)
    HTTPServerRequest(protocol='http', host='lab.localhost', method='GET', uri='/hub/oauth_callback?code=[secret]&state=[secret]', version='HTTP/1.1', remote_ip='XXX.XXX.XXX.XXX')]
    Traceback (most recent call last):
      File "[...]/tornado/web.py", line 1543, in _execute
        result = yield result
      File "[...]/oauthenticator/oauth2.py", line 182, in get
        user = yield self.login_user()
      File "[...]/jupyterhub/handlers/base.py", line 473, in login_user
        authenticated = await self.authenticate(data)
      File "[...]/jupyterhub/auth.py", line 257, in get_authenticated_user
        authenticated = await maybe_future(self.authenticate(handler, data))
      File "[...]/oauthenticator/generic.py", line 116, in authenticate
        resp = yield http_client.fetch(req)
    tornado.curl_httpclient.CurlError: HTTP 599: Failed to connect to localhost port 80: Connection refused
```

See this error, Jupyterhub receives the code from the browser, and then Jupyterhub (the server) tries to connect to localhost:80 to exchange the code for a token..

unless the auth server is running inside the jupyterhub container or some other networking is setup so that traffic from inside the jupyterhub container to localhost:80 get's routed to your auth server, this can't work.

**Comment by xenatisch** [comment]
@gweis I did notice that too, though I kind of discounted it as some internal mistake in generating the error message. Simply because every other request is being handled correctly, until it comes to this.

The thing is, the request header shows that the host corresponds to `lab.localhost`, as much is even shown here:

    HTTPServerRequest(protocol='http', host='lab.localhost', method='GET', uri='/hub/oauth_callback?code=[secret]&state=[secret]', version='HTTP/1.1', remote_ip='XXX.XXX.XXX.XXX')]

So unless there is a redirect somewhere, or for some bizarre reason, the subdomain is being ignored, I cannot for the life of me figure out why this is happening.

Is there a setting to specify the subdomain URL somewhere hidden in Jupyterhub? Or should I explicitly define the proxy for it, even though it is handled externally?

**Comment by gweis** [comment]
All the other requests are working because they originate from your browser. The one that fails is when jupyterhub (the server) tries to exchange the code for a token with the OAuth server. This does not involve your browser at all.

**Comment by xenatisch** [comment]
@gweis Thanks again for the comments. I see your point. However, the hub server never gets past the authorisation for it to start dealing with the token and user data. You see, this error occurs when the hub server tries to resolve the callback by the authentication server, not when requesting the token. The `GET` request is that which follows the authorisation in the auth server. That's what makes this quite bizarre. 

The OAuth server does indeed have a robust URL and request verification system in place, that's correct. However, they are all configured properly, and are working as expected. As I mentioned in the original post, the OAuth server has been tested independently, using a different external client. 

Anyhow, I will look into the oauthenticator / Jupytetrhub source codes to see if I can work anything out. In the mean time though, any suggestions would be greatly appreciated. Will post here once I make any progress.

**Comment by gweis** [comment]
I'll try it again:

Your hub server receives the call-back with the token exchange code:

```
[JupyterHub] [ERROR] [Uncaught exception GET /hub/oauth_callback?code=[secret]&state=[secret] (XXX.XXX.XXX.XXX)
    HTTPServerRequest(protocol='http', host='lab.localhost', method='GET', uri='/hub/oauth_callback?code=[secret]&state=[secret]', version='HTTP/1.1', remote_ip='XXX.XXX.XXX.XXX')]
    Traceback (most recent call last):
      File "[...]/tornado/web.py", line 1543, in _execute
        result = yield result
      File "[...]/oauthenticator/oauth2.py", line 182, in get
        user = yield self.login_user()
      File "[...]/jupyterhub/handlers/base.py", line 473, in login_user
        authenticated = await self.authenticate(data)
      File "[...]/jupyterhub/auth.py", line 257, in get_authenticated_user
        authenticated = await maybe_future(self.authenticate(handler, data))
      File "[...]/oauthenticator/generic.py", line 116, in authenticate
        resp = yield http_client.fetch(req)
    tornado.curl_httpclient.CurlError: HTTP 599: Failed to connect to localhost port 80: Connection refused
```

This request is accepted and processed. Now Let's check that line of code where the exception is thrown:
https://github.com/jupyterhub/oauthenticator/blob/master/oauthenticator/generic.py#L116

It uses ```url``` and ```params``` to make that request. From the lines above you can see, that ```url``` is the OAuth server token url and ```params``` containers the token exchange code. To me this looks very much like the server tries to exchange the code for a token. It fails because there is no OAtuh server on localhost:80 (form hub server container / network namespace), and throws an exception, which means you oauth_callback request fails.

Your browser (probably on the same host) may know  where localhost:80 is, but your hub server run in a container with a different network namespace (it's almost a different machine). Your container has it's own localhost which is different to what your browser sees as localhost.

**Comment by xenatisch** [comment]
@gweis I tried and successfully carried out the authorisation and token exchange process programmatically from the hub server, using credentials identical to what I use for Jupyterhub (except for the callback URL, which I had to change). The process is internal, and independent of the browser. It works perfectly fine. So yea, there is an OAuth server on `localhost:80`, and it is accessible from the hub server. 

I didn't test the `userdata_url` though. I'll look into it.

**Comment by gweis** [comment]
That does not quite fit your original problem description:

> The hub and the authentication servers are run on separate Docker containers. They are both served through Nginx, which itself is housed on a a container that is independent of the two servers.

With that every container gets it's own localhost, unless you do some special network namespace set up or use kubernetes, where all the containers are put together into one pod (which is essentially the same as putting all containers into the same network namespace)

**Comment by xenatisch** [comment]
@gweis Thanks again. I solved the problem, and have had this page open for nearly a week now so that I won't forget to post the solution.

Turns out that, as far as container communications are concerned, and in line with what you describe in your messages, the problem originated in that some requests were being handled in the frontend (i.e. through the browser), and some in the backend. 

On that note, and in a scenario where both the OAuth2 server, and the hub are in the same host (separate containers), `OAUTH2_AUTHORIZE_URL` must be set to a URL that is accessible through the browser and points to the OAuth2 server. In other words, it has to be pointing towards a URL, or a host IP, not a machine proxy that is handled within the container. 

`OAUTH2_TOKEN_URL` on the other hand must be a the name of the container (i.e. the proxy) that points to the OAuth2 server. The same applies to `OAUTH_CALLBACK_URL` and the `USERDATA_URL`. 

Hope this helps someone. With thanks to @gweis , I'm now closing this issue.

**Comment by shalinisssingh** [comment]
Hi @xenatisch i'm stuck with this problem and need possible solution. Could you please elaborate where you made change

**Comment by stephen-a2z** [comment]
I meet the same problem:
```
[E 2020-04-20 16:33:32.747 JupyterHub web:1670] Uncaught exception GET /hub/oauth_callback?code=3823a7540aa344c6975&state=eyJzdGF0ZV9pZCI6ICI0NzY1MTk3Y2NiYWI0NDg1YTcxOGIxZjYxNzBYWExMSIsICJuZXh0X3VybCI6ICIifQ%3D%3D (::ffff:98.234.180.188)
    HTTPServerRequest(protocol='https', host='jupyter.liaoyu.online', method='GET', uri='/hub/oauth_callback?code=3823a7540aa344dc6975&state=eyJzdGF0ZV9pZCI6ICI0NzY1MTk3Y2NiYWI0NDg1YTcxOGIxZjYxNzBlYWExMSIsICJuZXh0X3VybCI6ICIifQ%3D%3D', version='HTTP/1.1', remote_ip='::ffff:98.234.180.188')
    Traceback (most recent call last):
      File "/root/anaconda3/lib/python3.6/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/root/anaconda3/lib/python3.6/site-packages/oauthenticator/oauth2.py", line 213, in get
        user = await self.login_user()
      File "/root/anaconda3/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 699, in login_user
        authenticated = await self.authenticate(data)
      File "/root/anaconda3/lib/python3.6/site-packages/jupyterhub/auth.py", line 383, in get_authenticated_user
        authenticated = await maybe_future(self.authenticate(handler, data))
      File "/root/anaconda3/lib/python3.6/site-packages/oauthenticator/github.py", line 160, in authenticate
        resp = await http_client.fetch(req)
    tornado.curl_httpclient.CurlError: HTTP 599: Failed to connect to api.github.com port 443: Connection refused

[E 2020-04-20 16:33:32.756 JupyterHub log:166] {
      "X-Forwarded-Host": "jupyter.liaoyu.online",
      "X-Forwarded-Proto": "https",
      "X-Forwarded-Port": "443",
      "X-Forwarded-For": "::ffff:98.234.180.188",
      "Cookie": "_xsrf=[secret]; username-jupyter-liaoyu-online=[secret]; jupyterhub-session-id=[secret]; oauthenticator-state=[secret]",
      "Accept-Language": "en,zh-CN;q=0.9,zh;q=0.8",
      "Accept-Encoding": "gzip, deflate, br",
      "Referer": "https://jupyter.liaoyu.online/hub/login",
      "Sec-Fetch-User": "?1",
      "Sec-Fetch-Mode": "navigate",
      "Sec-Fetch-Site": "cross-site",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
      "Sec-Fetch-Dest": "document",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36",
      "Upgrade-Insecure-Requests": "1",
      "Connection": "close",
      "Host": "jupyter.liaoyu.online"
    }
[E 2020-04-20 16:33:32.756 JupyterHub log:174] 500 GET /hub/oauth_callback?code=[secret]&state=[secret] (@::ffff:98.234.180.188) 1486.02ms
```

**Comment by oneilk** [comment]
@xenatisch / @shalinisssingh / @stephen-a2z Have any of you been able to resolve this issue? I am having a very, very similar issue. I am going to play around with those environment variables that @xenatisch mentioned.

**Comment by DMoreira97** [comment]
Hello. I think I was able to understand very lightly the explanation given by @xenatisch .

With the configuration shown in the image below, `OAUTH2_AUTHORIZE_URL` gets a url accessible from the browser, and `OAUTH2_TOKEN_URL ` plus `USERDATA_URL` get an url with the container "name" (ip). However, it doesn't make much sense to do the same to `OAUTH_CALLBACK_URL` in my configuration, once after the login, the user will be redirected to this url, so this one also needs to be an url accessible from the browser (and I've already tried the other way around, which results in an inaccessible url).

![image](https://user-images.githubusercontent.com/27859403/136167968-7c55c146-4f3a-4e0f-8484-7ba15eba356b.png)

After having applied this, I noticed that the hub logs changed, so that is probably good news once this might have fixed the first problem.

For the second problem, here are the logs from the hub:

`
[I 2021-10-06 08:27:40.792 JupyterHub log:189] 200 GET /hub/login?next=%2Fhub%2F (@::ffff:127.0.0.1) 26.85ms
[I 2021-10-06 08:27:53.001 JupyterHub oauth2:111] OAuth redirect: 'http://localhost:8081/hub/oauth_callback'
[I 2021-10-06 08:27:53.004 JupyterHub log:189] 302 GET /hub/oauth_login?next=%2Fhub%2F -> http://localhost:8080/auth/realms/realm-jupyterhub/protocol/openid-connect/auth?response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A8081%2Fhub%2Foauth_callback&client_id=my-client-id&state=[secret] (@::ffff:127.0.0.1) 2.91ms
[E 2021-10-06 08:27:53.090 JupyterHub oauth2:389] Error fetching user data 401 GET http://10.98.133.100:80/auth/realms/realm-jupyterhub/protocol/openid-connect/userinfo: {
     "error": "invalid_token",
     "error_description": "Token verification failed"
    }
[E 2021-10-06 08:27:53.090 JupyterHub web:1789] Uncaught exception GET /hub/oauth_callback?state=eyJzdGF0ZV9pZCI6ICI5MjQ4ZDk3MGFmZDI0NTA0YTAzMTVjNDAwYzFlYTJlZSIsICJuZXh0X3VybCI6ICIvaHViLyJ9&session_state=6558b7a0-b42b-4205-a1e6-6b23db2be03a&code=dab45396-261a-4611-9fa0-987f9b74f964.6558b7a0-b42b-4205-a1e6-6b23db2be03a.2c75d5b0-0717-48b4-9dcd-4d9ad18a46cb (::ffff:127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8081', method='GET', uri='/hub/oauth_callback?state=eyJzdGF0ZV9pZCI6ICI5MjQ4ZDk3MGFmZDI0NTA0YTAzMTVjNDAwYzFlYTJlZSIsICJuZXh0X3VybCI6ICIvaHViLyJ9&session_state=6558b7a0-b42b-4205-a1e6-6b23db2be03a&code=dab45396-261a-4611-9fa0-987f9b74f964.6558b7a0-b42b-4205-a1e6-6b23db2be03a.2c75d5b0-0717-48b4-9dcd-4d9ad18a46cb', version='HTTP/1.1', remote_ip='::ffff:127.0.0.1')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/dist-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/usr/local/lib/python3.8/dist-packages/oauthenticator/oauth2.py", line 231, in get
        user = await self.login_user()
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/handlers/base.py", line 754, in login_user
        authenticated = await self.authenticate(data)
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/auth.py", line 469, in get_authenticated_user
        authenticated = await maybe_future(self.authenticate(handler, data))
      File "/usr/local/lib/python3.8/dist-packages/oauthenticator/generic.py", line 171, in authenticate
        user_data_resp_json = await self._get_user_data(token_resp_json)
      File "/usr/local/lib/python3.8/dist-packages/oauthenticator/oauth2.py", line 390, in fetch
        raise e
      File "/usr/local/lib/python3.8/dist-packages/oauthenticator/oauth2.py", line 369, in fetch
        resp = await self.http_client.fetch(req, **kwargs)
    tornado.httpclient.HTTPClientError: HTTP 401: Unauthorized

[E 2021-10-06 08:27:53.144 JupyterHub log:181] {
      "X-Forwarded-Host": "localhost:8081",
      "X-Forwarded-Proto": "http",
      "X-Forwarded-Port": "8081",
      "X-Forwarded-For": "::ffff:127.0.0.1",
      "Cookie": "username-localhost-8888=[secret]; _xsrf=[secret]; oauthenticator-state=[secret]",
      "Accept-Language": "en-GB,en;q=0.9,en-US;q=0.8,pt;q=0.7,es;q=0.6",
      "Accept-Encoding": "gzip, deflate, br",
      "Sec-Ch-Ua-Platform": "\"Windows\"",
      "Sec-Ch-Ua-Mobile": "?0",
      "Sec-Ch-Ua": "\"Chromium\";v=\"94\", \"Google Chrome\";v=\"94\", \";Not A Brand\";v=\"99\"",
      "Sec-Fetch-Dest": "document",
      "Sec-Fetch-User": "?1",
      "Sec-Fetch-Mode": "navigate",
      "Sec-Fetch-Site": "same-site",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36",
      "Upgrade-Insecure-Requests": "1",
      "Connection": "close",
      "Host": "localhost:8081"
    }
[E 2021-10-06 08:27:53.144 JupyterHub log:189] 500 GET /hub/oauth_callback?state=[secret]&session_state=[secret]&code=[secret] (@::ffff:127.0.0.1) 110.63ms
`

**Comment by jckoester** [comment]
I'm experiencing very similar problems, except I get a slightly different error:
```
[I 2021-10-19 18:23:10.531 JupyterHub oauth2:111] OAuth redirect: 'https://jupyter.gymnasium-ditzingen.de/hub/oauth_callback'
[D 2021-10-19 18:23:10.532 JupyterHub base:526] Setting cookie oauthenticator-state: {'httponly': True, 'expires_days': 1}
[I 2021-10-19 18:23:10.533 JupyterHub log:189] 302 GET /hub/oauth_login?next=%2Fhub%2F -> https://gymnasium-ditzingen.de/iserv/oauth/v2/auth?response_type=code&redirect_uri=https%3A%2F%2Fjupyter.gymnasium-ditzingen.de%2Fhub%2Foauth_callback&client_id=37_2h4lu2ctowcgo4k4ossksg8wskw84w0so4000g0wggswcc044c&state=[secret]&scope=openid+profile+email (@85.212.249.56) 2.10ms
[E 2021-10-19 18:23:10.948 JupyterHub oauth2:389] Error fetching user data 401 GET https://gymnasium-ditzingen.de/iserv/public/oauth/userinfo: {
     "error": "access_denied",
     "error_description": "OAuth2 authentication required"
    }
[E 2021-10-19 18:23:10.949 JupyterHub web:1789] Uncaught exception GET /hub/oauth_callback?state=eyJzdGF0ZV9pZCI6ICIyNTY2OTgxNTExMTE0ZGVkYWZmM2IzM2NmYzg2ZmVhNiIsICJuZXh0X3VybCI6ICIvaHViLyJ9&code=MmRkMWQwNWJjYmYyOWQyZjU5ZDkwZjc2NjZjYWYwMjZiOTg1YzU1NDZjZWRkZWU2OThmMTUwYjU4M2MwYjRkMw (85.212.249.56)
    HTTPServerRequest(protocol='http', host='jupyter.gymnasium-ditzingen.de', method='GET', uri='/hub/oauth_callback?state=eyJzdGF0ZV9pZCI6ICIyNTY2OTgxNTExMTE0ZGVkYWZmM2IzM2NmYzg2ZmVhNiIsICJuZXh0X3VybCI6ICIvaHViLyJ9&code=MmRkMWQwNWJjYmYyOWQyZjU5ZDkwZjc2NjZjYWYwMjZiOTg1YzU1NDZjZWRkZWU2OThmMTUwYjU4M2MwYjRkMw', version='HTTP/1.1', remote_ip='85.212.249.56')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/dist-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/usr/local/lib/python3.8/dist-packages/oauthenticator/oauth2.py", line 231, in get
        user = await self.login_user()
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/handlers/base.py", line 754, in login_user
        authenticated = await self.authenticate(data)
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/auth.py", line 469, in get_authenticated_user
        authenticated = await maybe_future(self.authenticate(handler, data))
      File "/usr/local/lib/python3.8/dist-packages/oauthenticator/generic.py", line 171, in authenticate
        user_data_resp_json = await self._get_user_data(token_resp_json)
      File "/usr/local/lib/python3.8/dist-packages/oauthenticator/oauth2.py", line 390, in fetch
        raise e
      File "/usr/local/lib/python3.8/dist-packages/oauthenticator/oauth2.py", line 369, in fetch
        resp = await self.http_client.fetch(req, **kwargs)
    tornado.httpclient.HTTPClientError: HTTP 401: Unauthorized
[D 2021-10-19 18:23:10.952 JupyterHub base:1285] No template for 500
```
It somehow looks like the initial authentication was successful but doesn't get used when retrieving the userdata.

**Comment by maltegrosse** [comment]
finally figured out, this only happens on non master realms as the "openid" client scope is not available.
so simple follow this:
https://keycloak.discourse.group/t/issue-on-userinfo-endpoint-at-keycloak-20/18461/7
1. Add client Scope "openid"
2. Add to Clients -> your jupyterhub client->client scopes --> add openid
