### ISSUE TITLE
Do not use Azure AD display name as username

### ISSUE THREAD

**Issue by thomas-rabiller-azimut** [jupyterhub/oauthenticator#213]
While using the AzureAdOAuthenticator to authenticate with Oauth to the Azure AD provider, the property "name" from the requested JWT token is used as username in JupyterHub. According to the [Azure AD documentation](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-id-and-access-tokens):

> The name claim provides a human-readable value that identifies the subject of the token. The value is not guaranteed to be unique, it is mutable, and it's designed to be used only for display purposes

It is therefore not reliable as a username (not unique, can contain spaces and special chars...)

I suggest using the object id instead, which is exactly the common unix username max size (32 chars long after removing the dashes in guid)

This is what I am doing currently in a project by overriding the behaviour in a inherited class, but it should probably be applied in future versions by default.

**Comment by vwoloszyn** [comment]
I open an issue regarding this behavior of using the AD display name as username. In short, jupyterhub is not allowing to autheticate users because the display name contain an illegal char "/"
https://github.com/jupyterhub/jupyterhub/issues/3996
