### ISSUE TITLE
Google Authenticator does not use client id from config only env

### ISSUE THREAD

**Issue by coderforlife** [jupyterhub/oauthenticator#215]
Putting the setting `c.GoogleOAuthAuthenticator.client_id = '...'` in the JupyterHub config file results in a redirect to https://accounts.google.com/o/oauth2/v2/auth?redirect_uri=https%3A%2F%2Fexample.com%3A8000%2Fhub%2Foauth_callback&client_id=&response_type=code&state=[secret]&scope=openid+email when logging in. Notice that the `client_id` is empty. Google properly says something went wrong and that no client ID is provided.

However, if the environmental variable is used instead like

`OAUTH_CLIENT_ID=...` jupyterhub

Then it works just fine. All other settings are still in config file.

**Comment by coderforlife** [comment]
Further testing shows that this seems to apply to the `c.GoogleOAuthAuthenticator.client_secret` setting as well, ultimately requiring `OAUTH_CLIENT_SECRET` environmental variable. Testing took further since this error shows up after signing in.

**Comment by coderforlife** [comment]
Possibly. I have been poking around the code but I am quite unfamiliar with lots of the architecture being used. I have tried using `traitlets.observe` for lots of different configs but it is never being triggered (I have tried with `client_id`, `client_secret`, `oauth_callback_url`, Google's `login_service`, and Google's `hosted_domain`). I simply had them print out what was going on but nothing showed up. However I can print out in the `_client_id_default` function and see that being called.

I have also tried using the 'global' observing (https://traitlets.readthedocs.io/en/stable/api.html#traitlets.HasTraits.observe) from the `__init__` method of `GoogleOAuthenticator` and still no messages show up. It seems as though the traitlet configs are not getting seen at all... but there is no complaints when loading up the config file.

I don't what else to try to track this down. Any suggestions?

**Comment by betatim** [comment]
From a quick read of the code I also think it should work. Have you tried what happens if you disable the default value setter (https://github.com/jupyterhub/oauthenticator/blob/8277ae61f471fac5c054b1e7980da00c84ed3c4e/oauthenticator/oauth2.py#L216)?

It is a bit weird because this mechanism is used as part of the zero2jupyterhub material which I am using to configure Google OAuth which just works.

**Comment by coderforlife** [comment]
I was using `observe` to be able to debug the issue, not as a solution. I wanted to know what config settings were being set and when, but no luck...

If the default value setter is suppressed than an empty string is passed as the client id.

I am confused as well as it does seem that it should be working. Why do it only affect `client_id` and `client_secret` but not `oauth_callback_url`? (only the first two have default handlers, but suppressing those does not help...)

**Comment by coderforlife** [comment]
Doing some additional sleuthing I see that `self.config` (where `self` is a `GoogleOAuthenticator`) is being set during the constructor to a `traitlets.config.loader.Config` object that contains all of the configuration settings and correctly! When printed the object displays as a dictionary:

`{'JupyterHub': {'config_file': 'jupyterhub_config.py', 'log_level': 10, 'authenticator_class': <class 'oauthenticator.google.GoogleOAuthenticator'>, 'cookie_secret_file': 'jupyterhub_cookie_secret', 'data_files_path': '...', 'db_url': '...', 'ssl_cert': '...', 'ssl_key': '...'}, 'GoogleOAuthAuthenticator': {'oauth_callback_url': '...', 'client_id': '...', 'client_secret': '...', 'hosted_domain': '...', 'login_service': '..'}, 'Authenticator': {'admin_users': {'...'}}}`

If I try to access `self.config.GoogleOAuthAuthenticator.client_id` I get a the desired value - so it is there!

It seems as though the config settings are not being applied properly. This may be due to an issue with my version of traitlets or something like that in that it isn't interpreting `GoogleOAuthAuthenticator` as the proper target of these setting...

**Comment by coderforlife** [comment]
Okay, so this turned out to be an issue of mine and mine alone. I misspelled `GoogleOAuthenticator`... I think I need to submit a feature request to `traitlets` for a warning in debug mode that mentions un-used values or bad names of things...
