### ISSUE TITLE
LocalGenericOAuthenticator: How do I turn ON debug logging for tornado ?

### ISSUE THREAD

**Issue by jiyer2016** [jupyterhub/oauthenticator#216]
I am integrating jupyterhub with a client's OAuth2 Service provider using the LocalGenericOAuthenticator

This is how my configuration looks like in jupyterhub_config.py:

```
from oauthenticator.generic import LocalGenericOAuthenticator
c.JupyterHub.authenticator_class = LocalGenericOAuthenticator

c.LocalGenericOAuthenticator.oauth_callback_url = '***'
c.LocalGenericOAuthenticator.client_id = '***'
c.LocalGenericOAuthenticator.client_secret = '***'
c.LocalGenericOAuthenticator.login_service = 'GenericOAuth2'
c.LocalGenericOAuthenticator.userdata_url = '***'
c.LocalGenericOAuthenticator.token_url = '***'
c.LocalGenericOAuthenticator.userdata_method = 'GET'
c.LocalGenericOAuthenticator.create_system_users = True
c.Authenticator.whitelist = {'***'}
c.Authenticator.admin_users = {'***'}
```

Here is the error I get - happens in the OAUTH_CALLBACK flow - where I get a HTTP 403: Forbidden:
```
[E 2018-09-21 13:44:38.983 JupyterHub web:1621] Uncaught exception GET /hub/oauth_callback?code=***&state=*** (::ffff:***)
    HTTPServerRequest(protocol='http', host='***', method='GET', uri='/hub/oauth_callback?code=***&state=***', version='HTTP/1.1', remote_ip='::ffff:***')
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/tornado/web.py", line 1543, in _execute
        result = yield result
      File "/opt/conda/lib/python3.6/site-packages/oauthenticator/oauth2.py", line 182, in get
        user = yield self.login_user()
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 473, in login_user
        authenticated = await self.authenticate(data)
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/auth.py", line 257, in get_authenticated_user
        authenticated = await maybe_future(self.authenticate(handler, data))
      File "/opt/conda/lib/python3.6/site-packages/oauthenticator/generic.py", line 141, in authenticate
        resp = yield http_client.fetch(req)
    tornado.httpclient.HTTPError: HTTP 403: Forbidden
```

It seems to be failing at the point when the callback is submitting a GET request to the userdata_url endpoint of the OAUTH2 Service provider.

The Client is asking me to validate the GET request submitted from JupyterHub. The HTTP request submitted from tornado http client doesn't appear on the stdout by default.

First, I turned ON debug on jupyter as a whole - but couldn't find information any interesting information on the HTTP GET request.

I then added this snippet inside the "jupyterhub_config.py" - but that made no difference either.

```
import logging

logger = logging.getLogger('tornado.access')
logger.setLevel(logging.DEBUG)

logger = logging.getLogger('tornado.application')
logger.setLevel(logging.DEBUG)

logger = logging.getLogger('tornado.general')
logger.setLevel(logging.DEBUG)
```
So my question is - How do I turn ON debug logging for tornado running inside jupyterhub in order to debug this issue further ?

Note: I have replaced all information that may be considered sensitive with "***" in the above code / log snippets

**Comment by minrk** [comment]
To enable debug logging:

start jupyterhub with `--debug`, or add:

```python
c.JupyterHub.log_level = logging.DEBUG
```

**Comment by jiyer2016** [comment]
Thanks, I tried this - but it does NOT appear to produce debugging information related to actual requests/response messages on the tornado library.
