### ISSUE TITLE
Default value for token_type

### ISSUE THREAD

**Issue by nifuki** [jupyterhub/oauthenticator#225]
Hi,

My provider doesn't return the type of the access token, so I have to hardcode it here: https://github.com/jupyterhub/oauthenticator/blob/3a1e663555ba84050f7b0cc5940c723bb739699c/oauthenticator/generic.py#L122

I think it would be useful to add an option to set its type or to just add the default value ("Bearer" as the most commonly used), like so:

`token_type = resp_json.get('token_type', 'Bearer')`

Thanks.

**Comment by nifuki** [comment]
Or at least to log an error message if it is not set, since it is a required setting as defined by the [standard](https://tools.ietf.org/html/draft-ietf-oauth-token-exchange-16#section-2.2.1).

**Comment by manics** [comment]
I'm closing this as it's quite old and it's the provider at fault. Please feel free to open a PR to improve the error message though.
