### ISSUE TITLE
Wrong link of CILogon Sign in button 

### ISSUE THREAD

**Issue by mxcheng2011** [jupyterhub/oauthenticator#228]
The button "Sign in with CIlogon" is linked to https://hostname/hub/login rather than the correct https://hostname/hub/oauth_login.

**Comment by mxcheng2011** [comment]
<img width="1438" alt="screen shot 2018-11-27 at 5 49 45 pm" src="https://user-images.githubusercontent.com/38145385/49119368-ae094400-f26d-11e8-9e71-20b15ebf9d03.png">

**Comment by mxcheng2011** [comment]
<img width="920" alt="screen shot 2018-11-27 at 5 58 26 pm" src="https://user-images.githubusercontent.com/38145385/49119475-148e6200-f26e-11e8-9636-b6c774763d6b.png">

**Comment by mxcheng2011** [comment]
It turns out we have to set `c.JupyterHub.template_paths = ['/srv/jupyterhub/anaconda3/share/jupyter/hub/templates']` in configuration. Do you know how to print out default template_paths parameter?

**Comment by minrk** [comment]
You shouldn't need to set template_paths unless you are using a non-default template location. The default path is {sys.prefix}/share/jupyterhub/templates (jupyterhub, not jupyter/hub).

What version of oauthenticator and jupyterhub are you using? The login should be hitting a URL that redirects automatically to the login service.

**Comment by mxcheng2011** [comment]
Min, it is the verion oauthenticator (0.8.0). The jupyterhub is installed by Anaconda3 which has only {sys.prefix}/share/jupyter/hub not {sys.prefix}/share/jupyterhub/. Anyway, I will close this ticket. Thank you for the reply.
