### ISSUE TITLE
Do a release on pypi

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/oauthenticator#23]
So people can easily install this via pip!

**Comment by willingc** [comment]
@yuvipanda Please check https://pypi.python.org/pypi/oauthenticator/0.2.0 using ``pip install oauthenticator`` I think we can close this. If you agree, click the very cool close button :wink:

**Comment by yuvipanda** [comment]
whoops - forgot to reply. THis is great - thanks @willingc :D

On Tue, Apr 26, 2016 at 2:34 AM, Min RK <notifications@github.com> wrote:

> Closed #23 <https://github.com/jupyterhub/oauthenticator/issues/23>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyterhub/oauthenticator/issues/23#event-641222229>
>



-- 
Yuvi Panda T
http://yuvi.in/blog
