### ISSUE TITLE
Wrong environment variable in README.md

### ISSUE THREAD

**Issue by bpoettinger** [jupyterhub/oauthenticator#230]
In README.md the environment variable `_OAUTH_AUTHORIZE_URL` is stated in the Moodle setup section. The correct variable is `OAUTH2_AUTHORIZE_URL`, the former one is the internal variable name...

**Comment by betatim** [comment]
Do you want to make a Pull Request to directly tackle this?

**Comment by manics** [comment]
https://github.com/jupyterhub/oauthenticator/pull/231 was merged
