### ISSUE TITLE
Issue On Using JupyterHub Generic Authenticator For PingFederate

### ISSUE THREAD

**Issue by robotsp** [jupyterhub/oauthenticator#234]
---------------myoauthauthenticator.py--------------------------
from oauthenticator.oauth2 import OAuthLoginHandler
#from oauthenticator.generic import GenericLoginHandler
from oauthenticator.generic import GenericOAuthenticator
from tornado.auth import OAuth2Mixin

# OAuth2 endpoints
class MyOAuthMixin(OAuth2Mixin):
    _OAUTH_AUTHORIZE_URL = 'https://fedauthtst.com.cn/as/authorization.oauth2?response_type=code&scope=openid+profile&pfidpadapterid=OAuth&access_token_manager_id=OAuth3'
    _OAUTH_ACCESS_TOKEN_URL = 'https://fedauthtst.com.cn/as/token.oauth2'

class MyOAuthLoginHandler(OAuthLoginHandler, MyOAuthMixin):
    pass

# Authenticator configuration
class MyOAuthAuthenticator(GenericOAuthenticator):
    login_service = 'SSO'
    login_handler = MyOAuthLoginHandler
    token_url = 'https://fedauthtst.com.cn/as/token.oauth2'
    oauth_callback_url = 'https://jupyterhub.pg.com.cn/hub/oauth_callback'
    username_key = "email"
    create_system_users = True
    client_id = 'xxxxxxx'      # Your client ID and secret, as provided to you
    client_secret = 'xxxxxxxxxxx'  # by the OAuth2 service.

-------------------jupyterhub_config.py--------------------------------------
from oauthenticator.myoauthauthenticator import MyOAuthAuthenticator
c.JupyterHub.authenticator_class = MyOAuthAuthenticator

------------------Error--------------------------------
It successfully callback to my jupyterhub with code, but jupyterhub could not get token with code (next step). It seems some problems with the handler.

https://xxxxxxxxxx/hub/oauth_callback?code=ax9Xf3F-0LwS1xWF6UFhtYLQ_zECbWpGv9cAAAEs&state=eyJzdGF0ZV9pZCI6ICJkNzc4YTM2OGQxNGU0NDE3YmIyZDgxYWE5NDNiMWFmYSIsICJuZXh0X3VybCI6ICIifQ%3D%3D

500 : Internal Server Error

generic.py：

 @gen.coroutine
    def authenticate(self, handler, data=None):
        code = handler.get_argument("code")

        # TODO: Configure the curl_httpclient for tornado
        AsyncHTTPClient.configure("tornado.curl_httpclient.CurlAsyncHTTPClient")
        http_client = AsyncHTTPClient()

        params = dict(
            redirect_uri=self.get_callback_url(handler),
            code=code,
            grant_type='authorization_code'
        )
        params.update(self.extra_params)

        if self.token_url:
            url = self.token_url
        else:
            raise ValueError("Please set the OAUTH2_TOKEN_URL environment variable")

        b64key = base64.b64encode(
            bytes(
                "{}:{}".format(self.client_id, self.client_secret),
                "utf8"
            )
        )

        headers = {
            "Accept": "application/json",
            "User-Agent": "JupyterHub",
            "Authorization": "Basic {}".format(b64key.decode("utf8"))
        }
        req = HTTPRequest(url,
                          method="POST",
                          headers=headers,
                          validate_cert=self.tls_verify,
                          body=urllib.parse.urlencode(params)  # Body is required for a POST...
                          )

Did anyone come across the same issue?  Would give me some suggestions? Thanks:)

**Comment by robotsp** [comment]
And I configuring below on jupyterhub_config.py

c.JupyterHub.ip = 'my machine's ip'
c.JupyterHub.port = 'my machine's port'

I am not sure, it is needed?

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
