### ISSUE TITLE
GenericOauthenticator fails at http_client.fetch with http 403 when setting up Jupyterhub SSO thru okta

### ISSUE THREAD

**Issue by ysy92618** [jupyterhub/oauthenticator#238]
We are trying to set up SSO to Jupyterhub thru Okta as our authentication provider.  But got the following error:
[I 2019-02-11 11:04:02.123 JupyterHub log:122] 302 GET /hub/login → /hub/oauth_login (@10.31.100.64) 0.53ms
11:04:02.164 - debug: [ConfigProxy] PROXY WEB /hub/oauth_login to http://127.0.0.1:18081
[I 2019-02-11 11:04:02.165 JupyterHub oauth2:82] OAuth redirect: 'https://<jupyterhub server>:8443/hub/oauth_callback'
[I 2019-02-11 11:04:02.166 JupyterHub log:122] 302 GET /hub/oauth_login → https://***.oktapreview.com/oauth2/***/v1/authorize?redirect_uri=https%3A%2F%2F***%3A8443%2Fhub%2Foauth_callback&client_id=***&response_type=code&state=***&scope=openid+profile+email+address+phone+offline_access (@10.31.100.64) 1.08ms
11:04:07.767 - debug: [ConfigProxy] PROXY WEB /hub/oauth_callback?code=***&state=*** to http://127.0.0.1:18081
[E 2019-02-11 11:04:08.446 JupyterHub generic:142] req = <tornado.httpclient.HTTPRequest object at 0x7fb5c4c9fc50>
[E 2019-02-11 11:04:08.518 JupyterHub web:1590] Uncaught exception GET /hub/oauth_callback?code=***&state=*** (10.31.100.64)
    HTTPServerRequest(protocol='https', host='<jupyterhubServer>:8443', method='GET', uri='/hub/oauth_callback?code=***&state=***, version='HTTP/1.1', remote_ip='10.31.100.64', headers={'X-Forwarded-Host': '<JupyterhubServer>:8443', 'X-Forwarded-Proto': 'https', 'X-Forwarded-Port': '8443', 'X-Forwarded-For': '10.31.100.64', 'Cookie': 'oauthenticator-state="2|1:0|10:1549911842|20:oauthenticator-state|***, 'Accept-Language': 'en-US,en;q=0.9', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36', 'Upgrade-Insecure-Requests': '1', 'Cache-Control': 'max-age=0', 'Connection': 'close', 'Host': '<Jupyterhubserver>:8443'})

    Traceback (most recent call last):
      File "/users/anaconda3/lib/python3.6/site-packages/tornado/web.py", line 1511, in _execute
        result = yield result
      File "/users/anaconda3/lib/python3.6/site-packages/oauthenticator/oauth2.py", line 182, in get
        user = yield self.login_user()
      File "/users/anaconda3/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 327, in login_user
        authenticated = yield self.authenticate(data)
      File "/users/anaconda3/lib/python3.6/site-packages/jupyterhub/auth.py", line 221, in get_authenticated_user
        authenticated = yield self.authenticate(handler, data)
      File "/users/anaconda3/lib/python3.6/site-packages/oauthenticator/generic.py", line 144, in authenticate
        resp = yield http_client.fetch(req)
    tornado.httpclient.HTTPError: HTTP 403: Forbidden
[D 2019-02-07 10:03:37.966 JupyterHub base:632] No template for 500
[E 2019-02-11 11:04:08.520 JupyterHub log:114] {
      "X-Forwarded-Host": "<JupyterhubServer>:8443",
      "X-Forwarded-Proto": "https",
      "X-Forwarded-Port": "8443",
      "X-Forwarded-For": "10.31.100.64",
      "Cookie": "oauthenticator-state=\"2|1:0|10:1549911842|20:oauthenticator-state|***|***",
      "Accept-Language": "en-US,en;q=0.9",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
      "User-Agent": "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36",
      "Upgrade-Insecure-Requests": "1",
      "Cache-Control": "max-age=0",
      "Connection": "close",
      "Host": "<JupyterhubServer>:8443"
    }

Here's our configuration in jupyterhub_configy.py as instructed by our Okta Admin:
c.Authenticator.auto_login = True
from oauthenticator.generic import GenericOAuthenticator
c.JupyterHub.authenticator_class = GenericOAuthenticator

c.GenericOAuthenticator.oauth_callback_url = 'https://$jupyterhubServer:8443/hub/oauth_callback'
c.GenericOAuthenticator.client_id = $clientID
c.GenericOAuthenticator.client_secret = $clientSecret
c.GenericOAuthenticator.userdata_url = 'https://$OkataServer/oauth2/v1/clients'
c.GenericOAuthenticator.token_url = $OktaTokenUrl
c.GenericOAuthenticator.username_key = 'preferred_username'
c.GenericOAuthenticator.userdata_params = {"state": "state"}
c.GenericOAuthenticator.scope = ['openid', 'profile', 'email', 'address', 'phone', 'offline_access']

We also set up the below environment variables for Jupyterhub:
OAUTH2_AUTHORIZE_URL=$okta-authorize-url
OAUTH2_TOKEN_URL=$okta-token-url

Our jupyterhub server has been added to okta whitelist so access from okta should not be an issue. I turned on the debug, but still can't tell which configuration caused the issue.  Any help will be appreciated.

**Comment by sunmakrules** [comment]
Hi, I am facing the same issue. Did any of you manage to fix it? If not, Is there a workaround until we have a fix?

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
