### ISSUE TITLE
Question on support for Elliptical Curve Algorithms

### ISSUE THREAD

**Issue by jiyer2016** [jupyterhub/oauthenticator#239]
I work for a firm and a few months back configured a Jupyterhub installation to talk to an in-house OAUTH2 Service provider. Its all working perfectly well. 

A few days back, I was told that the in-house OAUTH2 Service provider is undergoing an upgrade and future versions will require integrating platforms / apps to support "Elliptic Curve algorithms".

Now, I don't understand what "Elliptic Curve Algorthims" exactly means - but I checked the jupyterhub's documentation to see if this is supported. So, far I have had NO luck. 

Would anyone be able to advise whether or NOT support for "Elliptic Curve Algorithms" is available on JupyterHub ?

Thanks in advance.

**Comment by jiyer2016** [comment]
anyone have inputs to this question ? Thanks in advance.

**Comment by jiyer2016** [comment]
anyone have inputs to this question ? Thanks in advance.

**Comment by manics** [comment]
I think the supported algorithms and protocols are determined by your underlying python and openssl libraries: https://docs.python.org/3/library/ssl.html
