### ISSUE TITLE
Include  Gitlab local authentication details in read.md  

### ISSUE THREAD

**Issue by divatemangesh** [jupyterhub/oauthenticator#243]
In GITLAB  authentication section  for local authentication, there are not many details 

> You can use your own GitLab CE/EE instance by setting the GITLAB_HOST environment flag.

in the above statement where to set the environmental flag is not mentioned. it is to be written in an auth.env file or somewhere else.

also using Gitlab Local authenticator doesn't solve the problem it. For authentication is always going to gitlab.com

**Comment by ghezalsherdil** [comment]
I am having the same issue, is there any updates on this?

**Comment by divatemangesh** [comment]
Gitlab local authenticator does not mean authentication will happen from local gitlab server. But when using git lab local authenticator it  uses  userlist file  which is stored locally and authenticate only user which are specified in userlist file.

If you are  getting redirected  gitlab.com.
That means you need to set  one envornmental variable in.  Secret/auth.env file
Set gitlab_host=<gitlab_ip_address:port>
also set gitlab_url env with same value as gitlab_host will be deprected soon and will be replaced by gitlab_url.

For gitlab url dont use ip address of  gitlab container(if running in container) but put  ipaddress  which  gives gitlab homepage/loginpage from browser.

**Comment by mesudip** [comment]
How do I make sure that the user's home directory is created after the GitLab login? 

Let's say a user `user` is logged successfully to JupyterHub using GitLab Oauth, but **Start My Server** will always fail because there is no `/home/user` directory created in JupyterHub.

I can solve it by adding the user using `adduser` command in JupyterHub for each user.  Is there a better way?

**Comment by manics** [comment]
I'm closing this as it's quite old and there's no concrete action point. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/) or open a new issue. Thanks!
