### ISSUE TITLE
[Generic] extra_params not exposed for the authorize request

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/oauthenticator#244]
We are making various requests while working with _authz_ (authorization) and _authn_ (authentication). A common request is to do the initial authorization request with _client_id_,_scope_ and _response_type_, _redirect_uri_ etc. This is done in the `oauth2.py` file by relying on a tornado function that the class has inherited and can be read about [here](https://www.tornadoweb.org/en/stable/auth.html).

https://github.com/jupyterhub/oauthenticator/blob/5b0b395326292d526a4c924c34c6d9d1d06818af/oauthenticator/oauth2.py#L80-L90

As we can see, we use the `extra_params` in a hardcoded fashion passing only a state, something very important to protect against CSRF to be explained elsewhere. But, we may want to pass additional parameters in this request, for example I'm now required by Okta to pass along one more to work well with them (which sadly is absurd).

Anyhow, we should allow this parameters to be configurable I think. But, also note that since we will make multiple types of request, we must scope the parameters to the associated request. I know the `generic.py` file defines a `extra_params` traitlet:

https://github.com/jupyterhub/oauthenticator/blob/5b0b395326292d526a4c924c34c6d9d1d06818af/oauthenticator/generic.py#L52-L54

But this extra_params is only used in the second request associated with OAUTH2_TOKEN_URL, the request of a token which can be used to fetch user information from the userinfo endpoint.

---

## Conclusion
We can now using `generic.py`'s `GenericOAuthenticator` configure the extra params passed to the `OAUTH2_TOKEN_URL`, but we cannot configure the params passed to `OAUTH2_USERDATA_URL` or the initial request to `OAUTH2_AUTHORIZE_URL`.

## Suggestion
We add traitlets to configure this, and name them related to AUTHORIZE, TOKEN, USERDATA.

> NOTE: USERDATA is typically referred to as USERINFO in the Open ID Connect (OIDC) specifications (`authorization_endpoint`, `token_endpoint`, `userinfo_endpoint`)

**Comment by erowan** [comment]
I need to pass extra info in here too

**Comment by d0m84** [comment]
I faced the same challenge today and it's not straight forward. Finally I fixed it by reading the code.
My impression was that `extra_params` will be used for the authorization request as well, but it's not.

Finally I fixed it by adding my own custom parameter to the environment variable. 

`OAUTH2_AUTHORIZE_URL="https://auth.example.com/authorize?my_param=example"`

The parameter will be included in the authorization request afterwards since `urllib` will put the pieces together correctly afterwards.

So there is definitely room to improve at least for the documentation of the generic example.

**Comment by consideRatio** [comment]
@d0m84 I recall trying that as well, but getting issues with having double `?` with my provider, as compared to `?` following `&`. Good it worked for you!

**Comment by d0m84** [comment]
@consideRatio 
You are right. When writing the comment I mixed up two pieces of code. The double `?` might be problematic for various server implementations. Sorry that it doesn't work for you.

**Comment by d0m84** [comment]
@consideRatio 
I checked my Jupyterhub logs today. I don't see a double `?` in the generated authorization URL. When you login with oauth you should see a log line like this:

`GET /hub/oauth_login?next= -> https://auth.example.com/authorize?my_param=example&..`

**Comment by consideRatio** [comment]
Ah nice @d0m84! Then this is a viable workaround for the limitation of not being able to configure this in a less obfuscated way!

**Comment by manics** [comment]
Is there any action to be taken here, or can we close this?

**Comment by d0m84** [comment]
> 
> 
> Is there any action to be taken here, or can we close this?

Sounds like it is not used for the generic authenticator so far. https://github.com/jupyterhub/oauthenticator/pull/338#issuecomment-624693757 
If that's the case it doesn't solve the issue for me. (I'm not able to test anymore).

**Comment by consideRatio** [comment]
It is my understanding from #338 that this is resolved now by configuring `extra_authorize_params`! Thank you @NickolausDS!
