### ISSUE TITLE
Restructure to make more use of tornados auth stuff?

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/oauthenticator#245]
Apparently tornado has a lot of features for working with OAuth2 (authorize + token endpoint) and Open ID Connect (authorize + token + userinfo endpoint).

In `oauth2.py` we handle the authorize stuff using a tornado defined function called `authorize_redirect`:

https://github.com/jupyterhub/oauthenticator/blob/5b0b395326292d526a4c924c34c6d9d1d06818af/oauthenticator/oauth2.py#L80-L90

But in `oauth2.py` we dont handle the authenticate stuff:

https://github.com/jupyterhub/oauthenticator/blob/5b0b395326292d526a4c924c34c6d9d1d06818af/oauthenticator/oauth2.py#L278-L280

---

In `generic.py` we handle the authenticate stuff and the userinfo stuff, but this is done without the support of tornado's auth functions described here: https://www.tornadoweb.org/en/stable/auth.html

While there are `authorize_redirect`, there is also `authenticate_redirect` and `get_authenticated_user`.

---

## Suggested action

We investigate if we could refactor stuff to rely on tornado's implementations instead of rebuilding a lot of stuff ourselves.

## Updates

- Warning, the `tornado.auth.OpenIdMixin` is referring OpenID 2.0 which is not the same as OpenID Connect based on OAuth2 and what is commonly used. See https://groups.google.com/forum/#!topic/python-tornado/Jimtp8xVD6w

**Comment by minrk** [comment]
We already build on tornado's auth construction, so I'm not sure there's much more we can re-use than we already do.

Note that most of tornado.auth is dedicated to OAuth 1.0, not OAuth 2. ~all of tornado's OAuth 2 is in what we inherit from the OAuth2 mixin.

I think this can be closed.
