### ISSUE TITLE
GenericoAuthenticator fails with 401 trying to get token with code

### ISSUE THREAD

**Issue by kyeotic** [jupyterhub/oauthenticator#247]
This issue is similar to [this one](https://github.com/jupyterhub/oauthenticator/issues/238), but we are getting a different result.

The issue comes after the oAuth code has been retrieved, when the token request is made. I am using Okta.

If I try the token request manually, from postman, with the auth _code from the logs it works. This is definitely an issue with Jupyterhub.

## Configuration
```
hub:
  imagePullPolicy: Always
  service:
    annotations:
      iam.amazonaws.com/role: "ngp_apps-development-eks-dev-worker"
  extraConfig:
    myConfig: |
      from oauthenticator.generic import GenericOAuthenticator
      c.JupyterHub.authenticator_class = GenericOAuthenticator
      c.JupyterHub.authenticator_class.delete_invalid_users = True
      c.JupyterHub.authenticator_class.auto_login = True
  extraEnv:
    OAUTH_CLIENT_ID: "***"
    OAUTH_CLIENT_SECRET: "***"
    OAUTH_CALLBACK_URL:  http://callysto.lab.niketech.com/hub/oauth_callback
    OAUTH2_USERNAME_KEY: "sub"
    OAUTH2_USERDATA_URL: https://auth.preprod.niketech.com/api/v1/userinfo
    OAUTH2_TOKEN_URL: https://auth.preprod.niketech.com/api/v1/token
    OAUTH2_AUTHORIZE_URL: 'https://auth.preprod.niketech.com/api/v1/authorize?scope=openid email'
```

## Error
(`***` = REDACTED)
``` bash
[I 2019-03-13 18:06:09.224 JupyterHub log:158] 302 GET /hub/oauth_login -> https://auth.preprod.niketech.com/api/v1/authorize?scope=openid+email&redirect_uri=http%3A%2F%2Fcallysto.lab.niketech.com%2Fhub%2Foauth_callback&client_id=nike.niketech.callysto&response_type=code&state=[secret] (@10.178.152.188) 1.61ms
[E 2019-03-13 18:06:10.906 JupyterHub web:1670] Uncaught exception GET /hub/oauth_callback?code=***&state=*** (10.178.152.188)
    HTTPServerRequest(protocol='http', host='callysto.lab.niketech.com', method='GET', uri='/hub/oauth_callback?code=***&state=***', version='HTTP/1.1', remote_ip='10.178.152.188')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/usr/local/lib/python3.6/dist-packages/oauthenticator/oauth2.py", line 182, in get
        user = yield self.login_user()
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py", line 473, in login_user
        authenticated = await self.authenticate(data)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/auth.py", line 257, in get_authenticated_user
        authenticated = await maybe_future(self.authenticate(handler, data))
      File "/usr/local/lib/python3.6/dist-packages/oauthenticator/generic.py", line 116, in authenticate
        resp = yield http_client.fetch(req)
    tornado.httpclient.HTTPClientError: HTTP 401: Unauthorized
```

**Comment by nadav-robas** [comment]
@kyeotic  
I'm experiencing a similar issue too.
Have you found a solution?

**Comment by kipstakkr** [comment]
@kyeotic Have you found a solution for it? I'm too stuck with the same error when connecting to my organization's own Identity service platform

**Comment by kyeotic** [comment]
@kipstakkr @nadav-robas No, we ended up writing our own authenticator.

**Comment by shivan10** [comment]
I'm currently using Azure AD Authentication and I'm able to generate a code using my client id and secret. But I end up with a screen saying 500 internal server error. Checking docker logs shows me an HTTP error code of 401. Has anyone faced a similar issue? How did you get around it?

**Comment by scivm** [comment]
I am getting the same error.   Have not solved it yet.   I am using zero to kubernetes jupyterhub 

hub:
  extraEnv:
    AAD_TENANT_ID: "xxxx"
  image:
    name: jupyterhub/k8s-hub
    tag: 0.9-17c3f1d

spec:
  env:
    - name: AAD_TENANT_ID
      value: xxxx

auth:
    type: custom
    custom:
      className: "oauthenticator.azuread.AzureAdOAuthenticator"
      config:
        client_id: "xxxx"
        client_secret: "xxxx"
        oauth_callback_url: "http://xxx/hub/oauth_callback"
        tenant_id: "xxxx"

**Comment by kyeotic** [comment]
If you are getting a 500 then that's a seperate issue. Please create a new GitHub issue to track it

**Comment by manics** [comment]
I'm closing this as it's quite old and there's no concrete action point. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/) or open a new issue. Thanks!
