### ISSUE TITLE
Using JupyterHub with Django OAuthenticator

### ISSUE THREAD

**Issue by scooper001** [jupyterhub/oauthenticator#249]
I'm trying to build a Django web application that will have Jupyter notebook through the JupyterHub server embedded within the app, where users could login via the app and can access the notebook once they are in. I'm trying to use OAuth2 where JupyterHub verifies the authenticated users that Django provides.

I am using django-oauth-toolkit for the authentication service and linking it using DjangoOAuthentication.

I have the DjangoOAuthenticator oauth_callback_url linked to 'http://localhost:8081/hub/oauth_callback'

I have the Redirect uris (on Django) linked to 'http://localhost:8081/hub/oauth_callback'

I get:

`**404 : Not Found** Jupyter has lots of moons, but this is not one...`

```
[I 2019-03-18 16:28:54.195 JupyterHub oauth2:82] OAuth redirect: 'http://localhost:8081/hub/oauth_callback'
[I 2019-03-18 16:28:54.198 JupyterHub log:158] 302 GET /hub/oauth_login?next= -> localhost/oauth2/authorize?client_id=zkn2mFYhhNcs3bDTnwIWK0mDuLBdLAe2eMENE5Xa&response_type=code&state=[secret]&redirect_uri=http%3A%2F%2Flocalhost%3A8081%2Fhub%2Foauth_callback (@127.0.0.1) 3.94ms
[W 2019-03-18 16:28:54.230 JupyterHub log:158] 404 GET /hub/localhost/oauth2/authorize?client_id=zkn2mFYhhNcs3bDTnwIWK0mDuLBdLAe2eMENE5Xa&response_type=code&state=[secret]&redirect_uri=http%3A%2F%2Flocalhost%3A8081%2Fhub%2Foauth_callback (@127.0.0.1) 17.81ms
```
The URL it goes to:

`http://localhost:8081/hub/localhost/oauth2/authorize?client_id=zkn2mFYhhNcs3bDTnwIWK0mDuLBdLAe2eMENE5Xa&response_type=code&state=eyJzdGF0ZV9pZCI6ICJlZTA0MmRiYmU4YTY0ZmIxYTk0ODU0MjFiMzhhMWYwOCIsICJuZXh0X3VybCI6ICIifQ%3D%3D&redirect_uri=http%3A%2F%2Flocalhost%3A8081%2Fhub%2Foauth_callback`

I believe I have either the oauth_callback_url or the redirect_uri on Django set up wrong.

Note: My question is not a duplicate of Using Django OAuth2 provider #153 . We have different errors.

Thank you.

**Comment by divatemangesh** [comment]
@scooper001 please let us know when you are getting error while getting redirecting from jupyterhub  to authenticator or from authenticator to jupyter.

Also let us know where did you specified
"oauth_callback_url"
and " redirect uri"

**Comment by scooper001** [comment]
oauth_callback_url is set at the JupyterHub config file as follows:

```
import os
c = get_config()
from oauthenticator.django import LocalDjangoOAuthenticator
c.JupyterHub.authenticator_class = LocalDjangoOAuthenticator
c.DjangoOAuthenticator.oauth_callback_url = 'http://localhost:8000/hub/oauth_callback'
c.DjangoOAuthenticator.client_id = ''
c.DjangoOAuthenticator.client_secret = ''
c.JupyterHub.config_file = 'jupyterhub_config.py'
c.ConfigurableHTTPProxy.debug = True
c.ConfigurableHTTPProxy.should_start = False
c.ConfigurableHTTPProxy.auth_token = 'CONFIGPROXY_AUTH_TOKEN'
c.JupyterHub.hub_ip = ''
c.JupyterHub.hub_port = 8081
c.JupyterHub.port = 8000
c.JupyterHub.logo_file = '/srv/jupyterhub/jupyter.png'
c.JupyterHub.spawner_class = 'simplespawner.SimpleLocalProcessSpawner'
```
redirect uri set on the Django application:
'http://localhost:8000/hub/oauth_callback'

The error appears right after I click on Sign in with Django.

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
