### ISSUE TITLE
OAuth2Mixin mixed in too late (in generic.py / google.py etc instead of in oauth2.py)

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/oauthenticator#250]
The OAuthLoginHandler defined in `oauth2.py` is using `self.authorize_redirect` (Line 85), but that is a function not defined in the class, or its base class `jupyterhub.handlers.BaseHandler`, or its base class `tornado.web.RequestHandler`. It is simply assumed that the `OAuthLoginHandler` class will be subclassed and get the `tornado.auth.OAuth2Mixin`. This took a while for me to understand ;D

https://github.com/jupyterhub/oauthenticator/blob/5b0b395326292d526a4c924c34c6d9d1d06818af/oauthenticator/oauth2.py#L59-L90

I figure it would be fine to simply mixin the OAuth2Mixin to the `OAuthLoginHandler` as it actually needs it, and remove the OAuth2Mixin from here for example.

https://github.com/jupyterhub/oauthenticator/blob/5b0b395326292d526a4c924c34c6d9d1d06818af/oauthenticator/generic.py#L24-L30

**Comment by minrk** [comment]
Closing in favor of #312 which should solve this and we shouldn't need two issues to track it.
