### ISSUE TITLE
Forced to use environment variables :'(

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/oauthenticator#255]
I think I'm forced to use environment variables to configure the OAuthenticator, for example: `OAUTH2_AUTHORIZE_URL` can only be provided as an environment variable. This is because it is used to set the `tornado.auth.OAuth2Mixin`'s `_OAUTH_AUTHORIZE_URL` value that we need to set.

https://github.com/jupyterhub/oauthenticator/blob/5b0b395326292d526a4c924c34c6d9d1d06818af/oauthenticator/generic.py#L24-L26

Perhaps we can make it so that overriding a traitlet called `authorize_url` will set the `_OAUTH_AUTHORIZE_URL` from the `tornado.auth.OAuth2Mixin` so we are not forced to use environment variables?

Same goes for the `_OAUTH_ACCESS_TOKEN_URL` I think...

**Comment by consideRatio** [comment]
I recall i made the same conclusion, but ended up debugging a long time for why things did not work, and finally realizing it was used by tornados auth module as well.

So i think it needs to be set in multiple places to really do the job.

/ erik and a short response from mobile

**Comment by manics** [comment]
I think this was fixed by https://github.com/jupyterhub/oauthenticator/pull/323 ?

**Comment by consideRatio** [comment]
I think so! Thank you @manics for your excellent work to issue triage this repo! :heart: :heart: :heart: :tada:

**Comment by manics** [comment]
@consideRatio I was inspired by your Z2JH epic 😀
