### ISSUE TITLE
Using Google Auth for Office365 accounts?

### ISSUE THREAD

**Issue by mathematicalmichael** [jupyterhub/oauthenticator#256]
Since the Gmail application on phones can log in to a university email system managed by Microsoft, could it be similarly possible to have the Google authenticator allow students to log in with their university credentials? 

(the admins/IT at our university are impossible to work with and we'd like to get authentication working for all students, independently, through the department).

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
