### ISSUE TITLE
JUPYTERHUB_CRYPT_KEY env

### ISSUE THREAD

**Issue by alvinhuff** [jupyterhub/oauthenticator#260]
When I run jupyterhub --debug from /etc/jupyterhub I get the below message at the end of the debugging session. 

**auth_state is enabled, but encryption is not available: Encryption keys must be specified in JUPYTERHUB_CRYPT_KEY env**

I am using a reverse proxy with nginx/letsencrypt/certbot for https.  Do I need to be concerned with output from --debug?  

eventually I want to setup OAuth (Globus, ASU-CAS or ASU-Shibboleth)

This is a docker container running on a vm (Jetstream/XSEDE).  If I do need the "JUPYTERHUB_CRYPT_KEY " would that be an "env" file in the CWD with a line like this: "export JUPYTERHUB_CRYPT_KEY = {openssl rand -hex 32}" ?

**Comment by bmshouse** [comment]
Globus in particular will require the the key to be set. For The Littlest JupyterHub, I just ran `tljh-config set hub.extraEnv.JUPYTERHUB_CRYPT_KEY 'XXX'` where XXX is the output from `openssl rand -hex 32`  For the Dockerfile, I would suspect a line like:`ENV JUPYTERHUB_CRYPT_KEY XXX` where is the openssl rand output.

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
