### ISSUE TITLE
Accessing access token from within the notebook

### ISSUE THREAD

**Issue by xmichaelx** [jupyterhub/oauthenticator#264]
I login using generic OAuth client, is it possible to retrieve access token of currently logged in user from within the notebook?

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!

**Comment by nicornk** [comment]
@xmichaelx did you ever get an answer to this question?
