### ISSUE TITLE
[GitHub] We can authorize organizations, but what about teams within them?

### ISSUE THREAD

**Issue by scottyhq** [jupyterhub/oauthenticator#265]
Currently GitHub authentication is setup to whitelist individual users or entire organizations:
https://github.com/jupyterhub/oauthenticator/blob/master/oauthenticator/github.py

See here for the implementation:
https://zero-to-jupyterhub.readthedocs.io/en/latest/authentication.html?highlight=auth#github

It would be great to be able to whitelist Teams within a given organization:
https://developer.github.com/v3/teams/members/#get-team-membership 

We are currently creating many new organizations on github for week-long tutorials to grant time-limited access to hubs. Having team-based authentication could help with a few scenarios:

1) medium/large github organizations with application-specific hubs (https://github.com/pangeo-data)

2) could also be a really useful feature for resource access based on team membership within a hub (for example, mapping team name to group id)?

**Comment by yuvipanda** [comment]
I'm pretty sure we'd love a PR!

**Comment by sgibson91** [comment]
I'm gonna work on this as part of Pangeo's migration to 2i2c 🙂  https://github.com/2i2c-org/pilot-hubs/issues/482#issuecomment-893548362
