### ISSUE TITLE
302 Redirect issue 

### ISSUE THREAD

**Issue by hedgehog-millenium** [jupyterhub/oauthenticator#271]
Are you using the environment variables?

OAUTH2_TOKEN_URL # the same as token_url param
OAUTH2_AUTHORIZE_URL # oauth2 provider's authorization andpoint

_Originally posted by @dmvieira in https://github.com/jupyterhub/oauthenticator/issues/107#issuecomment-332361208_

**Comment by hedgehog-millenium** [comment]
I'm setting up all the params mentions for GenericOAuthenticator even adding mentioned env variables but still have the same issue with redirection and not able to see KeyCloak login page

**Comment by RAbraham** [comment]
I think I'm having the same issue. I have followed the directions [here](https://zero-to-jupyterhub.readthedocs.io/en/latest/authentication.html#openid-connect). I get ERR_TOO_MANY_REDIRECTS error on Chrome. I think the variable OAUTH2_AUTHORIZE_URL is not being used. When I inspect the 302 response, it's 
```
?response_type=code&redirect_uri=https%3A%2F%2Fmynotebook.com%2Fhub%2Foauth_callback&client_id=jupyterhub&state=mystate
```
Since OAUTH2_AUTHORIZE_URL is not used, it redirects to the notebook site itself?(i.e. https://mynotebook.com)

**Comment by RAbraham** [comment]
I got it to work thanks to jmatuskey's original [question](https://discourse.jupyter.org/t/genericoauthenticator-wont-read-env-vars-in-1-0/984l) .i.e. by using `hub.extraConfig.myConfig.py` (note it is different from jmatuskey who uses `hub.extraConfig.myConfig`) but my context is JupyterHub on Kubernetes and [it](https://zero-to-jupyterhub.readthedocs.io/en/latest/reference.html#hub-extraconfig) suggests `myConfig.py`

**Comment by Nop0x** [comment]
@RAbraham can you maybe give a different link to the original question? It seems like there is no way to access what you linked.

**Comment by RAbraham** [comment]
@Nop0x my bad. I had a typo in my link. Please try now, if not, I'll paste the solution.

**Comment by guimou** [comment]
I'm facing the same problem. Could you describe the solution a little bit more? I read all the linked thread, but as I don't use Helm charts but s2i (originally based on jupyterhub-quickstart from Graham Dumpleton), I can't figure out what to put where...
I tried something like this based on the provided hints, but no luck (EnvGenericOAuthenticator is a custom class based on GenericOAuthenticator where I retrieve user secrets from Vault using their keycloak JWT they used to login to Jupyterhub):
`c.JupyterHub.authenticator_class = EnvGenericOAuthenticator
c.GenericOAuthenticator.login_handler._OAUTH_AUTHORIZE_URL = 'https://%s/auth/realms/%s/protocol/openid-connect/auth' % (keycloak_hostname, keycloak_realm)
c.GenericOAuthenticator.login_service = "KeyCloak"
c.GenericOAuthenticator.oauth_callback_url = 'https://%s/hub/oauth_callback' % jupyterhub_hostname
c.GenericOAuthenticator.client_id = os.environ.get('OAUTH_CLIENT_ID')
c.GenericOAuthenticator.client_secret = os.environ.get('OAUTH_CLIENT_SECRET')
...`

**Comment by guimou** [comment]
OK, after lots of try and errors, here is my working configuration:
- c.JupyterHub.authenticator_class.login_handler._OAUTH_AUTHORIZE_URL = ... has to be set in jupyterhub_config.py. It does not work as only OAUTH_AUTHORIZE_URL env var in the deployment configuration.
- OAUTH2_TOKEN_URL, OAUTH2_USERDATA_URL and OAUTH2_USERNAME_KEY have to be set as en var in the deployment configuration. It does not work if I set them following the same pattern as previous point in jupyterhub_config.py.
Maybe it makes sense considering the way GenericOAuthenticator is coded and the behavior of JH in version 1, but it's not really straightforward and poses problem for sure when upgrading versions.

**Comment by GrahamDumpleton** [comment]
See also:

* https://github.com/jupyterhub/oauthenticator/issues/286

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
