### ISSUE TITLE
use baseHandler to set cookie

### ISSUE THREAD

**Issue by shreddd** [jupyterhub/oauthenticator#277]
Currently oauth.py directly calls the tornado set_secure_cookie when setting the state cookie here:
https://github.com/jupyterhub/oauthenticator/blob/master/oauthenticator/oauth2.py#L67

This bypasses a bunch of logic in the JupyterHub BaseHandler to handle things like custom cookie options and handling some other edge cases. 
See:
https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/handlers/base.py#L488

The example I had in mind was setting "secure: True" via cookie_options to force secure cookies in an SSL terminated environment, but there are plenty of other use cases.

It might make sense to just call BaseHandler._set_cookie instead. If this sounds like the right thing to do, I can submit a PR.

**Comment by Wh1isper** [comment]
I agree !
I meet the same problem: secure flag missing in HTTPS query
I try this way but in k8s config.yaml but secure flag is still missing
`from oauthenticator.generic import GenericOAuthenticator
      from oauthenticator.oauth2 import OAuthLoginHandler, STATE_COOKIE_NAME
      class SecureOAuthLoginHandler(OAuthLoginHandler):
          def set_state_cookie(self, state):
              self._set_cookie(STATE_COOKIE_NAME, state, expires_days=1, httponly=True)
      class SecureOAuthenticator(GenericOAuthenticator):
          login_handler = SecureOAuthLoginHandler
      c.JupyterHub.authenticator_class = SecureOAuthenticator`

**Comment by consideRatio** [comment]
## Help wanted
- [ ] Validate this makes sense (@minrk, @GeorgianaElena, perhaps this is something you can help with?)
- [ ] Create a PR -> Review -> Merge
