### ISSUE TITLE
Tenant-ID

### ISSUE THREAD

**Issue by JulianTBZ** [jupyterhub/oauthenticator#278]
Hi all, 

I try to install the oauthenticator on my Jupyterhub Server with AAD authentication. 
But I get the following error when I made my config. 
Do I take the wrong ID?
Azure AD --> Settings --> Directory ID

> traitlets.traitlets.TraitError: The 'tenant_id' trait of an AzureAdOAuthenticator instance must be a unicode string, but a value of None <class 'NoneType'> was specified.

Thanks
KR,
Julian

**Comment by ericdeflaminis** [comment]
The value should be in AAD > Properties > Directory ID.

It should be passed in as an environment variable - statically referencing it in the Jupyter config does not seem to work.

**Comment by JulianTBZ** [comment]
Hi @ericdeflaminis,
Thanks for your reply. 
The ID I found already. 
But my problem is that I get the Error message "instance must be a unicode string" when I enter the ID into the configuration file. 
Can I see anywhere what format I need to use? 
KR, 
Julian

**Comment by espenfl** [comment]
> The value should be in AAD > Properties > Directory ID.
> 
> It should be passed in as an environment variable - statically referencing it in the Jupyter config does not seem to work.

Does anyone know why this does not work?

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
