### ISSUE TITLE
Add documentation for ORCID-based authentication

### ISSUE THREAD

**Issue by nuest** [jupyterhub/oauthenticator#284]
Almost every researcher has (or will sooner or later have) and ORCID, see https://orcid.org/

It would be useful to be able to _whitelist_ a number of ORCIDs for a JupyterHub instance, e.g. via a database, or via a file with one ORCID per line.

This could allow journals or universities, who are likely to require their authors to have an ORCID, to use authentication without needing their own secure password storage or OAuth mechanism.

**Comment by manics** [comment]
Does the generic authenticator work? https://github.com/jupyterhub/oauthenticator/blob/master/oauthenticator/generic.py

**Comment by betatim** [comment]
You can create a OAuth application on the orcid page https://orcid.org/developer-tools and then use the generic OAuthenticator in this package. No need to do a hop via an extra intermediary like Globus.

**Comment by nuest** [comment]
Thanks for the replies! I'll try it out and then prepare a PR with documentation, so that the next person does not have to find this thread :-).

**Comment by consideRatio** [comment]
Hi @nuest! Do you have some experience to report back with at this point in time? I was issue triaging this repo and figured it may be a good time to close this issue without further input.

**Comment by matthewwiese** [comment]
@consideRatio @nuest I've forked this repository to add `OrcidOAuthenticator`, subclassed from `OAuthenticator`: https://github.com/matthewwiese/oauthenticator/blob/main/oauthenticator/orcid.py

It's been working great in our lab and I'd be happy to open a PR and clean it up for merging upstream if there is interest.

**Comment by matthewwiese** [comment]
@consideRatio I've opened PR #655 to resolve this issue
