### ISSUE TITLE
Entrypoints causes issues with JupyterHub.

### ISSUE THREAD

**Issue by GrahamDumpleton** [jupyterhub/oauthenticator#286]
A number of the authenticators require environment variables to be set up in order to be used. For example `openshift`:

```
os.environ['OPENSHIFT_URL'] = oauth_issuer_address

os.environ['OPENSHIFT_REST_API_URL'] = kubernetes_server_url
os.environ['OPENSHIFT_AUTH_API_URL'] = oauth_issuer_address

from oauthenticator.openshift import OpenShiftOAuthenticator
c.JupyterHub.authenticator_class = OpenShiftOAuthenticator
```

but also `generic` OAuth authenticator. Even things like GitHub authenticator rely on environment variables for service host.

The setting of the environment variables used to be able to be done in the `jupyterhub_config.py` file by setting them via `os.environ` and then importing the authenticator.

This pattern no longer works because the addition of the entrypoints for the authenticators results in the modules for the authenticators seem to be preloaded prior to the `jupyterhub_config.py` file being processed.

Change where entry points was added is:

* https://github.com/jupyterhub/oauthenticator/commit/5a6e94352e5c3940ee0e55594e8146f6b0985cb8

The only workaround at the moment seems to be to use:

```
del sys.modules['oauthenticator.openshift']

from oauthenticator.openshift import OpenShiftOAuthenticator
c.JupyterHub.authenticator_class = OpenShiftOAuthenticator
```

That is, delete the imported module from `sys.modules` and thus force reloading of it.

Long term, all the authenticator modules that need environment variables for some things, if you want to be able to configure them from `jupyterhub_config.py` will need to support configuration using traitlets. Whether that is possible is all cases isn't clear though.

The only other choice seems to be to set the environment variables before JupyterHub is started, which isn't necessarily convenient when `jupyterhub_config.py` was the only place provided to configure anything.

Is there perhaps a way to tell JupyterHub not to preload the modules for all the authenticators?

**Comment by GrahamDumpleton** [comment]
Should clarify, this is when used with JupyterHub 1.0 specifically.

**Comment by manics** [comment]
> Long term, all the authenticator modules that need environment variables for some things, if you want to be able to configure them from jupyterhub_config.py will need to support configuration using traitlets. Whether that is possible is all cases isn't clear though.

If it works I think this is the nicest solution, since it means all Authenticator config can be configured in one place.

**Comment by GrahamDumpleton** [comment]
The problem is how to deal with things like:

* https://github.com/jupyterhub/oauthenticator/blob/master/oauthenticator/generic.py#L25
* https://github.com/jupyterhub/oauthenticator/blob/master/oauthenticator/openshift.py#L26

Those settings in the mixin base classes.

**Comment by manics** [comment]
I wonder if it could be optionally initialised in the constructor for the LoginHandler https://github.com/jupyterhub/oauthenticator/blob/158eb206dd2b59961442a4d3b67fbbb179a3030a/oauthenticator/generic.py#L40

**Comment by consideRatio** [comment]
@GrahamDumpleton thank you for an excellent issue, well done figuring this out and summarizing it like this! ❤️
