### ISSUE TITLE
Oauthenticator could not be imported

### ISSUE THREAD

**Issue by orngcom** [jupyterhub/oauthenticator#289]
I'm trying to integrate Auth0 with my JupyterHub but I keep getting this error:

The 'authenticator_class' trait of <jupyterhub.app.JupyterHub object at 0x7f44b0808b38> instance must be a type, but 'oauthenticator.auth0.Auth0OAuthenticator' could not be imported.

I've set:
from oauthenticator.auth0 import Auth0OAuthenticator, LocalAuth0OAuthenticator
c.JupyterHub.authenticator_class = 'oauthenticator.auth0.Auth0OAuthenticator'
c.Auth0OAuthenticator.client_id = 'xxx'
c.Auth0OAuthenticator.client_secret = 'xxx'
c.Auth0OAuthenticator.oauth_callback_url = 'https://jupyterhub.demo/hub/oauth_callback'

in my jupyterhub_config.py 

and installed the module with:
pip3 install oauthenticator.

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
