### ISSUE TITLE
Google OAuth: prompt=select_account 

### ISSUE THREAD

**Issue by bmshouse** [jupyterhub/oauthenticator#298]
Situation: User attempts to login to a service while already authenticated to their personal email address. The service is restricted to Internal Email addresses only and the users is immediately redirected to a Google forbidden (403) page.  

Potential Solution: Google offers an [Authorization Parameter](https://developers.google.com/identity/protocols/OAuth2WebServer#creatingclient) "prompt" that when set to "select_account" will allow users to pick/login to another account. 

Problem: I have failed to identify where I can add this authorization paramater.  It seems like extra_params mentioned in #244 could address this also. 

I appreciate any assistance you can offer.  Thank you.

**Comment by manics** [comment]
Solved by https://github.com/jupyterhub/oauthenticator/pull/338
