### ISSUE TITLE
401 Unauthorized on callback request, AzureAD 

### ISSUE THREAD

**Issue by konradsitarz** [jupyterhub/oauthenticator#304]
Hi, I need to add AAD authentication for JupyteHub instance. 
I followed up with the instruction in readme and I'm almost there. After click on sign in with AAD I'm redirected to the Microsoft sign in page and after login there is redirect back to my jupyterhub address but on the frontend it's showing error 500 and in logs I see 401 unauthorized.

```
[E 2019-11-19 14:03:14.137 JupyterHub web:1788] Uncaught exception GET /hub/oauth_callback?code=AQABAAIAAACQN9QBRU3jT6bcBQLZNUj7q2m4Kk7ygLUlD1453RnU2M74KileUexWuK-y4kvP8iJ6aQl-WRQI6pHL7Cei3_it7TIbzX36MKnJul8hRrbBLze4Ld0aQw-mqR
    HTTPServerRequest(protocol='https', host='mydomain.com', method='GET', uri='/hub/oauth_callback?code=AQABAAIAAACQN9QBRU3jT6bcBQLZNUj7q2m4Kk7ygLUlD1453RnU2M74KileUexWuK-y4kvP8iJ6aQl-WRQI6pHL7C
    Traceback (most recent call last):
      File "/opt/tljh/hub/lib/python3.6/site-packages/tornado/web.py", line 1699, in _execute
        result = await result
      File "/opt/tljh/hub/lib/python3.6/site-packages/oauthenticator/oauth2.py", line 209, in get
        user = yield self.login_user()
      File "/opt/tljh/hub/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 655, in login_user
        authenticated = await self.authenticate(data)
      File "/opt/tljh/hub/lib/python3.6/site-packages/jupyterhub/auth.py", line 383, in get_authenticated_user
        authenticated = await maybe_future(self.authenticate(handler, data))
      File "/opt/tljh/hub/lib/python3.6/site-packages/oauthenticator/azuread.py", line 96, in authenticate
        resp = yield http_client.fetch(req)
    tornado.httpclient.HTTPClientError: HTTP 401: Unauthorized

```

**Comment by konradsitarz** [comment]
Ahh it was stupid error when copying values for authentication.
I was able to debugg it using requests inside this package and manually check what was wrong in the request text. It would be great if error was more descriptive than only 401 unauthorized.

Closing since it's not the error of the lib.

**Comment by manics** [comment]
@konradsitarz Great that you've figured it out! If you've got any concrete ideas for how to improve the error logs, or how to improve the docs to describe your debugging steps, please feel free to open a PR.
