### ISSUE TITLE
Keycloak settings

### ISSUE THREAD

**Issue by pixie79** [jupyterhub/oauthenticator#306]
Hi,

Does anyone have an example config for using this against keycloak within a jupyter lab notebook?

Thanks

Mark

**Comment by manics** [comment]
`oauthenticator` is used to provide OAuth authentication to JupyterHub. It doesn't interact directly with Jupyter Notebook or Jupyterlab, though it can be configured to pass some state parameters in the environment (e.g. username). What are you trying to do?
