### ISSUE TITLE
Missing tests for Azure AD B2C

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/oauthenticator#309]
It would be great to have some tests for all authenticators, and we currently lack it for the new Azure AD B2C Authenticator.

https://github.com/jupyterhub/oauthenticator/pull/307

**Comment by linkcd** [comment]
Looking at other test cases for Azure AD https://github.com/jupyterhub/oauthenticator/blob/master/oauthenticator/tests/test_azuread.py

Looks like this test is only testing assigning env variable and read it from the instance. it is not actually tested against AAD. 

Is this type of test needed for AAD B2C (only test env variables set/get), or we really need to test with a working AAD B2C tenant?

**Comment by consideRatio** [comment]
To test as realistically as possible is nice of course, there is currently a low standard though for the azuread authenticator :/

**Comment by consideRatio** [comment]
They do serve real value, both for the maintainers of this repo and for the users of the software. I recently helped fix a issue with mediawiki authenticator thanks to the availabe test, those also solved an issue with the upstream python client mwauth!

**Comment by shivan10** [comment]
I'm currently using Azure AD Authentication and I'm able to generate a code using my client id and secret. But I end up with a screen saying 500 internal server error. Checking docker logs shows me an HTTP error code of 401. Has anyone faced a similar issue? How did you get around it?

**Comment by consideRatio** [comment]
@shivan10 please open up a new issue with that, also provide a copy paste of relevant logs if you got it

**Comment by consideRatio** [comment]
This authenticator was removed in 0.11.0 as it could be implemented with the generic authenticator instead.
