### ISSUE TITLE
When to define a custom authenticator?

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/oauthenticator#313]
There will be almost infinite amounts of authenticators in this repo if we make a custom class for all of them. With this in mind, when should we make a new module in this repo with a class for a custom authenticator, and when shouldn't we? Getting a clear answer on that, and then documenting it would be nice.

**Comment by manics** [comment]
Could we encourage all new authenticators to be in a separate package with `oauthenticator` as a dependency? It means ensuring breaking changes aren't made to the core classes, and perhaps improving the docs?

**Comment by minrk** [comment]
I think this is a really hard decision to make. If I had my choice, we would probably only have major repo hosts (GitHub, Bitbucket, GitLab) and Google here. But kicking any out would mean creating and maintaining separate packages for the ones we have, which is *more* work than keeping them here. At this point, it's hard to draw a line anywhere other than who got here first.

I think the only feasible course is @manics idea that we stop here and say "oauthenticator is not accepting new providers, here are the docs for writing your own." That also means the work of making a stable public API for writing new OAuthenticator subclasses in external packages, which we don't have right now.

**Comment by minrk** [comment]
opened #316 to start this. It's very rough for now, but gets things started with the right places to write these docs.
