### ISSUE TITLE
Environment Variable from get_auth_state() not passed into user environment on Spawning

### ISSUE THREAD

**Issue by eosantigen** [jupyterhub/oauthenticator#314]
I have followed the step from the official documentation [here](https://jupyterhub.readthedocs.io/en/stable/reference/authenticators.html#authentication-state) in order to inject the value of the 'access_token' into an environment variable that will be available inside each user's notebook/shell.

I have added the snippet:

```
    @gen.coroutine
    def pre_spawn_start(self, user, spawner):
        auth_state = yield user.get_auth_state()
        if not auth_state:
            print("AUTH_STATE NOT ENABLED?")
            return
        spawner.environment['TEST'] = auth_state['access_token']
```
inside the _oauthenticator/generic.py_  class right under the _authenticate_ method.

The _authenticate_ method returns :

```
        return {
            'name': resp_json['content'][0]['userName'],
            'auth_state': {
                'access_token': access_token,
                'refresh_token': refresh_token,
                'oauth_user': resp_json,
                'scope': scope,
            }
        }
```

And of course, have the relevant setting: 
```c.LocalGenericOAuthenticator.enable_auth_state = True```

Still, the environment variable does not even show in a user's terminal either as empty or as expected with the certain value .

Also, I have tested likewise:

```
    @gen.coroutine
    def pre_spawn_start(self, user, spawner):
        auth_state = yield user.get_auth_state()
        if not auth_state:
            print("AUTH_STATE NOT ENABLED?")
            return
        spawner.environment['TEST'] = 'lol'
        spawner.Spawner.environment= {'TEST': 'lol'}
```
Which also does not work!

What am I missing?

(note : I'm using the **tljh** but I guess it makes no difference)

Kind Regards

**Comment by manics** [comment]
How did you set `JUPYTERHUB_CRYPT_KEY`?

**Comment by eosantigen** [comment]
I didn't set it anywhere ....

**Comment by manics** [comment]
TLJH uses systemd: https://github.com/jupyterhub/the-littlest-jupyterhub/blob/master/tljh/systemd-units/jupyterhub.service#L17

I don't know if it's possible to set the equivalent of `JUPYTERHUB_CRYPT_KEY` in the config file. If it's not you'll need to add the environment variable to the systemd service file

**Comment by eosantigen** [comment]
ok. I passed it on systemd [service] definition. However, I don't think that's where the problem may lie. I didn't have a KEY before and the state loaded as normal . (as seen on logs)

**Comment by eosantigen** [comment]
I have changed to the default JupyterHub (not using the tljh anymore) and the snippet that fetches the data from the state still doesn't work. Still same result.

**Comment by eosantigen** [comment]
I confirm this has been RESOLVED now. :) I had forgotten to terminate the tljh process so it was somehow picking up the old SystemdSpawner, so after it got terminated and I switched to the original JupyterHub all works as expected. Thank you @manics for the hint , it helped me indeed to resolve this.
