### ISSUE TITLE
Using AWSCognito and unable to get environment for DOMAIN

### ISSUE THREAD

**Issue by budgester** [jupyterhub/oauthenticator#315]
So i'm using TLJH

Running the config

```
root@ip-172-*.*.*:/home/ubuntu# tljh-config show
users:
  admin:
  - insightadmin
auth:
  type: oauthenticator.awscognito.AWSCognitoAuthenticator
```

With this config..
```
root@ip-172.*.*.*:/home/ubuntu# cat /opt/tljh/config/jupyterhub_config.d/awscognito.py
c.AWSCognitoAuthenticator.client_id=‘********’
c.AWSCognitoAuthenticator.client_secret=‘********’
c.AWSCognitoAuthenticator.oauth_callback_url='https://myhub/hub/oauth_callback'
c.AWSCognitoAuthenticator.username_key='username'
c.AWSCognitoAuthenticator.oauth_logout_redirect_url='https://myhub/hub/logout
```

```
root@ip-172-*.*.*:/home/ubuntu# printenv | grep AWS
AWSCOGNITO_DOMAIN=myhub.auth.eu-west-1.amazoncognito.com
```
When I hit the site, it doesn't pick up the environment variable and I get

https://none/oauth2/authorize?response_type=code&redirect_uri=

If I hard code the url into

https://github.com/jupyterhub/oauthenticator/blob/master/oauthenticator/awscognito.py#L53

i.e. change
```
AWSCOGNITO_DOMAIN = os.getenv('AWSCOGNITO_DOMAIN')
```
to
```
AWSCOGNITO_DOMAIN = 'myhub.auth.eu-west-1.amazoncognito.com'
```
It works fine, where am I missing setting the environment variable ? 

I've tried it in /etc/environment and running 
```
export AWSCOGNITO_DOMAIN=myhub.auth.eu-west-1.amazoncognito.com'
```
 all to no avail..

And testing it in python gives

```
root@ip-172-*.*.*:/home/ubuntu# python3
Python 3.6.9 (default, Nov  7 2019, 10:44:02)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> print(os.getenv('AWSCOGNITO_DOMAIN'))
myhub.auth.eu-west-1.amazoncognito.com
```

Any help would be great.

**Comment by manics** [comment]
TLJH uses systemd so the environment needs to be set in the service file, see these related issues:
- https://github.com/jupyterhub/oauthenticator/issues/314
- https://github.com/jupyterhub/the-littlest-jupyterhub/issues/470

**Comment by budgester** [comment]
What would it take to be able to configure it the same manner as all the other configuration on this authenticatior.

e.g.

c.AWSCognitoAuthenticator.awscognito_domain='myhub.auth.eu-west-1.amazoncognito.com

**Comment by manics** [comment]
This parameter is used as some class attributes, so it's not straightforward to set them dynamically:
https://github.com/jupyterhub/oauthenticator/blob/3d7840da11a5e0b4af9e38e3045eb10b6e2bc2a7/oauthenticator/awscognito.py#L57-L58
These are defined in the parent `tornado.aiuth.OAuth2Mixin` class

> If I hard code the url into
> https://github.com/jupyterhub/oauthenticator/blob/master/oauthenticator/awscognito.py#L53

You might be able to do the equivalent of this in your config file by subclassing the authenticator, e.g. something along the lines of (note I haven't tested this):
```python
from tornado.auth import OAuth2Mixin
from oauthenticator.oauth2 import OAuthLoginHandler, OAuthenticator

AWSCOGNITO_DOMAIN = 'my.aws.domain.example.org'

class MyAWSCognitoMixin(OAuth2Mixin):
    _OAUTH_AUTHORIZE_URL = "https://%s/oauth2/authorize" % AWSCOGNITO_DOMAIN
    _OAUTH_ACCESS_TOKEN_URL = "https://%s/oauth2/token" % AWSCOGNITO_DOMAIN

class MyAWSCognitoLoginHandler(OAuthLoginHandler, MyAWSCognitoMixin):
    pass

class MyAWSCognitoAuthenticator(oauthenticator.awscognito.AWSCognitoAuthenticator):

    login_service = 'MyAWSCognito'
    login_handler = MyAWSCognitoLoginHandler

    oidc_userdata_url = "https://%s/oauth2/userInfo" % AWSCOGNITO_DOMAIN
    oidc_token_url = "https://%s/oauth2/token" % AWSCOGNITO_DOMAIN
    oidc_logout_url = "https://%s/logout" % AWSCOGNITO_DOMAIN
```
```
auth:
  type: MyAWSCognitoAuthenticator
```
If you figure out a way to make it configurable please open a PR!

**Comment by budgester** [comment]
I've not figured out a way yet, but here is a terraform template I've used to configure an EC2 instance userdata with tljh, in case it's of any use to someone, so this could 

```
#!/bin/bash

##############################################
# Setup systemd environment variable overrides
##############################################
mkdir /etc/systemd/system/jupyterhub.service.d

echo "[Service]
Environment=AWSCOGNITO_DOMAIN=${awscognito_domain}" >> /etc/systemd/system/jupyterhub.service.d/jupyterhub.conf

##############################################
# Need to ensure oauthenticator is bumped to 0.10.0
##############################################
curl https://raw.githubusercontent.com/jupyterhub/the-littlest-jupyterhub/master/bootstrap/bootstrap.py \
  | sudo python3 - \
    --admin insightadmin

##############################################
# Setup aws Cognito Authenticator 
##############################################
echo "c.AWSCognitoAuthenticator.client_id='${client_id}'
c.AWSCognitoAuthenticator.client_secret='${client_secret}'
c.AWSCognitoAuthenticator.oauth_callback_url='${callback_url}'
c.AWSCognitoAuthenticator.username_key='username'
c.AWSCognitoAuthenticator.oauth_logout_redirect_url='${logout_url}'" >> /opt/tljh/config/jupyterhub_config.d/awscognito.py


tljh-config set auth.type oauthenticator.awscognito.AWSCognitoAuthenticator

tljh-config reload

```

**Comment by manics** [comment]
@budgester Thanks for sharing your solution!
There's a related issue for making this more configurable: https://github.com/jupyterhub/oauthenticator/issues/312

In the meantime are you interested in sharing this solution, either by adding to TLJH docs, or as a [`How to`](https://discourse.jupyter.org/tags/how-to) post on https://discourse.jupyter.org/ ?

**Comment by budgester** [comment]
I'll create a howto on TLJH docs over the next couple of days.

**Comment by budgester** [comment]
https://github.com/jupyterhub/the-littlest-jupyterhub/pull/472
