### ISSUE TITLE
Would like to have a proper way to configure AAD environment

### ISSUE THREAD

**Issue by sidneyli** [jupyterhub/oauthenticator#317]
I tried to build a jupyter hub with helm over kubernetes that can be authenticated with aad. However I am currently working with an azure cloud environment other than the common global service, and the aad authenticator hard coded the endpoint uri and there is no easy way to modify it, or is there? 

A [link](https://docs.microsoft.com/en-us/azure/active-directory/develop/authentication-national-cloud#azure-ad-authentication-endpoints) to azure endpoints for different environments.

It would be really sweet if those options can be listed/configured from the helm config.yaml.

**Comment by manics** [comment]
The `AzureAdB2COAuthenticator` was recently added which support more configuratoin: https://github.com/jupyterhub/oauthenticator/pull/307
Is that any use?

**Comment by sidneyli** [comment]
I took a look before but found the logic is kind of different. But I will give it a shot and come back update this feed.

**Comment by sidneyli** [comment]
@manics 
Seems like the feature is too young to be included to the official docker image. I will try again sometimes later this week. 
I have little experience over B2C but I do have doubts since the link you provided reads  **MS have different roadmap for AAD and AAD B2C as they are two separated products** and the endpoint used is different.
@linkcd Maybe can provide some insights?

**Comment by linkcd** [comment]
@sidneyli 
**Regarding AAD vs AAD B2C**
AAD and AAD B2C are different in many ways, such as pricing, possibilities of customization, etc. We (veracity.com) actually working closely with microsoft team on this regarding roadmap (cannot share them now as they are under NDA)

Anyway, here is a news from 2 days ago https://azure.microsoft.com/en-us/updates/b2c-deprecate-msol/ shows that B2C is moving to its own endpoint domains. 

**Regarding your need**
I believe you can reuse the https://github.com/jupyterhub/oauthenticator/pull/307 as it basically provide a way for more flexible way for defining endpoints.

**Comment by sidneyli** [comment]
@linkcd Thanks a lot for the info.
I am aware I can always repack the whole project with what I need. Just proposing a more generic solution for others. 
Maybe I can create a MR and let the maintainers decide if to take it in.

**Comment by manics** [comment]
I'm closing this as it's quite old and there's no concrete action point. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/) or open a new issue. Thanks!
