### ISSUE TITLE
Problem with authentication:

### ISSUE THREAD

**Issue by kenenbek** [jupyterhub/oauthenticator#324]
1. I am in the following [folder](https://github.com/jupyterhub/oauthenticator/tree/master/examples/full)
2. Generated `ssl.key` and `ssl.cert`
3. Added me as admin to `userlist`
4. `docker build -t jupyterhub-oauth .`
5. `docker run -it -p 8000:8000 --env-file=env jupyterhub-oauth`

After running the service I have the following page.

![image](https://user-images.githubusercontent.com/15985969/71191532-a745d880-2297-11ea-8f23-d2f38c2d3e61.png)

`302 GET /hub/oauth_login?next= -> https://github.com/login/oauth/authorize?response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A9999%2Fhub%2Foauth_callback&client_id=&state=[secret] (@127.0.0.1) 2.11ms`

Everything seems OK. But when I hit the button I have an error:

![image](https://user-images.githubusercontent.com/15985969/71191635-e2480c00-2297-11ea-92a0-64259f96a866.png)
How can I overcome it?

**Comment by manics** [comment]
Did you follow the README instructions to 
> Add your oauth client id, client secret, and callback URL to the env file

**Comment by kenenbek** [comment]
@manics Yes, I missed them. Thank you. 
Can I ask? Is this a correct form for callback? 
OAUTH_CALLBACK_URL=https://localhost:9999/hub/oauth_callback

**Comment by manics** [comment]
That looks right
