### ISSUE TITLE
Forwarding Cognito Identity to Boto3

### ISSUE THREAD

**Issue by aidan-plenert-macdonald** [jupyterhub/oauthenticator#327]
Using boto3, I can get AWS Credentials for a Cognito authentication (see [example](https://stackoverflow.com/questions/28989054/amazon-aws-cognito-and-python-boto3-to-establish-aws-connection-and-upload-file)) like,

```
client = boto3.client('cognito-identity','us-east-1')
id_resp =  client.get_id(AccountId='<ACCNTID>',IdentityPoolId='<IDPOOLID>')
cred_resp = client.get_credentials_for_identity(IdentityId=id_resp['IdentityId'])
secret_key = cred_resp['Credentials']['SecretKey']
access_key = cred_resp['Credentials']['AccessKeyId']
```

In this way, I could forward my JupyterHub OAuth creds to Boto3 to make Cognito based requests. I just need to get at either `IdentityPoolId` or `IdentityId`. Looking at the Env Vars exported in the JupyterHub Notebook,

```
['PATH',
 'LANG',
 'JUPYTERHUB_API_TOKEN',
 'JPY_API_TOKEN',
 'JUPYTERHUB_CLIENT_ID',
 'JUPYTERHUB_HOST',
 'JUPYTERHUB_OAUTH_CALLBACK_URL',
 'JUPYTERHUB_USER',
 'JUPYTERHUB_SERVER_NAME',
 'JUPYTERHUB_API_URL',
 'JUPYTERHUB_ACTIVITY_URL',
 'JUPYTERHUB_BASE_URL',
 'JUPYTERHUB_SERVICE_PREFIX',
 'USER',
 'HOME',
 'SHELL',
 'KERNEL_LAUNCH_TIMEOUT',
 'JPY_PARENT_PID',
 'TERM',
 'CLICOLOR',
 'PAGER',
 'GIT_PAGER',
 'MPLBACKEND']
```

Are any of these managed by JupyterHub to be the needed Cognito Id's?

**Comment by aidan-plenert-macdonald** [comment]
Looks like we could get it by making a change like [mentioned here](https://github.com/jupyterhub/oauthenticator/issues/211#issuecomment-569637559)

I noticed that similar code is [here](https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/apihandlers/users.py#L137) with the comment,

```
        # auth state will only be shown if the requester is an admin
        # this means users can't see their own auth state unless they
        # are admins, Hub admins often are also marked as admins so they
        # will see their auth state but normal users won't
        requester = self.current_user
        if requester.admin:
            model['auth_state'] = await user.get_auth_state()
        self.write(json.dumps(model))
```

Just curious. What is the harm in allowing users to view their own credentials?

**Comment by manics** [comment]
I'm not an expect on Oauth2 but I found this:
https://www.oauth.com/oauth2-servers/access-tokens/

The access token is gives an _application_ permission to interact with a resource on behalf of the user, and it's assumed the application is secure. If a user can access their token then can take any action that's within the scope of the token but your application will be held responsible.

**Comment by aidan-plenert-macdonald** [comment]
@manics Interesting. I have a  jupyter notebook extension that needs user identity in order to access secured APIs. I agree with your statement, so what is the recommended way to create an API that has secure identities?

Looks like the only way is to use [GET /authorizations/token/{token}](https://jupyterhub.readthedocs.io/en/stable/_static/rest-api/index.html#path--authorizations-token--token-) to validate the user, and use the token to make all the requests.

**Comment by manics** [comment]
If you trust your user's you can pass auth state as an environment variable if you're using a spawner that supports it. See https://github.com/jupyterhub/jupyterhub/blob/1.1.0b1/docs/source/reference/authenticators.md#using-auth_state

Note you can subclass the Authenticator in-line in the jupyter config.

**Comment by aidan-plenert-macdonald** [comment]
How does this work with tokens that have an expiration? I've read some posts in Github that say they have trouble with expiring tokens

**Comment by manics** [comment]
I'm afraid I don't know, maybe someone else can help?

**Comment by NickolausDS** [comment]
One cheap and easy way to fix that problem is by setting the Jupyter cookie lifetime to something less than the lifetime of the tokens. This doesn't solve that problem, but can make sure `pre_spawn_start` doesn't launch a notebook with expired tokens:

```
c.JupyterHub.tornado_settings = {'cookie_options': {'expires_days': 1}}
```
However, this doesn't account for tokens expiring while the notebook is running. Refresh tokens are another option if you want to guarantee tokens stay live within a notebook (and the provider supports them). However, refresh tokens can last a very long time, and that imposes a security risk if the service were to ever experience a breach.

**Comment by manics** [comment]
I'm closing this as it's quite old and there's no concrete action point. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/) or open a new issue. Thanks!
