### ISSUE TITLE
Live integration tests against external OAuth providers

### ISSUE THREAD

**Issue by manics** [jupyterhub/oauthenticator#329]
This repo mocks most external OAuth providers since they require secret tokens. Travis secrets aren't available for testing PRs, but they could be used to test `master` after a PR is merged, and all tags.

This would hopefully pick up issues such as https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1551 immediately, and will also provide notice if for some reason an external provider changes it's OAuth configuration.

**Comment by minrk** [comment]
Testing OAuth is super hard, since we not only need credentials registering our test environment, but we also need credentials for users logging in. I'm not sure we can do anything realistic here.

**Comment by manics** [comment]
You're right :-(. Maybe we could make local manual testing a bit easier though? e.g.
- A mini web-app with login buttons for each of the OAuthenticators that calls `authenticate`. the client ID and secret can be loaded from a config file. Manual testing consists of clicking each of the login buttons in turn.

This still requires testers to have a client ID, secret, and login for testing, but the setup is a lot easier than configuring a full JupyterHub deployment.

**Comment by vindvaki** [comment]
GitLab provides [docker images](https://docs.gitlab.com/omnibus/docker/) that might be usable for pretty realistic integration tests.

**Comment by manics** [comment]
I was about to close this as impractical, but an alternative testing idea came to mind: how about if we have a list of (possibly external) reviewers for each Authenticator who use it? If a change is made to an Authenticator it should ideally (though not mandatory) be approved by one of those reviewers before merging.

**Comment by manics** [comment]
Closing as there's no concrete action
