### ISSUE TITLE
Update repos README.md - links failing etc.

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/oauthenticator#332]
The README for the repo has become outdated, and links are failing.

I'd like to see us have:
- nice badges from team-compass
- a good intro to what this project is, and how it fits into the JupyterHub ecosystem of repos.
- install section (that also describes where it should be installed: next to jupyterhub)
- some quick onboarding on what OAuth is
- general notes on how to configure it, and specific examples.

**Comment by rpwagner** [comment]
@NickolausDS can you watch this issue, since it's looks like the docs are being updated and maybe [moved to individual pages](https://github.com/jupyterhub/oauthenticator/tree/master/docs/source)? We may need to contribute to that for our plugin.

**Comment by NickolausDS** [comment]
Yes, I'd be happy to.

**Comment by dmpe** [comment]
It would be also nice to have automatic builds for docs from this repository, with a link!
https://jupyterhub.readthedocs.io/en/stable/reference/authenticators.html is only partially helpful.
