### ISSUE TITLE
OAuthenticator based on gitlab

### ISSUE THREAD

**Issue by devopsdymyr** [jupyterhub/oauthenticator#342]
can anyone give me how to congifure gitlab authenticator for my jupyterhub which is deployed on kubernetes cluster

Jupyterhub created by using helm

https://zero-to-jupyterhub.readthedocs.io/en/latest/setup-jupyterhub/setup-helm.html

I have tested with github which is working fine but tried to use gitlab facing issue

**Comment by iampatterson** [comment]
I am using an identical environment.  Can you kindly share the config for GitHub, I can't get mine to work.  I followed the instructions explicitly.  I get a 404 like this.  I think it is a problem with the home pages or the callback URL's not sure what else to try.   


This is the only thing I have in my config.yaml 

 type: github
  github:
    clientId: "XXXX"
    clientSecret: "XXXXXXX"
    callbackUrl: "http://XX.XX.XX.XX/hub/home/oauth_callback"


jupyterhub_config.py

from oauthenticator.github import GitHubOAuthenticator
c.JupyterHub.authenticator_class = GitHubOAuthenticator

c.GitHubOAuthenticator.oauth_callback_url = 'http://XX.XX.XX.XX/hub/home/oauth_callback'
c.GitHubOAuthenticator.client_id = 'XXXX'
c.GitHubOAuthenticator.client_secret = 'XXXXXXXXX"

Git tokens match 

Git Oath config

Home
http://XX.XX.XX.XX/hub/home

Callback URL 
http://XX.XX.XX.XX/hub/home/oauth_callback


![image](https://user-images.githubusercontent.com/47332351/82856425-c7bb3400-9ec2-11ea-8f1d-1490d1ee3dd3.png)

**Comment by manics** [comment]
Hi :wave: This sounds like a configuration problem rather than a bug. Do you mind posting this as a support question on https://discourse.jupyter.org/ instead? Thanks!
