### ISSUE TITLE
Last RTD build was 2 months ago

### ISSUE THREAD

**Issue by GeorgianaElena** [jupyterhub/oauthenticator#347]
The latest oauthenticator changes didn't trigger a RTD build (the RTD page shows the last oauthenticator build was 2 months ago: https://readthedocs.org/projects/oauthenticator/builds/)

I'm not sure if it's related to https://github.com/jupyterhub/jupyterhub/issues/2427 or if it's something else.

**Comment by consideRatio** [comment]
@GeorgianaElena nice catch, I also think it is related to https://github.com/jupyterhub/jupyterhub/issues/2427.

I looked through all of the repositories under the JupyterHub org, and checked their associated RTD build configuration for those that had it. [This view](https://readthedocs.org/dashboard/import/?) on RTD allowed me to do so.

## Status: web hooks configured

These instructions (https://github.com/jupyterhub/jupyterhub/issues/2427) have been applied to the following RTD configurations by a maintainer of the RTD project.

- [x] jupyterhub/binder
- [x] jupyterhub/binderhub
- [x] jupyterhub/jupyterhub
- [x] jupyterhub/kubespawner
- [x] jupyterhub/mybinder.org-deploy
- [x] jupyterhub/nbserverproxy
- [ ] jupyterhub/oauthenticator
- [x] jupyterhub/team-compass
- [x] jupyterhub/the-littlest-jupyterhub
- [x] jupyterhub/zero-to-jupyterhub-k8s

## Status: maintainers
- binder (betatim choldgraf)
- binderhub (yuvipanda willingc minrk choldgraf)
- jupyterhub (takluyver Carreau willingc minrk ellisonbg GeorgianaElena)
- kubespawner (yuvipanda willingc choldgraf consideRatio minrk GeorgianaElena betatim manics)
- mybinder.org-deploy (Carreau yuvipanda willingc minrk betatim mdpacer choldgraf jzf2101 mpacer)
- nbserverproxy (jupyter-server-proxy) (yuvipanda)
- oauthenticator (minrk)
- team-compass (yuvipanda willingc minrk betatim choldgraf)
- the-littlest-jupyterhub (yuvipanda willingc minrk betatim choldgraf)
- zero-to-jupyterhub-k8s (yuvipanda willingc minrk betatim choldgraf consideRatio manics)

Let's add some additional maintainers, at least to ensure we don't end up being individually responsible for maintenance.
- @yuvipanda could you add more maintainers to jupyter-server-proxy?
- @minrk could you add more maintainers to oauthenticator?

**Comment by yuvipanda** [comment]
@consideRatio thanks for doing this check! I have added you, @choldgraf, @minrk and @GeorgianaElena to the RTD build.

**Comment by consideRatio** [comment]
@minrk could you add me and some others in the JupyterHub team as maintainers of the RTD project coupled with this repo at https://readthedocs.org/projects/oauthenticator/ in order to help us share the maintenance burden better?

**Comment by consideRatio** [comment]
Thank you @minrk for adding me as a maintainer! The RTD build for this repo now functions as it should!
