### ISSUE TITLE
[AzureAD] Subclassed authenticator fails to be configured

### ISSUE THREAD

**Issue by hewittwill** [jupyterhub/oauthenticator#351]
### Bug description
Trying to use the `AzureAdOAuthenticator` for our JupyterHub setup. When I hit the 'Login using AzureAD' button, it takes us to a dead link:

`https://login.microsoftonline.com//oauth2/authorize?***`

As you can see it has a double slash and is missing the word 'common' between the .com and oauth2 

I tried a hundred different combinations and can not get it to change. 

Config Files:

```
import os

from oauthenticator.azuread import LocalAzureAdOAuthenticator, AzureAdOAuthenticator
from traitlets import Unicode, default

# Set where the user starts
c.Spawner.notebook_dir = "~/jupyterhub_notebooks"
c.Spawner.default_url = '/notebooks/Welcome.ipynb'

class HeartLabAzureAdOAuthenticator(LocalAzureAdOAuthenticator):

	def normalize_username(self, username):
		return username.lower().replace(' ', '_')


c.JupyterHub.authenticator_class = HeartLabAzureAdOAuthenticator

c.HeartLabAzureAdOAuthenticator.tenant_id = 'XXX'

c.Application.log_level = 'DEBUG'

c.HeartLabAzureAdOAuthenticator.oauth_callback_url = 'https://our_jupyterhub_url.com/hub/oauth_callback'
c.HeartLabAzureAdOAuthenticator.client_id = 'XXX'
c.HeartLabAzureAdOAuthenticator.client_secret = 'XXX'
c.HeartLabAzureAdOAuthenticator.create_system_users = True
```

also this in the tljh config yaml file. The test.com was to see if I could force a change. 

```
auth:
  HeartLabAzureAdOAuthenticator:
    token_url: test.com
    authorize_url: test.com
```

**Comment by consideRatio** [comment]
I think you need to configure the `tenant_id`.

See the code here:
https://github.com/jupyterhub/oauthenticator/blob/397a3ec6b489635ceb70cfd40059d8ee55bddd6d/oauthenticator/azuread.py#L28-L46

And the documentation here:
https://oauthenticator.readthedocs.io/en/latest/getting-started.html#azure-ad-setup
