### ISSUE TITLE
[Generic] Refactoring the authenticate function to make it easier to replace parts of it

### ISSUE THREAD

**Issue by mhaley-miovision** [jupyterhub/oauthenticator#353]
### Proposed change

Hello, I have recently setup Jupyterlab using the generic oauth authenticator and AWS Cognito.  Everything works exactly as expected, and it was quite easy to get going, which was really nice.  My next step was to get the idtoken that cognito returns that you need to request temporary AWS credentials exposed inside the user's workspace some how.  The problem is that both the old [aws cognito authenticator](https://github.com/jupyterhub/oauthenticator/blob/0.10.0/oauthenticator/awscognito.py) and the [generic authenticator](https://github.com/jupyterhub/oauthenticator/blob/master/oauthenticator/generic.py#L150) (which I was using) do not return the idtoken as authentication state.  To get around this I basically had to copy the authenticate method from the generic authenticator in a subclass just to get one extra value out of the response.  Once I was able to get the actual idtoken into the user's auth_state I overrode the pre-spawn and a post-spawn methods to create a k8s secret with that value to feed it into the container for use inside a user's environment.  What are people's thoughts for extracting additional information from the token response of the oauth2 workflow?  This seems like alot of work and effort to get one extra value.

Other Relates Issues:
https://github.com/jupyterhub/oauthenticator/issues/327

### Alternative options

For a bit I considered creating an extension in Jupyterhub (so inside the user's workspace) to run the authentication flow and setup all the user's personal secrets, but this route would be more annoying for the user and end up being harder to maintain moving forward.

### Who would use this feature?

Anyone looking to use AWS cognito with jupyterlab on AWS and wants to provide user specific AWS credentials inside of notebooks.

### (Optional): Suggest a solution

I see these two options:
1. Bring back the AWSCognito specific authenticator that saves the extra cognito specific information, such as the idtoken, inside the user's auth_state so it is easily accessible.
2. Split up the single authentication method that does multiple steps into smaller functions and provide additional hooks into the authentication flow so that people can inject themselves more easily into the flow with simple configuration.  This would make subclassing the generic authenticator easier, or not even needed in most cases.

**Comment by manics** [comment]
The main reason we're not adding more authenticators to this repository is maintainability. The problem with OAuth is it's almost impossible to automate the testing. This means it's a large manual burden on the current maintainers, and it's made even harder by needing to acquire accounts and tokens for testing.

If you think a new AWSCognito authenticator is best it should be fairly easy to publish your own python package, this is how the majority of JupyterHub Authenticators (and Spawners) are managed. If you're not familiar with Python packaging https://github.com/jupyterhub/dummyauthenticator is a simple example of overriding just `authenticate`.

If you think this functionality is useful in the Generic Authenticator, or if splitting up methods would help with developing other authenticators, it may make sense to make some changes here. Do you have a link to your code, so we can have an idea of what's needed?

**Comment by mhaley-miovision** [comment]
Yeah, that makes sense.  I think that the pieces of the authentication flow can be better broken up though so that maintaining an extra authenticator isn't such a burden. These are the additional hooks I was referring to and also breaking up the main authenticate function into smaller functions that could possibly be overwritten in a subclass instead of each authenticator having to manage the entire flow themselves.

For testing, in other projects I have worked with such as https://github.com/terraform-providers/terraform-provider-datadog, they use what is called a cassette. Essentially, the first time you setup a test you need to do it for real, but all of the api calls from the remote system are recorded and saved as a "cassette".  On future tests, instead of connecting to the remote backend, you can just play the cassette, and the test then becomes self contained.

**Comment by manics** [comment]
Hi @mhaley-miovision Do you have any more details on how the authenticate method could be broken up to make it easier for you?

I think we're pretty set on not adding more providers due to the testing burden. Although recording and replay frameworks exist they don't help if providers update their services, there are already a couple of open issues regarding changes to AD.

**Comment by mhaley-miovision** [comment]
Hi @manics,

Here is a [diff of the 0.8.0](https://www.diffchecker.com/3YeSNjgF) code that we are using today verse what is in the actual authenticate method.  As you can see, we only make two important changes.  The first is storing the entire json response from the oauth request, and the second is putting that full response in the auth state.  This lets us pull out the `id_token` later on using a `pre_spawn_start` routine and provide it to the kubernetes pod via a secret.

The original 0.8.0 authenticate method is around 80 lines long.  It should be a pretty simple exercise to pull apart the various parts of that function into helper methods.  This has numerous benefits:

1. Easier to maintain
2. Easier to test
3. More flexible for users to override specific functionality when needed

You can see a quick example of this here https://github.com/jupyterhub/oauthenticator/pull/374.
