### ISSUE TITLE
AzureAD authenticates with name instead of UPN

### ISSUE THREAD

**Issue by serant** [jupyterhub/oauthenticator#355]
### Bug description

If two Azure Active Directory users with the same name, but different emails (UPNs) exist, they were will map to the same JupyterHub account when using AzureAdOAuthenticator

#### Expected behaviour
If I have two Azure AD accounts:
1. Seran Thirugnanam with email: seranthirugnanam@mydomain.com
2. Seran Thirugnanam with email: sthirugnanam@mydomain.com

They should map to different accounts on JupyterHub when using AzureAdOAuthenticator.

#### Actual behaviour

The two accounts map to the same account on JupyterHub

### How to reproduce
1. Create two accounts in Azure AD with the same "name" field, but different email fields (or UPNs)
2. Sign in with AD using AzureAdOAuthenticator on JupyterHub using the first account
3. Create a notebook using the first account
4. Sign in with AD using AzureAdOAuthenticator using the second account
5. You will see the notebook of the first account

### Your personal set up
 - OS: Ubuntu 18.04
 - Version: Jupyterhub 1.1.0
 
 - Configuration:
My `jupyter_config.py`
```
c.JupyterHub.authenticator_class = AzureAdOAuthenticator
c.AzureAdOAuthenticator.tenant_id = <AAD_TENANT_ID>
c.AzureAdOAuthenticator.oauth_callback_url = <callback_url>
c.AzureAdOAuthenticator.client_id = <client_id>
c.AzureAdOAuthenticator.client_secret = <client_secret>
```

**Comment by serant** [comment]
If this is something that should be addressed, I can submit a PR with my changes. 

Some guidance on how to handle migrating deployments using "name" as the key for AzureAdOAuthenticator to a UPN as the key will be appreciated.

**Comment by yuvipanda** [comment]
https://github.com/jupyterhub/oauthenticator/pull/280 might help you?

**Comment by consideRatio** [comment]
Closing this preliminary given #280 is merged and released.
