### ISSUE TITLE
Release schedule?

### ISSUE THREAD

**Issue by dwilliams782** [jupyterhub/oauthenticator#356]
Hi,

We are using this via the Z2JH project, which is tagged at 0.11.0 for Oauthenticator.

I am keen to use the google group integration merged in #341 back in March. Is there a schedule for a new release?

Thanks

**Comment by ntdef** [comment]
Hi 👋 ! Jumping in as well to ask if there's a release scheduled. There are a lot of important Google OAuth changes in here.

**Comment by consideRatio** [comment]
There is no release schedule, but I'm looking to do a release this week to accompany the release of the JupyterHub Helm chart.
