### ISSUE TITLE
GoogleOAuthenticator AuthError

### ISSUE THREAD

**Issue by elibixby** [jupyterhub/oauthenticator#36]
When authenticating with the `GoogleOAuthenticator` I get a 500 Server error caused by the following:

```
HTTPResponse(_body=None,buffer=None,code=599,effective_url='https://accounts.google.com/o/oauth2/token',error=SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:645)')
```

Still trying to determine the root cause, but happy to get any pointers to make debugging easier.

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Thanks! :sunflower:
