### ISSUE TITLE
ModuleNotFoundError: No module named 'jwt'

### ISSUE THREAD

**Issue by devobern** [jupyterhub/oauthenticator#375]
Hello everyone,
I am trying to configure the oauthenticator for AzureAD. I have followed the instructions and also installed the package "PyJWT" via "pip3 install PyJWT", but the jupyterhub does not start anymore. In journalctl, I see the following output: 
[journalctl_output.txt](https://github.com/jupyterhub/oauthenticator/files/5394262/journalctl_output.txt)

The auth part of my tljh-config looks like the following: 

`auth:
  AzureAdOAuthenticator:
    clientId: xy
    clientSecret: xy
    callbackUrl: xy
    tenantId: xy
  type: azuread`

can anyone help me? If you need any more information please let me know. Many thanks in advance!

**Comment by consideRatio** [comment]
It looks like the environment where the authenticator run, is not able to find a module named `jwt`, and then I assume the installation failed or was in another Python environment or similar.

**Comment by mhatremahesh** [comment]
I have the same issue. @devobern did you find a solution to this problem?

**Comment by consideRatio** [comment]
When installing oauthenticator, install the extra requirements for azuread like described in https://oauthenticator.readthedocs.io/en/latest/tutorials/provider-specific-setup/providers/azuread.html, that should do the trick

**Comment by mhatremahesh** [comment]
@consideRatio thanks for your answer. If you mean `pip install "oauthenticator[azuread]"` I have already installed it. Let me know if you mean something else is missing. Thanks

**Comment by mhatremahesh** [comment]
I am able to solve this problem. OAuthenticator has dependency on PyJWT. If you install it using pip install PyJWT it will get installed in user environment and not in hub environment. After installing it in hub env using ```sudo /opt/tljh/hub/bin/python3 -m pip install PyJWT``` the installation is successful
