### ISSUE TITLE
Multiple Login Methods

### ISSUE THREAD

**Issue by Rayal** [jupyterhub/oauthenticator#380]
Hi!

I'm working on a project which requires me to have a single instance of Jupyterhub with multiple authentication methods, to offer my users a chance to choose which authentication they would like to use. Currently I'm just interested in having two: FirstUseAuthenticator and GoogleOAuthenticator.

I've tried hacking the 'login.html' screen and its corresponding python file to bolt on one authenticator to the other, clean code be damned, but to no avail.

I've also tried to make a class which inherits multiple authenticators, but the result doesn't actually work, due to [how python handles multiple inheritances](https://docs.python.org/3/tutorial/classes.html#multiple-inheritance).

### Proposed change

Creation of an authenticator class which allows the admin to configure multiple authentication methods.

### Alternative options

Someone give some insight on how to hack the existing authenticators to achieve a similar result.

### Who would use this feature?

Allowing for multiple authentication methods will grant flexibility for users and let admins grant wider access to their hubs.

### (Optional): Suggest a solution

I already mentioned multiple inheritances. I still think this is a viable solution. I'd need some more time to dig in to the authenticator codebase to offer a more detailed explanation of the possible solution.

**Comment by manics** [comment]
In general we ask that JupyterHub GitHub issues are used for bugs and relevant development discussions, with support being handled on the [community forum](https://discourse.jupyter.org/) where more people hang out, and the rest of the community can benefit from these discussions.

If you search GitHub and the forum you'll find some previous discussion on this topic. Please use the forum for any follow-up: https://discourse.jupyter.org/

Thanks for your understanding 😀.
