### ISSUE TITLE
Implement the curl_httpclient

### ISSUE THREAD

**Issue by joshlrogers** [jupyterhub/oauthenticator#385]
### Proposed change

Within the authenticate method there is a TODO to configure the curl_httpclient.  This is a proposal to implement this.

### Who would use this feature?

All users would as it appears to be more reliable.  For instance, we are no longer able to authenticate against Auth0 starting as of yesterday without having modified the auth0.py file to use the curl_httpclient.  We are assuming something has changed with how they handle HTTP requests on their end, but after having tried multiple mitigation measures the only successful one was to modify the code to implement the curl_httpclient.

### (Optional): Suggest a solution

To configure the curl_httpclient for Tornado.  I would submit a PR request myself to do this, at least against the auth0 authenticator, but I am not a Python dev and am not quite sure how the package dependency of pycurl is inserted into the flow.  I think requirements.txt but not sure of the implications there.

**Comment by manics** [comment]
The approach taken in JupyterHub is to use the curl client if it's installed:
https://github.com/jupyterhub/jupyterhub/blob/e7bc6c2ba999a43bc2465b9a128262d29cbc615c/jupyterhub/app.py#L2287-L2296

Do you think you could do the same in oauthenticator?

**Comment by joshlrogers** [comment]
@manics I do not remember whether I did or not, I'll change the code soon and report back whether it continues to work.

**Comment by joshlrogers** [comment]
@manics It does appear that simply installing pycurl works.  I removed the altered line and restarted jupyterhub and it continued working.

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/failing-to-authenticate-against-auth0-with-stream-closed-exception/6723/3
