### ISSUE TITLE
oauth-azure login's 'hang' after token is returned

### ISSUE THREAD

**Issue by jim-smith** [jupyterhub/oauthenticator#405]
I have jupyterhub set up on an azure server and working own port 22000.
I can get other authenticators to work but to make life easier for students I and am trying to get oauth-azure working.
At the moment when I try to log in it sends me through to our main systems for authentication. 
Looking at their logs it seems the login attempts are successful. 
However the process then just hangs and eventually returns a browser error saying the server can't be reached.

(I've changed the actual domain name to MYDOMAIN and the code, star and session_state in the message)

Safari can’t open the page “https://MYDOMAIN:22000/hub/oauth_callback?code=AAAAA&amp;state=BBBBBB&amp;session_state=CCCCCC” because the server where this page is located isn’t responding.</p>

Help needed please: How can I find out where the process is stalled?

Notes:
======
Our systems are set up with the callback_url set to my https://MYDOMAIN:22000
(MYDOMAIN is set to the appropriate url with a redirect to the IP address as well).

I've registered my domain and installed the certificates, and checked with different authenticators that the https part works fine.

jupyter hub is installed in /opt/jupyterhub following these instructions:
https://jupyterhub.readthedocs.io/en/stable/installation-guide-hard.html
and works with the native authenticator and the 'dummy authenticator.

it is configured to listen on port 22000 and with the azure config options hard coded using. these Ines in the jupyterhub_config.py:
c.JupyterHub.bind_url = 'https://:22000'

from oauthenticator.azuread import AzureAdOAuthenticator
c.JupyterHub.authenticator_class = AzureAdOAuthenticator

c.Application.log_level = 'DEBUG'

c.AzureAdOAuthenticator.tenant_id = 'XXXXX' #os.environ.get('AAD_TENANT_ID')
## I've hard coded this rather than exporting the environment variable outside this file
c.AzureAdOAuthenticator.oauth_callback_url = 'https://MYDOMAIN:22000/hub/oauth_callback'
c.AzureAdOAuthenticator.client_id = 'YYYYYYY' #'{AAD-APP-CLIENT_ID}'
c.AzureAdOAuthenticator.client_secret =  'ZZZZZZZ'   # '{AAD-APP-CLIENT-SECRET}'

I've tried setting the AAD_TENANT variable in the script that registers the service and also running running from the command line, prefixed by sudo and explicitly setting those three environments variables but that makes no difference.

**Comment by manics** [comment]
Hi :wave: This sounds like a configuration problem rather than a bug. Do you mind posting this as a support question on https://discourse.jupyter.org/ instead? Thanks!
