### ISSUE TITLE
[OAuth] Custom 403 error page after successful login at OAuth provider but rejection based on config

### ISSUE THREAD

**Issue by 1kastner** [jupyterhub/oauthenticator#414]
### Proposed change

Add the option to show a customized 403 error message when after a successful login at an OAuth provider the login is still rejected based on the config, e.g. the `allowed_users ` list or the `blocked_users` list.

### Alternative options

After installation, each JupyterHub administrator can tamper around with the code at https://github.com/jupyterhub/oauthenticator/blob/a4aac191c16cf6281f3d346615aefa75702b02d7/oauthenticator/oauth2.py#L226-L227

### Who would use this feature?

Especially if several JupyterHubs are deployed in one institution, users could accidentially try to login at the wrong server. This could be e.g. the case if there is one JupyterHub per course. For each course, only enrolled students of that specific course would be on the `allowed_users` list. Here, after a failed login some words could help to avoid confusion. As especially non-IT-people wouldn't be able to decypher the meaning of 403, that could result in a lot of unnecessary consultation.

### (Optional): Suggest a solution

The todo at https://github.com/jupyterhub/oauthenticator/blob/a4aac191c16cf6281f3d346615aefa75702b02d7/oauthenticator/oauth2.py#L226-L227 could be done. Similar to https://github.com/jupyterhub/jupyterhub/blob/4e7936056744cdad31d608388a349207196efa56/jupyterhub/auth.py#L180-L186, in the JupyterHub config the JupyterHub administrator can set an case-specific html snippet.

See https://github.com/jupyterhub/jupyterhub/issues/3356 for alternative ideas.

**Comment by 1kastner** [comment]
If there is some interest, I could submit a PR.

**Comment by minrk** [comment]
@1kastner that sounds great!
