### ISSUE TITLE
Support for PyJWT > 2

### ISSUE THREAD

**Issue by fabaff** [jupyterhub/oauthenticator#430]
### Bug description
PyJWT is constraint to [`>=1.7,<2.0`](https://github.com/jupyterhub/oauthenticator/blob/master/test-requirements.txt#L5)

#### Expected behaviour
Allow later PyJWT release

#### Actual behaviour
This constraint makes the package building process fails on NixOS. NixOS has PyJWT 2.1.0. I guess other distributions are affected too in the meantime as PyJWT 2.0.0 was almost 6 months ago.

Thanks

**Comment by consideRatio** [comment]
@fabaff ah there is support already I think, and what you pointed to was the test-requirements specifically which hasn't been properly updated.
