### ISSUE TITLE
GITLAB_URL should be read from the configuration instead of (or in addition to) the environment

### ISSUE THREAD

**Issue by dvandok** [jupyterhub/oauthenticator#462]
### Bug description

When setting up the gitlab authenticator with a private giltab instance, the base URL of that instance needs to be passed to the software. The way it is set up right now is by reading GITLAB_URL from the environment, where other information (such as the client secret) are read from the configuration. This is annoying because when jupyterlab runs as a service under systemd, this requires tweaking of the service environment. This should not be necessary.

#### Expected behaviour
Setting up jupyterhub with a private gitlab instance for oauth, the gitlab_url should be set in the configuration.

#### Actual behaviour
The GITLAB_URL can only be passed in the enviromnent.

### Your personal set up
We're running TLJH on a server for multiple users, authenticated against our own gitlab server.

 - OS:
Ubuntu 18.04
Python 3.6
TLJH: jupyterhub 1.4.0

I currently use a patched version of gitlab.py that addresses this issue; if you are interested I could share that.

**Comment by dvandok** [comment]
I notice a lot of difference between the TLJH code I have deployed and what is current on Github, so the issue may already have been dealt with...

**Comment by consideRatio** [comment]
I see in https://github.com/jupyterhub/oauthenticator/blob/6bf2d22b119ea60a96579be4fb86690288ceaebc/oauthenticator/gitlab.py#L44 that this is configurable already, so I presume this is related to TLJH previously using an older version of this package.
