### ISSUE TITLE
[Generic] Generic Oauthenticator Not support PKCE

### ISSUE THREAD

**Issue by iamjxb** [jupyterhub/oauthenticator#468]
For OIDC login using code flow with PKCE, the generic oauthenticator currently cannot generate code challenge and send code challenge method or code verifier. 
It is possible to add them through the extra_params and extra_authorize_params but that would make it "hard coded" and less secure. 
Is there a way to generate code challenge and verifier during runtime? If not, can we make a feature request for this?
Thank you.

**Comment by minrk** [comment]
Supporting PKCE sounds like a totally valid feature request, and seems pretty generic. If I [understand it correctly][pkce], what we would need is a boolean option for `use_pkce`, where if True, we add:

[pkce]: https://www.oauth.com/oauth2-servers/pkce/

in `OAuthLoginHandler`:

1. we generate a random string (`code_verifier`)
2. hash it with sha256
3. add params to `authorize_redirect`: `code_challenge=$hashed_verifier&code_challenge_method=S256`

in `OAuthCallbackHandler`:

1. retrieve `code_verifier` (persistence TBD; its own cookie, I guess?)
2. send original `code_verifier` in `code_verifier` param for the token request

**Comment by minrk** [comment]
Does it make a lot of sense to use PKCE with authorization_code flow? Reading about it, it seems to mostly be a replacement for mobile apps and single-page apps where the client secret cannot be reasonably protected. But since the code exchange request comes from the server side, this doesn't seem to be an issue in our case.

**Comment by humanSupafly** [comment]
> For OIDC login using code flow with PKCE, the generic oauthenticator currently cannot generate code challenge and send code challenge method or code verifier. It is possible to add them through the extra_params and extra_authorize_params but that would make it "hard coded" and less secure. Is there a way to generate code challenge and verifier during runtime? If not, can we make a feature request for this? Thank you.

Does generic oauthenticator support pkce?

How did you make it work using the extra_params and "hardcode" approch?
