### ISSUE TITLE
Allow for extra args in `authorize_url` to enable idp hints

### ISSUE THREAD

**Issue by belfhi** [jupyterhub/oauthenticator#470]
Hi,
I set up jupyterhub with GenericOAuthenticator to authenticate against my
Keycloak instance.
It would be nice if I could pass `kc_idp_hint=oidc` in the authorize_url 
so the user directly logs into the IdP and does not see the Keycloak Screen.

### Proposed change

Similar to `userdata_params` an extra attribute should be added
`authorize_params` with `Dict` type that will rhen be added to the authorize URL
after the client_id and client_secret.

### Who would use this feature?
Sites who run an infrastructure proxy like Keycloak could benefit like described 
above.
In general, other parameters can be used, it is not limited to this Keycloak usecase

**Comment by minrk** [comment]
Can you set `c.GenericOAuthenticator.authorize_url = "https://your-keycloak/authorize?kc_idp_hint=oidc"`? You have to set the authorize_url anyway with GenericOAuthenticator, I think you should be able to include params there.

**Comment by belfhi** [comment]
Oh. That was easy. Thanks very much @minrk . I was missing the ? character when I tried that out... ^^
