### ISSUE TITLE
Drop dependency on recommonmark - use MyST instead?

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/oauthenticator#480]
We have a dependency on recommonmark for our docs, but that makes us not able to work with Python 3.9 because its dependency commonmark hasn't updated to support Python 3.9.

I'd love to transition to have MyST instead. I think perhaps we use recommonmark to have markdown files part of Sphinx, while we could transition to use MyST instead.

**Comment by minrk** [comment]
Yeah, I think that's fine. I wouldn't expect anything to change, just swap it out.
