### ISSUE TITLE
check_whitelist() signature bug in BitbucketOAuthentication

### ISSUE THREAD

**Issue by adamlabadorf** [jupyterhub/oauthenticator#49]
Hi,

I am using oauth to authenticate against a bitbucket team. Using the version of oauthenticator installed with pip (0.5.0) I get the following exception:

`    Traceback (most recent call last):
      File "/opt/conda/lib/python3.5/site-packages/tornado/web.py", line 1469, in _execute
        result = yield result
      File "/opt/conda/lib/python3.5/site-packages/oauthenticator/oauth2.py", line 51, in get
        username = yield self.authenticator.get_authenticated_user(self, None)
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/auth.py", line 135, in get_authenticated_user
        if self.check_whitelist(username):
    TypeError: check_whitelist() missing 1 required positional argument: 'headers'
`

I tracked the issue down to the definition of BitbucketOAuthenticator.check_whitelist, which had a required second `headers` argument. I found that by moving the `headers` definition from the authenticate method to the class level and referencing it with self in the appropriate places that integration works correctly.

I have forked the repo and commited the fix, should I create a pull request for review?

**Comment by minrk** [comment]
Sounds like the right fix. Pull Request would be welcome!

**Comment by minrk** [comment]
Fixed by #50. Thanks!
