### ISSUE TITLE
Adding organization (and team) information to auth_state in GithubOAuthenticator

### ISSUE THREAD

**Issue by ft-cama** [jupyterhub/oauthenticator#492]
### Proposed change
I would like to have the GithubOAuthenticator store the organization/team through which a user is authenticated in e.g. auth_state.

### What can we achieve with this information?
We can customize the kubespawner so that it based on the user's organization/team does something specific, e.g. mounts an organization specific volume.

### Why is this a good idea?
It seems intuitive and natural that a user's jupyterhub instance is customized based on which organization the user belongs to. 

### Code change proposal
Link to GithubOAuthenticator: [https://github.com/jupyterhub/oauthenticator/blob/main/oauthenticator/github.py]

When checking if the user belongs to one of the allowed organizations do the following (lines 176-182 in the link):
```
        user_org = '' # NEW
        if self.allowed_organizations:
            for org in self.allowed_organizations:
                user_in_org = await self._check_membership_allowed_organizations(
                    org, username, access_token
                )
                if user_in_org:
                    user_org = org # NEW
                    break
```

And then to later update auth_state (lines 195-197 in the link):
```
        auth_state['access_token'] = access_token
        auth_state['github_user'] = resp_json
        if user_org != '': # NEW
            auth_state['user_org'] = user_org # NEW
```

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/github-organizations-user-permissions/13382/2

**Comment by ft-cama** [comment]
I get your point @manics!

How about instantiating an empty list and then append all the organizations that a user is part of? If the list is empty after looping through the allowed_organizations list, then the user is not authorized and authenticate still returns None.

```
    userdict = {"name": username}
    userdict["auth_state"] = auth_state = {}
    auth_state['access_token'] = access_token
    auth_state['github_user'] = resp_json

    if self.allowed_organizations:
        user_orgs = []
        for org in self.allowed_organizations:
            user_in_org = await self._check_membership_allowed_organizations(
                org, username, access_token
            )
            if user_in_org:
                user_orgs.append(org)
        if not user_orgs: # user_orgs is empty
            self.log.warning("User %s is not in allowed org list", username)
            return None
        else: # user is part of one or more orgs
            auth_state['user_orgs'] = user_orgs
```
This above code should replace lines 176-197 in the [GithubOAuthenticator](https://github.com/jupyterhub/oauthenticator/blob/8c1cf0c616d5e19d1f93238673f17db2daf57fa0/oauthenticator/github.py).

This requires looping through all the allowed organizations every time a user tries to log in, but this happens anyway when a user is not part of any organization or part of only the last organization in the list 'self.allowed_organizations'.

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/let-jupyterhub-configure-and-mount-group-volumes/13675/1

**Comment by manics** [comment]
That would work, however the reason I suggested implementing this by fetching the user info is that you can test it without needing a release of oauthenticator, and also serves to document how to extend this more generally, for example someone might want to get additional user info.

If that works then we can decide whether it's worth adding an option to request and return the full user-information?

**Comment by ft-cama** [comment]
I don't have the overview to give a specific implementation of how generally to get additional user information. 

**Some thoughts**
Most additional information requires additional scope(s), e.g. to get the user's email, the OAuth scope "user:email" is needed, so the scope(s) given in the config file will determine how much additional information about the user can be retrieved in the first place. 

To get all additional user information we can loop over the given scopes and retrieve the corresponding information.

It doesn't get a lot more general than this pseudocode:
```
for scope in scopes:
    // Retrieve (and process) scope specific information
    // Save information in auth_state
```

Note that the implementation of retrieving information associated with a scope can look very different, e.g. getting just the user email (single API call) versus getting the organizations of the user (multiple API calls).
