### ISSUE TITLE
[CILogon] Allow hub usernames to be left unchanged

### ISSUE THREAD

**Issue by GeorgianaElena** [jupyterhub/oauthenticator#514]
### Bug description

With `oauthenticator` 15.0.0, there isn't possible anymore to have the hub usernames be the value returned by the chosen claim. This is because `action` is a **required** field of `allowed_idps` dict and it can either be `strip_idp_domain` or `prefix`.

#### Expected behaviour

Migrate to 15.0.0 without requiring to change existing hub user's usernames.

#### Actual behaviour

You can either strip the domain from the username or prefix the username claim with a string. 

### Proposed solution

We could either remove the `action` from the required fields, which will translate into "no action specified on the username, then no change will be applied to it", or we could add a new explicit action that's just "don't change".

https://github.com/jupyterhub/oauthenticator/blob/42bebe989ec10e8a439bc80a011fbe64cc01669f/oauthenticator/schemas/cilogon-schema.yaml#L23-L25

**Comment by consideRatio** [comment]
It would be great to get this resolved quickly, it sounds like a very troublesome experience otherwise. If you submit a fix I'll be quick to assist with review so we can get a new release out.
