### ISSUE TITLE
[CILogon] Instructions for CILogon with Google OAuth use new Google API for `oid`, but CILogon uses an old OAuth API

### ISSUE THREAD

**Issue by GeorgianaElena** [jupyterhub/oauthenticator#522]
### Bug description

The `allowed_idps` dict is documented to expect its keys to be entity ids from the list provided by CILogon at https://cilogon.org/idplist.

https://github.com/jupyterhub/oauthenticator/blob/333f3563f8ccb8f40e5bd48d8edb92ce51859098/oauthenticator/cilogon.py#L113

However, the `idp` field of the `userinfo` response from CILogon
https://github.com/jupyterhub/oauthenticator/blob/f3af268474ecce4fc2a9eb789c2e06cd692375fa/oauthenticator/cilogon.py#L306

is an old Google oidc endpoint, i.e. http://google.com/accounts/o8/id . I believe  the OpenID Connect authorization endpoint to use instead is https://accounts.google.com/o/oauth2/v2/auth which is document at https://developers.google.com/identity/protocols/oauth2/openid-connect.

#### Expected + actual behaviour

I expected what CILogon would return in the `userinfo` dict would be the entity id in the list at https://cilogon.org/idplist, which is `https://accounts.google.com/o/oauth2/auth`, but is not, so when trying to use the Google identity provider, JupyterHub returns a 500 error.

### How to reproduce

A config like:
```
c.CILogonOAuthenticator.allowed_idps = {
    'https://accounts.google.com/o/oauth2/auth': {
        'username_derivation': {
            'username_claim': 'email',
        }
    },
}
```
won't work, because it would think you're using an idp that wasn't authorized when logging in using Google (which is actually the opposite of what's wanted)

### Possible solution

I opened an issue about it upstream also https://github.com/ncsa/OA4MP/issues/45 and I believe solving that would also solve this issue.

In the meantime however, we should document which is the actual entity id of Google that is expected.

**Comment by terrencegf** [comment]
https://test.cilogon.org has been updated so that the entityID values reported by https://test.cilogon.org/idplist/ match the "iss" (issuer) claim returned by the OAuth2/OIDC "userinfo" endpoint. See the [upstream issue](https://github.com/ncsa/OA4MP/issues/45#issuecomment-1165486305) for details.

https://cilogon.org should be updated mid-July.

**Comment by terrencegf** [comment]
The update has been deployed to https://cilogon.org . Please contact help@cilogon.org if the update does not solve this issue.

**Comment by GeorgianaElena** [comment]
https://github.com/ncsa/OA4MP/issues/45 has been fixed, so closing this one too! Thanks @terrencegf !
