### ISSUE TITLE
[GitLab] allow union of allowed_users and {allowed_gitlab_groups, allowed_project_ids}

### ISSUE THREAD

**Issue by floriandeboissieu** [jupyterhub/oauthenticator#545]
### Bug description

This issue is similar to #396 . In [GitLab Oauth](https://github.com/jupyterhub/oauthenticator/blob/main/oauthenticator/gitlab.py) any reason for keeping the intersection between allowed_users and {allowed_gitlab_groups, allowed_project_ids} knowing that there is also a blocked_users configuration argument?

I labelled it as a bug because I don't see any reason for that and it seems counter-intuitive to be able to union members of groups and projects but not with allowed_users list. But I am new to jupyterhub so... and referring to #396 it seems to be a change from a previously available union behaviour, thus I am sorry if it is an intended behaviour.

#### Expected behaviour

It would be expected to have a union here, to invite users external to all groups or projects

#### Actual behaviour

At the moment, the users allowed to login are the intersection of allowed_users and the members of {allowed_gitlab_groups, allowed_project_ids}.

#### Workaround

Creating a group for non-members users, but that is not very sustainable :-)

**Comment by consideRatio** [comment]
Fixed by #594
