### ISSUE TITLE
Add team whitelisting for GitHubOAuthenticator and  GitLabOAuthenticator 

### ISSUE THREAD

**Issue by jbweston** [jupyterhub/oauthenticator#57]
BitBucketOAuthenticator has team whitelisting, so it would seem reasonable to also add this for Gitlab and Github.

I am already working towards submitting a pull request, but am creating this issue here to serve as a centre for discussion and to avoid spamming the jupyterhub gitter channel.

**Comment by jbweston** [comment]
I am already working towards submitting a pull request, but am creating this issue here to serve as a centre for discussion and to avoid spamming the jupyterhub gitter channel

**Comment by jbweston** [comment]
I have a few questions about what a reasonable solution would look like. This is mostly related to naming things in a sane and consistent way.

In BitBucket there appears to be a concept called [`team`](https://confluence.atlassian.com/bitbucket/bitbucket-cloud-teams-321853005.html), which appears to be roughly analogous to what Gitlab calls a [`group`](https://docs.gitlab.com/ce/workflow/groups.html), and what Github calls an [`organization`](https://github.com/blog/674-introducing-organizations).

Confusingly Bitbucket also has a concept called `group`, which appears to
correspond to what Github calls a `team`, and this appears to have no analogue
in Gitlab.

---

So we need to:
1. decide what it is useful to whitelist on, i.e. should we allow only
   Bitbucket team/Gitlab group/Github organization whitelisting, or should we
   allow Bitbucket group/Github team level granularity also?
2. decide whether to use a consistent naming convention for the configuration
   parameters across the 3 classes (at the expense of it being non-obvious what is
   actually being whitelisted), or to use names specific to the service.

---

My opinion on (1) would be that we should only do whitelisting on the
team/group/organisation level for now. This is all I personally need for my
application, and more specific whitelisting can be added later by anyone who
needs this.

As for (2) I would say that we should keep the names of configuration
parameters tied to the concepts defined by the individual services (rather than
referring to everything as `teams`, for example). I would, however, probably
follow a naming convention like `gitlab_organization_whitelist`,
`bitbucket_team_whitelist`, `gitlab_group_whitelist` to remain explicit and
also to prevent name clashes when combining with other authenticators
(notably `LocalGitlabOAuthenticator` already has a `group_whitelist` so behaviour
would be potentially incorrect if `GitlabOAuthenticator` also defined this).

**Comment by minrk** [comment]
Agreed on both counts - naming with the service's own names should be the least confusing. And good catch on the `group_whitelist` clash. In general, I like to avoid redundant names such as `BitbucketOAuthenticator.bitbucket_team_whitelist`, but it would be good to avoid the clash. One more option would be to only do that where there is a clash (i.e. group), but I'm not sure if that's more or less confusing.

**Comment by jbweston** [comment]
I agree about the redundancy, but I think that consistent behaviour is more important. In addition there are already other attributes like `gitlab_client_id` and `gitlab_client_secret` so this is also consistent with other places in the API.

Speaking of which, I notice that both Gitlab and Github oauthenticators can be configured to use on-premises installations, and that the hostname for the corresponding server can be configured with an environment variable. However, `GITHUB_HOST` expects just the hostname without the URI scheme (`https://`), whereas `GITLAB_HOST` expects the URI scheme to be present already.

Would it make sense to change this for consistency's sake? I understand that I would also have to do a check to see if the environment variable already includes the scheme or not (in order to maintain backwards compatibility with the previous inconsistent behaviour).

**Comment by jbweston** [comment]
also @minrk doing proper pagination for the Github and Gitlab APIs involves parsing [`Link` headers](https://developer.github.com/guides/traversing-with-pagination/#basics-of-pagination). Currently I am using a regex that seems to correctly parse the Link header expected from these APIs, however I am not very confident that it is particularly robust, and am almost certain that it is not capable of parsing an arbitrary [RFC compliant](https://tools.ietf.org/html/rfc5988) link header.

On the other hand, I don't want to add dependencies (e.g. [this library](https://pypi.python.org/pypi/LinkHeader)) just to perform this one task.

**Comment by jbweston** [comment]
Also,  `BitBucketOAuthenticator`, `GitLabOAuthenticator` and `GitHubOAuthenticator` now contain a lot of duplicate code; the only difference is a couple of keys in the response json and how to get the next page (Git[hub|lab] use Link headers, and Bitbucket uses some field in the response json)

What is your view on grouping the common functionality to keep things DRYer? On the other hand there are perhaps sufficient differences to make factoring this out just confusing...
