### ISSUE TITLE
KeyCloak custom attribute to Jupyter

### ISSUE THREAD

**Issue by inteloid** [jupyterhub/oauthenticator#570]
Hi.

We use KeyCloak to authenticate our users.

We would like to have user-individual values configured as KeyCloak custom attributes, and then be able to retrieve them from JupyterHub Spawner, or Jupyter Notebook.

Any ideas on how to do that?

**Comment by manics** [comment]
Closing, since this has already been posted on https://discourse.jupyter.org/t/keycloak-custom-attributes-in-jupyter/17629
