### ISSUE TITLE
Release planning for 16.0.0

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/oauthenticator#585]
JupyterHub 4 is now released and I look to get z2jh 3 and tljh 1 bundle with various new dependencies with recent breaking changes. Let's try get a release out with oauthenticator!

### Next version number: 16.0.0

We decided to go for 16.0.0 for the major refactoring.

### Things I track to resolve before release

- #594
- #615
- #620
- #599
- #601
- #602
- #603
- #605
- #628
- #630
- #631
  - Closes #619
- #637
  - Closes #632
- #640
  - Closes #639 
-  #641
  - Closes #612

**Comment by manics** [comment]
I think the big refactoring justifies a major release even if it's not required.

**Comment by consideRatio** [comment]
Wieee #594 is in! I'd like to go for the following PRs and then make a release. With #594, I think these changes are far easier to make and I expect them to be quite simple PRs.

- #615
- #619
- #620

**Comment by consideRatio** [comment]
Wieeeeeeeeeeeeeeeeeeeeee!!!! Thank you @GeorgianaElena @minrk and @manics for the push to get this all the way!!!

![image](https://github.com/jupyterhub/oauthenticator/assets/3837114/b3bd2775-7fab-4b97-af16-3be69badb1af)
