### ISSUE TITLE
Generic Oauth2 authenticator

### ISSUE THREAD

**Issue by dmvieira** [jupyterhub/oauthenticator#59]
Hey guys, why we don't have a default implementation for oauth2?

**Comment by minrk** [comment]
There is a base class that implements the common parts (`oauth2.OAuthenticator`). There's a last step needed for turning the access token on the callback into a username, which seems different for each provider. That's the only difference between them right now. I'm not aware of a generic implementation of this. Is there a generic way to ask an oauth provider the username corresponding to an access token?

**Comment by dmvieira** [comment]
Yes, there is an RFC https://tools.ietf.org/html/rfc6749#section-4.4

I'm doing here ;)

**Comment by minrk** [comment]
closed by #60
