### ISSUE TITLE
Cannot override username_claim for helm chart anymore when using master

### ISSUE THREAD

**Issue by jabbera** [jupyterhub/oauthenticator#605]
### Bug description

This change: https://github.com/jupyterhub/oauthenticator/pull/595 removed the ability to have a custom claim name from the helm chart. For example the AzureAD authenticator now forces you to use name: https://github.com/jupyterhub/oauthenticator/blob/296aa57007909bd5baff53c1b4d6159155deff54/oauthenticator/azuread.py#L23

I use a custom attribute called samAccountName that maps back to people on prem values. Why was this configuration option removed?

**Comment by consideRatio** [comment]
Nice catch @jabbera!! I this is an unintended regression from #595.

### What happened?

A change like below was made.

```diff
-    @default("username_claim")
-    def _username_claim_default(self):
-        return "email"

+    username_claim = "email"
```

The `username_claim` that previously was a traitlet configurable object got overridden with a string, so there is no longer a traitlet configurable via `c.Auth0Authenticator.username_claim`.

### What to do?

I think mostly revert #595, I think the principles should be:

- If a class redefines the config default for a super class' traitlet, then I think it needs do so with the `@default` decorator to avoid overriding it.

  **Like this**

  ```python
      @default("username_claim")
      def _username_claim_default(self):
          return "email"
  ```
  
  **Not like this**
  
  ```python
      username_claim = "email"
  ```

  **Not like this either**

  I think doing this could cause a subtle issue, where configuring `c.OAuthenticator.username_claim` becomes different from configuring `c.AzureADOAuthenticator.username_claim`.

  ```python
      username_claim = Unicode(
          "my default value",
          config=True,
      )
  ```
  
- If a class defines a new traitlet on its own, then I think it should set its default value as part of defining the traitlet.

  ```python
      new_config = Unicode(
          "my default value",
          config=True,
      )
  ```
