### ISSUE TITLE
[CILogon] Require specification of `allowed_idps`?

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/oauthenticator#615]
I understand the list in `allowed_idps` as the identity providers possible to use via CILogon. Is there a use case to allow that to be unset? It seems like allowing for that adds some complexity in implementation and documentation on communicating how this authenticator should be configured.

I suggest that if we don't see a use case for allowing it to be unset, we make a breaking change and forcing it to be set to something.

**Comment by consideRatio** [comment]
Here is a section from work ongoing [in a PR](https://github.com/jupyterhub/oauthenticator/pull/594/files#diff-6f11d268e268a0d36dc3e95a40ff2b7b2785a842fa1a561df1e79be53172106cR368-R374), indicating on the added complexity.

```python
        if self.allowed_idps:
            # ... lots of code here ...

        # Although not recommended, it might be that `allowed_idps` is not specified
        # In this case we need to make sure we still check `allowed_users` and don't assume
        # everyone should be authorized
        elif self.allowed_users:
            if username in self.allowed_users:
                return True
            return False

        # otherwise, authorize all users
        return True
```

**Comment by consideRatio** [comment]
I'm not confident on the difference between allowed_idps and shown_idps, is there situations when we want to allow more than we show, or show more than we allow etc?

https://github.com/jupyterhub/oauthenticator/blob/79252e7f605d9eebc54901ec97fe1f9ffb8ee451/oauthenticator/cilogon.py#L221-L231

https://github.com/jupyterhub/oauthenticator/blob/79252e7f605d9eebc54901ec97fe1f9ffb8ee451/oauthenticator/cilogon.py#L122-L177

**Comment by consideRatio** [comment]
I think `shown_idps` doesn't have a purpose if we require `allowed_idps` to specify all IDPs to use explicitly.

It is only referenced from here.

https://github.com/jupyterhub/oauthenticator/blob/0eccfbdf4d6caebd018b1072b3295369b23087ed/oauthenticator/cilogon.py#L32-L43

I think we should require `allowed_idps`, and then pass the `allowed_idps` as we use `shown_idps` now.

**Comment by consideRatio** [comment]
### Deprecate `username_claim` and `additional_username_claims`

With `allowed_idps`, users are required to provide `["username_derivation"]["username_claim"]`, and when they do base `username_claim` and `additional_username_claims` are irrelevant.

Due to that, I suggest we deprecate use of both.

**Comment by consideRatio** [comment]
@GeorgianaElena I've ended up working on making `allowed_idps` required and deprecating and `shown_idps` and `additional_username_claims` that no longer becomes relevant. I think working on the `allow_all` config and defaulting to `False` required additional work to work without `allowed_idps` configured, so I figured I'll make it required instead to not first do that work and then go back on it.

**Comment by GeorgianaElena** [comment]
@consideRatio, thank you! I think your proposal makes things more simpler and clearer and we should do it 👍🏼 

We have in 2i2c configurations that don't specify `allowed_idps` and use `username_claim` + `shown_idps` only. The places where I've used that myself, I've done it because it seamed easier and faster to write.

**Comment by consideRatio** [comment]
@GeorgianaElena thanks you for the quick feedback!! I'll keep working on this!
