### ISSUE TITLE
check_allowed workaround not needed when jupyterhub>4.0.1 is required

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/oauthenticator#621]
I'm adding a workaround in the code, and want to reference an issue with more information. This is that issue.

The workaround looks like below and will be put in all check_allowed overrides.

```python
    async def check_allowed(self, username, auth_model):
        # workaround for JupyterHub<=4.0.1, see <this issue>
        if auth_model is None:
            return True
```

In JupyterHub<=4.0.1, `check_allowed` was sometimes called directly by JupyterHub passing `auth_model` as `None`. Me and Min concluded that it was fine to just return True in those cases for the OAuthenticator classes in https://github.com/jupyterhub/jupyterhub/issues/4461.

**Comment by manics** [comment]
The comment has been changed to
https://github.com/jupyterhub/oauthenticator/blob/ed6b97e56aaa2c30bb6122ebf633a0f504859d32/oauthenticator/oauth2.py#L1104-L1107

Do we still need to keep this issue open?
