### ISSUE TITLE
Allowing multiple hosted domain subdomains

### ISSUE THREAD

**Issue by gforsyth** [jupyterhub/oauthenticator#63]
I manage a JupyterHub at George Washington University and we currently use GitHub oauth for logins but we're looking at switching to Google oauth and using the university's google apps accounts. 

Due to some historical quirk, students are assigned a `gwmail.gwu.edu` address while faculty/staff have `email.gwu.edu` -- we want faculty and students to both be able to access the hub. Are there security concerns I'm missing if I change https://github.com/jupyterhub/oauthenticator/blob/master/oauthenticator/google.py#L111 and remove the `@` from the `endswith` condition? 

I'm not sure if this is a particularly common problem, so I'm happy to maintain a fork for our needs, but if it would be useful I'm also happy to contribute it back in, be it the potential solution above or something else.

**Comment by minrk** [comment]
I think this would be a fine addition.

You'd need to be a little more careful than just removing the @, because`notgwu.edu` also `endswith('gwu.edu')`, but I think this is sensible. I see two options:

1. allow hosted_domain to be a tuple. endswith accepts tuples of strings (`endswith(('a', 'b'))`)
2. allow subdomain matching, such as:

   ```python
   # adding '.' ensures matching only applies to whole domain parts
   ('.' + domain).endswith('.' + ref)
   ```

I can't think of any cases where subdomains *aren't* wanted, but maybe it's more prudent to go the tuple way.

**Comment by gforsyth** [comment]
Hey @minrk -- sorry, just starting to get to this now. 

Should this still use `traitlets` to verify the input? I'm having an issue there since `endswith` recognizes a `tuple` of strings but not a `Tuple` of strings...

**Comment by minrk** [comment]
`Tuple` declared on the class will be a `tuple` on any instance of that class. traitlets would only be used for exposing this as configuration, not the runtime validation of values. Where are you seeing a `Tuple` instance?

I was thinking something along the lines of:

```python

def _with_dot(domain):
    if domain.startswith('.'):
        return domain
    return '.' + domain

class GoogleOAuthenticator(OAuthenticator):
    domains = Tuple(help="""Tuple of domains to match...""", config=True)
    ...
    def authenticate(self):
        ...
        if not self.domains or _with_dot(domain).endswith((_with_dot(d) for d in self.domains)):
            # valid
```

**Comment by gforsyth** [comment]
Ahh, ok, I understand a bit better now.  The way it's set up now just relies on the default value being set when the `Tuple` is defined.

**Comment by david-dumas** [comment]
Opened to review/suggestions on my PR. Breaking changes inside.
