### ISSUE TITLE
[OpenShift] Fix no longer respected ca_certs config

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/oauthenticator#639]
In https://github.com/jupyterhub/oauthenticator/pull/363, the OpenShiftOAuthenticator got introduced with a `ca_certs` configuration that was used as an additional argument to the client making web requests when authenticating. After unreleased refactoring in #526, this config is no longer respected.

Fixing this can be done in a few ways I'm considering:

1. (breaking) We declare that `ca_certs` should be specified using `http_request_kwargs` (from #578 by @manics)
2. (broken) We declare its no longer supported
3. (maintenance need escalation) We lift `ca_certs` as a config to OAuthenticator from openshift

I'm leaning towards a breaking change, where we say it should be configured using `http_request_kwargs` instead.

@manics and @GeorgianaElena, what do you think?

**Comment by manics** [comment]
I think 1 or 3 are fine.

It would be nice if we could make initialisation fail when an undefined traitlets config is set.

**Comment by consideRatio** [comment]
I've went for 1 in #640, where configuring `ca_certs` errors and references `http_request_kwargs`, and where configuring `validate_cert` is deprecated as its available in OAuthenticator already as as `validate_server_cert`.
