### ISSUE TITLE
[Google, Globus, BitBucket] Configuring `enable_auth_state` causes `set is not JSON serializable`

### ISSUE THREAD

**Issue by ryanlovett** [jupyterhub/oauthenticator#667]
### Bug description

Upon upgrading to z2jh 3.0.1, a hub with google oauth emits a "500 : Internal Server Error". The logs indicate that a set object cannot be serialized to JSON.

#### Expected behaviour

I expected to be able to authenticate via Google

#### Actual behaviour

The hub emits an error.

### How to reproduce

1. A user visits the hub URL.
2. The user clicks on the button to sign in.
3. The user sees the `500 : Internal Server Error`.

### Your personal set up

Some of the configuration is at https://github.com/berkeley-dsep-infra/datahub/tree/staging/deployments/highschool.

Initially there were three hosted domains and I tried trimming them down to one, however that was not successful.

Related configuration, https://github.com/berkeley-dsep-infra/datahub/blob/staging/deployments/highschool/config/common.yaml#L23C1-L34

And secrets:
```
jupyterhub:
    hub:
        config:
            GoogleOAuthenticator:
                client_id: [snipped].googleusercontent.com
                client_secret: [snipped]
                oauth_callback_url: https://highschool-staging.datahub.berkeley.edu/hub/oauth_callback
            Authenticator:
                admin_users:
                    # infrastructure
                    - user1@berkeley.edu
                    - user2@berkeley.edu
```

We also have:
```
      Authenticator:
        enable_auth_state: true
        manage_groups: true
      OAuthenticator:
        allow_all: true
```

I also tried disabling `manage_groups`.

The error occurs even without spawning, i.e. if the user tries to go to /hub/admin or /hub/home, where the latter doesn't start a server.

```
[I 2023-08-15 23:19:14.910 JupyterHub oauth2:102] OAuth redirect: https://our_hub/hub/oauth_callback
[I 2023-08-15 23:19:14.911 JupyterHub log:191] 302 GET /hub/oauth_login?next=%2Fhub%2F -> https://accounts.google.com/o/oauth2/v2/auth?response_type=code&redirect_uri=https%3A%2F%2Four_hub%2Fhub%2Foauth_callback&client_id=_snipped_.apps.googleusercontent.com&state=[secret]&scope=openid+email (@10.0.0.37) 2.06ms
[E 2023-08-15 23:19:15.521 JupyterHub web:1871] Uncaught exception GET /hub/oauth_callback?state=_snipped_&code=_snipped_&scope=email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+openid&authuser=0&hd=our.domain&prompt=none (10.0.0.37)
    HTTPServerRequest(protocol='https', host='our_hub', method='GET', uri='/hub/oauth_callback?state=_snipped_&code=_snipped_&scope=email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+openid&authuser=0&hd=our.domain&prompt=none', version='HTTP/1.1', remote_ip='10.0.0.37')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
                 ^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/site-packages/oauthenticator/oauth2.py", line 202, in get
        user = await self.login_user()
               ^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/site-packages/jupyterhub/handlers/base.py", line 832, in login_user
        user = await self.auth_to_user(authenticated)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/site-packages/jupyterhub/handlers/base.py", line 821, in auth_to_user
        await user.save_auth_state(auth_state)
      File "/usr/local/lib/python3.11/site-packages/jupyterhub/user.py", line 344, in save_auth_state
        self.encrypted_auth_state = await encrypt(auth_state)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
        result = self.fn(*self.args, **self.kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/site-packages/jupyterhub/crypto.py", line 141, in _encrypt
        return self.fernet.encrypt(json.dumps(data).encode('utf8'))
                                   ^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/json/__init__.py", line 231, in dumps
        return _default_encoder.encode(obj)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/json/encoder.py", line 200, in encode
        chunks = self.iterencode(o, _one_shot=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/json/encoder.py", line 258, in iterencode
        return _iterencode(o, 0)
               ^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/json/encoder.py", line 180, in default
        raise TypeError(f'Object of type {o.__class__.__name__} '
    TypeError: Object of type set is not JSON serializable
```

I see from the changelog that some objects were converted to Sets, but I can't tell which item is being serialized here and if its something I need to coax into a list.

**Comment by consideRatio** [comment]
Hmmmmm... A failure to encode auth state to JSON.

Seems like a bug. I guess there is no representation in JSON for a set, so that may be the cause. It happens because you save the auth state and we didnt test with that.

**Comment by consideRatio** [comment]
Yes, this is a bug seen by users with `c.JupyterHub.enable_auth_state = True`, at least for GoogleOAuthenticator.

**Comment by consideRatio** [comment]
I've opened https://github.com/jupyterhub/oauthenticator/pull/668 that discusses how to fix this regression and in what way to do it, without actually doing it.

**Comment by ryanlovett** [comment]
Setting `Authenticator.enable_auth_state` to false does work around the issue. In this particular hub deployment, most of the hubs use CanvasOAuthenticator and we enable auth_state to extract info about students' course affiliations and roles. This one hub is an outlier in that it uses Google OAuth and we don't need the auth state for anything. So we could leave the setting disabled for this one hub and would be perfectly fine in the short term.

I hope you enjoy your vacation!
