### ISSUE TITLE
Launching multiple notebooks in jupyterhub with different jwt tokens loads the first spawned notebook.

### ISSUE THREAD

**Issue by adhithya71** [jupyterhub/oauthenticator#689]
Bug description :

I am using jupyterhub with custom authentication where a userId is extracted from jwt , and a notebook is spawned on that userId . But when I launch multiple notebooks with different userId from the same browser , it loads the first notebook . 
The new userId has been passed correctly in the logs , but somewhere it changes and the previous values are loaded .
This works fine when I launch each unique notebook in different browsers .

**Comment by manics** [comment]
I think this is most likely an issue with your single user server, e.g. JupyterLab or jupyter notebook.

You can try asking on the community forum to see if anyone has an idea of the problem, or if you can come up with a self contained example you could open a bug on the relevant repository.

Either way, please include enough information for someone to reproduce the problem. Thanks!
