### ISSUE TITLE
Add support for groups to the OpenShift OAuth plugin

### ISSUE THREAD

**Issue by luisfdez** [jupyterhub/oauthenticator#70]
This is not strictly an issue but an improvement for the OpenShift support.

A good starting point would be to know if the group/role information is available in the _service account as oauth client_ scenario (the more versatile from an end-user point of view).

The information service accounts can access is described here:
https://docs.openshift.org/latest/architecture/additional_concepts/authentication.html#service-accounts-as-oauth-clients

**Comment by willingc** [comment]
Hi @luisfdez,

We've recently updated the README to include additional detail on [OpenShift support](https://github.com/jupyterhub/oauthenticator/blob/master/README.md#openshift-setup).

I'm going to close this as resolved. Thanks for filing the issue to improve the docs.
