### ISSUE TITLE
GitHub OAuth should override username normalisation (prevent lowercasing)

### ISSUE THREAD

**Issue by stefanoborini** [jupyterhub/oauthenticator#73]
I noticed that GitHub oauthenticator does not reimplement normalise_username, so the default implementation is used. This creates the confusing (and potentially conflicting) situation where a github user  having mixed case will have a jupyterhub user that is all lowercase.

**Comment by stefanoborini** [comment]
Ok, I investigated the GitHub policy, and apparently it is case insensitive, meaning that stefanoborini and StefanoBorini are considered to be the same username in github. It is however case preserving, meaning that once you create it with a given capitalization, it will be preserved.

Technically, it is therefore impossible for conflicts to arise due to lowercase normalisation in jupyterhub. You cannot create another github user with a different case, log into jupyterhub, and create trouble. 

It is however a question if case should be preserved in jupyterhub.

**Comment by maxrudolph** [comment]
I am using jupyterhub and students who had created github usernames containing uppercase letters were unable to launch their notebooks through jupyterhub.

**Comment by minrk** [comment]
@maxrudolph what versions of JupyterHub and OAuthenticator? The current version of each is regularly used with GitHub users with mixed-case usernames. If it's been up for a while, you may want to clear the jupyterhub database (trash `jupyterhub.sqlite`) and relaunch.

**Comment by maxrudolph** [comment]
@minrk  I am using jupyterhub 0.7.2 and nbgrader 0.4.0. I resolved the problem by having all users create github accounts with lowercase letters.
