### ISSUE TITLE
[Google] Decouple `hosted_domain` from domain stripping usernames

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/oauthenticator#733]
Currently, if `GoogleOAuthenticator.hosted_domain` is configured to a list with a single domain, the username is stripped of that domain. If another hosted_domain is added, no domains are stripped from the usernames etc.

This is a fragile configuration, where a change to `hosted_domain` for authorization purposes leads to changes in usernames. We should make sure those changes are decoupled from each other I think.

This isn't an urgent issue or something we need to fix, but I wanted it represented as a GitHub issue for now.

**Comment by manics** [comment]
I agree, I attempted this but all the tests broke so I decided to leave it for the future.
