### ISSUE TITLE
configuring multiple authenticators in JupyterHub

### ISSUE THREAD

**Issue by wwj718** [jupyterhub/oauthenticator#74]
my users will have Google id's some will have Github id

Is it possible to do?

**Comment by minrk** [comment]
It is technically possible, but it has not been done, to my knowledge. A MultiAuthenticator would need to be added that dispatches to Google and GitHub, and puts them on different URLs. An extra page handler would need to be added to allow the users to select the right provider.

**Comment by wwj718** [comment]
thank you for your reply 😄
