### ISSUE TITLE
"oauth callback made without a token" on attempting to log in with Google OAuth

### ISSUE THREAD

**Issue by tiggerntatie** [jupyterhub/oauthenticator#77]
I am successfully seeing the Google OAuth permission page, where I allow the application access to my google profile and e-mail address. When I select 'allow', the browser returns to Jupyterhub server and displays 400: bad request and "oauth callback made without a token".  I have oauthenticator-0.5.1, installed from github. 

Edit: Callback URL clearly shows a code:

```https://<domain>/jupyter/hub/oauth_callback?code=4/ljNDF1aRSYYjmWs6qf0BgncHtbLDxlZk5I5-PERaoQA&authuser=0&session_state=7059f12686a635b1d2da35e21189f371f6f11a13..dfe6&prompt=consent#```

I see same behavior with oauthenticator 0.6.0.dev and jupyterhub 0.8.0.dev.

Any ideas where I might look for a problem?

**Comment by minrk** [comment]
If you can, can you show the values for `handler.request.get_full_url()`? and `handler.get_arguments('code')`?

**Comment by tiggerntatie** [comment]
Thank you! Your questions (and their answers) quickly revealed clearly that arguments weren't making it through the nginx proxy. Easily fixed!

**Comment by ryantuck** [comment]
what changes to your nginx proxy were necessary to get this working?

**Comment by tiggerntatie** [comment]
I was attempting to have JH respond at something other than the root, i.e. mydomain.com/jupyter instead of mydomain.com. An approach that I settled on (perhaps not the best) involved using regex matching, thus:  

    # Managing literal requests to the JupyterHub front end
    location ~ /jupyter(.*) {
        proxy_pass http://127.0.0.1:8000/jupyter$1;
    .....
    # Managing WebHook/Socket requests between hub user servers and external proxy
    location ~* /jupyter/(api/kernels/[^/]+/(channels|iopub|shell|stdin)|terminals/websocket)/? {
        proxy_pass http://127.0.0.1:8000/jupyter/$1;

Since I don't work with nginx so often, I did not realize that once you start playing with regex you are *required* to construct the full address being passed to the proxy. So the corrected version looked like this:


    # Managing literal requests to the JupyterHub front end
    location ~ /jupyter(.*) {
        proxy_pass http://127.0.0.1:8000/jupyter$1$is_args$args;
    .....
    # Managing WebHook/Socket requests between hub user servers and external proxy
    location ~* /jupyter/(api/kernels/[^/]+/(channels|iopub|shell|stdin)|terminals/websocket)/? {
        proxy_pass http://127.0.0.1:8000/jupyter/$1$is_args$args;

This was enough to get the Oauth callback working properly. Unfortunately, as I continued to move forward in my testing I found that while I could create and open notebooks, the browser was unable to communicate with the kernel, leaving me in a persistent "waiting for kernel" state. Ultimately, I decided that the goal of putting my server at /jupyter was not so compelling that I needed to spend more time to solve that problem.

So I reverted to putting the server at the domain root (while allowing nginx to serve static content at other addresses), and have confirmed that both the default and Google Oauth authentication both work correctly. Now I am having an adventure trying to have dockerspawner launch singleuser containers.. If you are curious, you can find that question on [google groups](https://groups.google.com/forum/#!topic/jupyter/DTB28nagcuA). :)

Thanks!

**Comment by tiggerntatie** [comment]
Heh.. I just realized that it's your video at Pydata London 2016 that I have partly used as a guide for my adventure ("Hmm.. that looks pretty easy to set up. I think I'll give it a go!").
