### ISSUE TITLE
Jupyterhub integration error Keycloak

### ISSUE THREAD

**Issue by Najafov007** [jupyterhub/oauthenticator#771]
### Bug description

Hello, I've asked this question in Jupyterhub community but didnt get any solution. The problem is with integration jupyterhub with keycloak. So we are in openshift and installing jupyterhub using bitnami helm chart. Here's our configuration:

hub:
  adminUser: admin
  configuration: |
    Chart:
      Name: {{ .Chart.Name }}
      Version: {{ .Chart.Version }}
    Release:
      Name: {{ .Release.Name }}
      Namespace: {{ .Release.Namespace }}
      Service: {{ .Release.Service }}
    hub:
      config:
        JupyterHub:
          admin_access: true
          authenticator_class: generic-oauth
          GenericOAuthenticator:
            client_id: jupyter
            client_secret: <our_secret>
            oauth_callback_url: http://jupyterhub_site.com/hub/oauth_callback
            authorize_url: http://keycloak-site.com/realms/jupyterhub/protocol/openid-connect/auth
            token_url: http://keycloak-site.com/realms/jupyterhub/protocol/openid-connect/token
            userdata_url: http://keycloak-site.com/realms/jupyterhub/protocol/openid-connect/userinfo
            username_claim: nijat
            tls_verify: false
            enable_auth_state: true
            login_service: 'Keycloak'
            redirectToServer: true
            
Besides that I've create a new client in keycloak, with client id <jupyter> and client_secret. My URLs in Keycloak:

Root URL - http://jupyterhub_site.com 
Home URL - http://jupyterhub_site.com
Valid redirect URIs -http://jupyterhub_site.com/* and http://jupyterhub_site.com/hub/oauth_callback

And what's now. I am going through the route I created in openshift, see the button - Sign in using keycloak. After I enter it it redirects me to keycloak page with the name of jupyterhub realm and asks for login and pass. I write it and get 500 Internal Error. Here's the log of my pod - hub:

[I 2024-10-14 08:59:18.499 JupyterHub _xsrf_utils:125] Setting new xsrf cookie for b'None:yQnovSbPbgJXTCPDcbdY9I3fKLs9DEop10jkRmVpaYE=' {'path': '/hub/', 'max_age': 3600}
[I 2024-10-14 08:59:18.502 JupyterHub log:192] 200 GET /hub/login?next=%2Fhub%2F (@::ffff:10.135.0.2) 4.89ms
[I 2024-10-14 08:59:19.534 JupyterHub oauth2:113] OAuth redirect: http://jupyterhub_site.com/hub/oauth_callback
[I 2024-10-14 08:59:19.535 JupyterHub log:192] 302 GET /hub/oauth_login?next=%2Fhub%2F -> http://keycloak-site.com/realms/jupyterhub/protocol/openid-connect/auth?response_type=code&redirect_uri=http%3A%2F%2Ftest-jupyterhub.apps.data-ocp.abb-bank.az%2Fhub%2Foauth_callback&client_id=jyputer&state=[secret] (@::ffff:10.135.0.2) 1.22ms
[E 2024-10-14 08:59:38.043 JupyterHub oauth2:782] Error fetching 599 POST http://keycloak-site.com/realms/jupyterhub/protocol/openid-connect/token: HTTP 599: error setting certificate verify locations:
      CAfile: /etc/pki/tls/certs/ca-bundle.crt
      CApath: none
    Traceback (most recent call last):
      File "/opt/bitnami/miniforge/lib/python3.12/site-packages/tornado/web.py", line 1790, in _execute
        result = await result
                 ^^^^^^^^^^^^
      File "/opt/bitnami/miniforge/lib/python3.12/site-packages/oauthenticator/oauth2.py", line 224, in get
        user = await self.login_user()
               ^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/bitnami/miniforge/lib/python3.12/site-packages/jupyterhub/handlers/base.py", line 928, in login_user
        authenticated = await self.authenticate(data)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/bitnami/miniforge/lib/python3.12/site-packages/jupyterhub/auth.py", line 493, in get_authenticated_user
        authenticated = await maybe_future(self.authenticate(handler, data))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/bitnami/miniforge/lib/python3.12/site-packages/oauthenticator/oauth2.py", line 1230, in authenticate
        token_info = await self.get_token_info(handler, access_token_params)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/bitnami/miniforge/lib/python3.12/site-packages/oauthenticator/oauth2.py", line 1005, in get_token_info
        token_info = await self.httpfetch(
                     ^^^^^^^^^^^^^^^^^^^^^
      File "/opt/bitnami/miniforge/lib/python3.12/site-packages/oauthenticator/oauth2.py", line 817, in httpfetch
        return await self.fetch(
               ^^^^^^^^^^^^^^^^^
      File "/opt/bitnami/miniforge/lib/python3.12/site-packages/oauthenticator/oauth2.py", line 783, in fetch
        raise e
      File "/opt/bitnami/miniforge/lib/python3.12/site-packages/oauthenticator/oauth2.py", line 762, in fetch
        resp = await self.http_client.fetch(req, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    tornado.curl_httpclient.CurlError: HTTP 599: error setting certificate verify locations:
      CAfile: /etc/pki/tls/certs/ca-bundle.crt
      CApath: none
    
[E 2024-10-14 08:59:38.045 JupyterHub log:184] {
      "X-Forwarded-For": "10.64.202.34,::ffff:10.135.0.2",
      "Forwarded": "for=10.64.202.34;host=jupyterhub_site.com;proto=http",
      "X-Forwarded-Proto": "http,http",
      "X-Forwarded-Port": "80,80",
      "X-Forwarded-Host": "jupyterhub_site.com",
      "Host": "test-jupyterhub.apps.data-ocp.abb-bank.az",
      "Cookie": "_xsrf=[secret]; oauthenticator-state=[secret]",
      "Accept-Language": "en-US,en;q=0.9",
      "Accept-Encoding": "gzip, deflate",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36",
      "Upgrade-Insecure-Requests": "1",
      "Cache-Control": "max-age=0",
      "Connection": "keep-alive"
    }
[E 2024-10-14 08:59:38.045 JupyterHub log:192] 500 GET /hub/oauth_callback?state=[secret]&session_state=[secret]&iss=https%3A%2F%2Fkeycloak-site.com%2Frealms%2Fjupyterhub&code=[secret] (@::ffff:10.135.0.2) 6038.91ms

How can I solve this problem, please help

**Comment by manics** [comment]
https://discourse.jupyter.org/ is the correct place for these questions. We rely on the community to answer a lot of these questions, although we're developers we have no way of researeching all the differnt possible external OAuth providers.

I can't find your post on Discourse, can you link to it?

**Comment by Najafov007** [comment]
> https://discourse.jupyter.org/ is the correct place for these questions. We rely on the community to answer a lot of these questions, although we're developers we have no way of researching all the different possible external OAuth providers.
> 
> I can't find your post on Discourse, can you link to it?

https://discourse.jupyter.org/t/jupyterhub-keycloak-integration-error/29202

**Comment by Najafov007** [comment]
> ### Bug description
> Hello, I've asked this question in Jupyterhub community but didnt get any solution. The problem is with integration jupyterhub with keycloak. So we are in openshift and installing jupyterhub using bitnami helm chart. Here's our configuration:
> 
> hub: adminUser: admin configuration: | Chart: Name: {{ .Chart.Name }} Version: {{ .Chart.Version }} Release: Name: {{ .Release.Name }} Namespace: {{ .Release.Namespace }} Service: {{ .Release.Service }} hub: config: JupyterHub: admin_access: true authenticator_class: generic-oauth GenericOAuthenticator: client_id: jupyter client_secret: <our_secret> oauth_callback_url: http://jupyterhub_site.com/hub/oauth_callback authorize_url: http://keycloak-site.com/realms/jupyterhub/protocol/openid-connect/auth token_url: http://keycloak-site.com/realms/jupyterhub/protocol/openid-connect/token userdata_url: http://keycloak-site.com/realms/jupyterhub/protocol/openid-connect/userinfo username_claim: nijat tls_verify: false enable_auth_state: true login_service: 'Keycloak' redirectToServer: true
> 
> Besides that I've create a new client in keycloak, with client id and client_secret. My URLs in Keycloak:
> 
> Root URL - http://jupyterhub_site.com Home URL - http://jupyterhub_site.com Valid redirect URIs -http://jupyterhub_site.com/* and http://jupyterhub_site.com/hub/oauth_callback
> 
> And what's now. I am going through the route I created in openshift, see the button - Sign in using keycloak. After I enter it it redirects me to keycloak page with the name of jupyterhub realm and asks for login and pass. I write it and get 500 Internal Error. Here's the log of my pod - hub:
> 
> [I 2024-10-14 08:59:18.499 JupyterHub _xsrf_utils:125] Setting new xsrf cookie for b'None:yQnovSbPbgJXTCPDcbdY9I3fKLs9DEop10jkRmVpaYE=' {'path': '/hub/', 'max_age': 3600} [I 2024-10-14 08:59:18.502 JupyterHub log:192] 200 GET /hub/login?next=%2Fhub%2F (@::ffff:10.135.0.2) 4.89ms [I 2024-10-14 08:59:19.534 JupyterHub oauth2:113] OAuth redirect: http://jupyterhub_site.com/hub/oauth_callback [I 2024-10-14 08:59:19.535 JupyterHub log:192] 302 GET /hub/oauth_login?next=%2Fhub%2F -> [http://keycloak-site.com/realms/jupyterhub/protocol/openid-connect/auth?response_type=code&redirect_uri=http%3A%2F%2Ftest-jupyterhub.apps.data-ocp.abb-bank.az%2Fhub%2Foauth_callback&client_id=jyputer&state=[secret]](http://keycloak-site.com/realms/jupyterhub/protocol/openid-connect/auth?response_type=code&redirect_uri=http%3A%2F%2Ftest-jupyterhub.apps.data-ocp.abb-bank.az%2Fhub%2Foauth_callback&client_id=jyputer&state=%5Bsecret%5D) (@::ffff:10.135.0.2) 1.22ms [E 2024-10-14 08:59:38.043 JupyterHub oauth2:782] Error fetching 599 POST http://keycloak-site.com/realms/jupyterhub/protocol/openid-connect/token: HTTP 599: error setting certificate verify locations: CAfile: /etc/pki/tls/certs/ca-bundle.crt CApath: none Traceback (most recent call last): File "/opt/bitnami/miniforge/lib/python3.12/site-packages/tornado/web.py", line 1790, in _execute result = await result ^^^^^^^^^^^^ File "/opt/bitnami/miniforge/lib/python3.12/site-packages/oauthenticator/oauth2.py", line 224, in get user = await self.login_user() ^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/bitnami/miniforge/lib/python3.12/site-packages/jupyterhub/handlers/base.py", line 928, in login_user authenticated = await self.authenticate(data) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/bitnami/miniforge/lib/python3.12/site-packages/jupyterhub/auth.py", line 493, in get_authenticated_user authenticated = await maybe_future(self.authenticate(handler, data)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/bitnami/miniforge/lib/python3.12/site-packages/oauthenticator/oauth2.py", line 1230, in authenticate token_info = await self.get_token_info(handler, access_token_params) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/bitnami/miniforge/lib/python3.12/site-packages/oauthenticator/oauth2.py", line 1005, in get_token_info token_info = await self.httpfetch( ^^^^^^^^^^^^^^^^^^^^^ File "/opt/bitnami/miniforge/lib/python3.12/site-packages/oauthenticator/oauth2.py", line 817, in httpfetch return await self.fetch( ^^^^^^^^^^^^^^^^^ File "/opt/bitnami/miniforge/lib/python3.12/site-packages/oauthenticator/oauth2.py", line 783, in fetch raise e File "/opt/bitnami/miniforge/lib/python3.12/site-packages/oauthenticator/oauth2.py", line 762, in fetch resp = await self.http_client.fetch(req, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ tornado.curl_httpclient.CurlError: HTTP 599: error setting certificate verify locations: CAfile: /etc/pki/tls/certs/ca-bundle.crt CApath: none
> 
> [E 2024-10-14 08:59:38.045 JupyterHub log:184] { "X-Forwarded-For": "10.64.202.34,::ffff:10.135.0.2", "Forwarded": "for=10.64.202.34;host=jupyterhub_site.com;proto=http", "X-Forwarded-Proto": "http,http", "X-Forwarded-Port": "80,80", "X-Forwarded-Host": "jupyterhub_site.com", "Host": "test-jupyterhub.apps.data-ocp.abb-bank.az", "Cookie": "_xsrf=[secret]; oauthenticator-state=[secret]", "Accept-Language": "en-US,en;q=0.9", "Accept-Encoding": "gzip, deflate", "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,_/_;q=0.8,application/signed-exchange;v=b3;q=0.7", "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36", "Upgrade-Insecure-Requests": "1", "Cache-Control": "max-age=0", "Connection": "keep-alive" } [E 2024-10-14 08:59:38.045 JupyterHub log:192] 500 GET /hub/oauth_callback?state=[secret]&session_state=[secret]&iss=https%3A%2F%2Fkeycloak-site.com%2Frealms%2Fjupyterhub&code=[secret] (@::ffff:10.135.0.2) 6038.91ms
> 
> How can I solve this problem, please help

https://discourse.jupyter.org/t/jupyterhub-keycloak-integration-error/29202
