### ISSUE TITLE
Auth0 authenticator is not accessible

### ISSUE THREAD

**Issue by efagerberg** [jupyterhub/oauthenticator#86]
I notice that the `oauthenticator.auth0.Auth0OAuthenticator` is not accessible in the latest release of oauthenticator.

I cloned from master to make sure it was not just the latest release. Confirmed the oauth submodule does not show up.

Are there plans to expose that class in the next release?

**Comment by willingc** [comment]
Hi @efagerberg,

Did you enable the custom mode for this within `jupyterhub_config.py`? [Ref](https://github.com/jupyterhub/oauthenticator/blob/5ebe2dcdfbb82be8dfcb4d3f72fc1633fd761a8a/oauthenticator/auth0.py#L19)

**Comment by efagerberg** [comment]
Hey @willingc yes I did. The failure comes actually from the class not being accessible itself.

This is the error I get when trying to use the authenticator 
`c.JupyterHub.authenticator_class = 'oauthenticator.auth0.Auth0OAuthenticator'`

> The 'authenticator_class' trait of <jupyterhub.app.JupyterHub object at 0x7fa7682789b0> instance must be a type, but 'oauthenticator.auth0.Auth0OAuth
> enticator' could not be imported

When I clone the master branch of `oauthenticator` I see that the `auth0` submodule is not exposed.
```

Type "help", "copyright", "credits" or "license" for more information.
>>> import oauthenticator
>>> dir(oauthenticator)
['AsyncHTTPClient', 'Authenticator', 'BaseHandler', 'BitbucketLoginHandler', 'BitbucketMixin', 'BitbucketOAuthenticator', 'GITHUB_API', 'GITHUB_HOST', 'GitHubLoginHandler', 'GitHubMixin', 'GitHubOAuthent
icator', 'GoogleLoginHandler', 'GoogleOAuth2Mixin', 'GoogleOAuthHandler', 'GoogleOAuthenticator', 'HTTPError', 'HTTPRequest', 'LocalAuthenticator', 'LocalBitbucketOAuthenticator', 'LocalGitHubOAuthentica
tor', 'LocalGoogleOAuthenticator', 'OAuth2Mixin', 'OAuthCallbackHandler', 'OAuthLoginHandler', 'OAuthenticator', 'Set', 'Unicode', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__na
me__', '__package__', '__path__', '__spec__', '__version__', '_version', 'bitbucket', 'gen', 'github', 'google', 'json', 'oauth2', 'os', 'url_concat', 'url_path_join', 'urllib', 'version_info', 'web']
```

**Comment by minrk** [comment]
There hasn't been a release since auth0 was added, so it's only in master right now. Your config is exactly right for use with master right now, or when it's released as 0.6. I've just tested with master to confirm that this works.

> Probably because https://github.com/jupyterhub/oauthenticator/blob/master/oauthenticator/__init__.py does not include that module I would guess.

Most authenticators shouldn't be in `oauthenticator.__init__` because that would result in all authenticators being imported when only one is used. Only the earliest ones are there for backward compatibility.

**Comment by efagerberg** [comment]
I feel very silly, I was in the wrong directory when testing the master branch. @minrk thanks for the clarification.

**Comment by minrk** [comment]
No problem. Hopefully we will get the next oauthenticator release out soon.

**Comment by efagerberg** [comment]
It turns out I was in the right directory, the module does not show up for python3 but does for python2. Is it only Python2 compatible?

```
(oauthenticator) ~/workspaces/python_workspace/oauthenticator (master) $ python3
Python 3.5.3rc1 (v3.5.3rc1:de530d7f21c0, Jan  1 2017, 23:25:25)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import oauthenticator
>>> dir(oauthenticator)
['AsyncHTTPClient', 'Authenticator', 'BaseHandler', 'BitbucketLoginHandler', 'BitbucketMixin', 'BitbucketOAuthenticator', 'Bool', 'GITHUB_API', 'GITHUB_HOST', 'GitHubLoginHandler', 'GitHubMixin', 'GitHub
OAuthenticator', 'GoogleLoginHandler', 'GoogleOAuth2Mixin', 'GoogleOAuthHandler', 'GoogleOAuthenticator', 'HTTPError', 'HTTPRequest', 'LocalAuthenticator', 'LocalBitbucketOAuthenticator', 'LocalGitHubOAu
thenticator', 'LocalGoogleOAuthenticator', 'OAuth2Mixin', 'OAuthCallbackHandler', 'OAuthLoginHandler', 'OAuthenticator', 'STATE_COOKIE_NAME', 'Set', 'Unicode', '__builtins__', '__cached__', '__doc__', '_
_file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_version', 'bitbucket', 'common', 'gen', 'github', 'google', 'guess_callback_uri', 'json', 'next_page_from_links
', 'oauth2', 'os', 're', 'url_concat', 'url_path_join', 'urllib', 'uuid', 'version_info', 'web']
```

If so should I open a separate issue?

**Comment by willingc** [comment]
Hi @efagerberg, 

Perhaps double-check that you have the package installed for python3:
```
python3 -m pip show oauthenticator
```

If not, install with:
```
python3 -m pip install oauthenticator
```

I hope that helps you.

**Comment by efagerberg** [comment]
Thanks for the suggestion @willingc. However the example I pasted was off me testing in the master branch of this repo.

**Comment by efagerberg** [comment]
I see now I got confused by how python3 handles `dir` if I try to get the module directly it works.

**Comment by willingc** [comment]
@efagerberg I'm glad it's working for you.
